"""Isolated browser acceptance. Real TSX/CSS/React; mocked transport and media.
Requires Python Playwright. Does not contact Supabase, Luna or actual microphones.
Usage: python scripts/sa-visual/browser-checks.py /tmp/sa-preview /tmp/sa-evidence
"""
from pathlib import Path
import base64, json, os, sys
from playwright.sync_api import sync_playwright

preview=Path(sys.argv[1] if len(sys.argv)>1 else '/tmp/sa-preview')
out=Path(sys.argv[2] if len(sys.argv)>2 else '/tmp/sa-evidence');out.mkdir(parents=True,exist_ok=True)
css=(preview/'style.css').read_text(); runtime=(preview/'react.js').read_text(); dom=(preview/'react-dom.js').read_text(); bundle=(preview/'bundle.js').read_text()
for asset in (preview/'smart-assistant').iterdir():
    if '/smart-assistant/'+asset.name in bundle:
        bundle=bundle.replace('/smart-assistant/'+asset.name,'data:image/'+('webp' if asset.suffix=='.webp' else 'png')+';base64,'+base64.b64encode(asset.read_bytes()).decode())
results=[];errors=[]
def check(name,condition,details=None):
    results.append({'name':name,'passed':bool(condition),'details':details})
    if not condition: print('FAIL',name,details)
def mount(browser,query='',width=390,height=844,reduced=False,touch=False):
    page=browser.new_page(viewport={'width':width,'height':height},device_scale_factor=1,is_mobile=touch,has_touch=touch,reduced_motion='reduce' if reduced else 'no-preference')
    page.on('pageerror',lambda error:errors.append(str(error)))
    # Own source is rendered directly; this also works in managed browsers that block local HTTP.
    page.set_content('<html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"></head><body><main id="app"></main></body></html>')
    page.add_style_tag(content=css);page.evaluate('(q)=>window.__previewQuery=q',query)
    page.add_script_tag(content=runtime);page.add_script_tag(content=dom);page.add_script_tag(content=bundle)
    page.wait_for_selector('[data-sa-experience="visual-v2"]');page.wait_for_timeout(100)
    return page

def screenshot(page,name):
    page.evaluate('document.activeElement?.blur()')
    page.screenshot(path=str(out/(name+'.png')))

def metrics(page):
    return page.evaluate('''() => {
      const root=document.querySelector('[data-sa-v2]'),h=root.querySelector('header'),m=root.querySelector('[aria-label="Conversation"]'),dock=root.querySelector('[aria-label="Input controls"]');
      const r=e=>{const x=e.getBoundingClientRect();return {x:x.x,y:x.y,w:x.width,h:x.height,right:x.right,bottom:x.bottom};};
      return {root:r(root),header:r(h),messages:r(m),dock:r(dock),headerChildren:[...h.children].map(r),overflow:root.scrollWidth-root.clientWidth,dark:getComputedStyle(root).backgroundColor,selected:root.querySelectorAll('[aria-label="Input controls"] button[aria-pressed="true"]').length};
    }''')

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),args=['--no-sandbox'])
    version=browser.version
    # Responsive composition: real browser layout, no image generator.
    for w,h,label in [(320,568,'small-phone'),(360,640,'phone-360'),(390,844,'phone'),(430,932,'large-phone'),(768,1024,'tablet'),(1440,900,'desktop'),(844,390,'landscape')]:
        for mode in ['text','voice']:
            p=mount(browser,f'mode={mode}&scene=records',w,h)
            mm=metrics(p)
            check(f'{label}/{mode}: header stays one row',mm['header']['h']<=80,mm)
            check(f'{label}/{mode}: no horizontal overflow',mm['overflow']<=1,mm)
            check(f'{label}/{mode}: controls fit the viewport',mm['dock']['bottom']<=h+1 and mm['header']['y']>=-1,mm)
            check(f'{label}/{mode}: conversation gets majority of usable height',mm['messages']['h']>=(h-mm['header']['h'])*.50,mm)
            check(f'{label}/{mode}: exactly one input mode selected',mm['selected']==1)
            if label in ['phone','desktop','small-phone']: screenshot(p,f'{label}-{mode}-records')
            p.close()
    p=mount(browser,'mode=text');screenshot(p,'01-phone-type')
    check('Type idle send disabled',p.get_by_role('button',name='Send message',exact=True).is_disabled())
    p.get_by_role('textbox',name='Message the assistant').fill('Find my latest quote')
    p.get_by_role('button',name='Send message',exact=True).click();p.wait_for_timeout(300)
    check('Typed message reaches existing turn endpoint unchanged',p.evaluate('__fixture.posts[0].body.message')=='Find my latest quote')
    check('Typed send keeps clientRequestId',bool(p.evaluate('__fixture.posts[0].body.clientRequestId')))
    p.close()
    p=mount(browser,'mode=voice');screenshot(p,'02-phone-voice-ready')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(450)
    check('Tap starts microphone without submitting a turn',p.evaluate('__fixture.recorders===1 && __fixture.posts.length===0'))
    check('Recording label is visible',p.get_by_text('Your microphone is on',exact=True).is_visible())
    check('Waveform reflects nonzero simulated amplitude',p.evaluate('Math.max(...[...document.querySelectorAll("[class*=waveform] span")].map(e=>parseFloat(e.style.height)))>20'))
    screenshot(p,'03-phone-recording')
    p.evaluate('__fixture.signal=0');p.wait_for_timeout(300)
    check('Silence becomes dots, not decorative motion',p.evaluate('[...document.querySelectorAll("[class*=waveform] span")].every(e=>parseFloat(e.style.height)===5)'))
    p.get_by_role('button',name='Finish recording',exact=True).click();p.wait_for_timeout(500)
    check('Finish transcribes once',p.evaluate('__fixture.transcriptions===1'))
    check('Transcript review does not auto-send',p.evaluate('__fixture.posts.length===0'))
    check('Transcript has explicit Send',p.get_by_role('button',name='Send message',exact=True).is_visible())
    screenshot(p,'04-phone-transcript')
    p.get_by_role('button',name='Send message',exact=True).click();p.wait_for_timeout(300)
    check('Transcript becomes the normal text turn',p.evaluate('__fixture.posts[0].body.message')=='Find the Smith quote and tell me how much Ridge costs.')
    check('Capture tracks stop after finish',p.evaluate('__fixture.stops>=1'))
    p.close()
    p=mount(browser,'mode=voice&scene=records')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(450)
    p.get_by_role('button',name='Cancel',exact=True).click();p.wait_for_timeout(100)
    check('Cancel records no transcription or turn',p.evaluate('__fixture.transcriptions===0 && __fixture.posts.length===0'))
    check('Cancel releases microphone tracks',p.evaluate('__fixture.stops>=1'))
    p.close()
    p=mount(browser,'mode=voice')
    bb=p.get_by_role('button',name='Start recording',exact=True).bounding_box();p.mouse.move(bb['x']+bb['width']/2,bb['y']+bb['height']/2);p.mouse.down();p.wait_for_timeout(500);p.mouse.up();p.wait_for_timeout(500)
    check('Press/hold/release goes to transcript review',p.get_by_role('button',name='Send message',exact=True).is_visible())
    p.close()
    p=mount(browser,'mode=voice');p.evaluate('__fixture.permission="denied"')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(150)
    check('Permission failure remains visible',p.get_by_role('alert').count()==1)
    p.get_by_role('button',name='Type',exact=True).click()
    check('Mic failure never disables typing',p.get_by_role('textbox',name='Message the assistant').is_enabled())
    screenshot(p,'phone-microphone-denied');p.close()
    p=mount(browser,'scene=records')
    p.get_by_role('button',name='Turn spoken replies on',exact=True).click();p.wait_for_timeout(100)
    check('Enabling speech does not replay history',p.evaluate('__fixture.audio.length===0'))
    p.get_by_role('textbox',name='Message the assistant').fill('What does Ridge cost?');p.get_by_role('button',name='Send message',exact=True).click();p.wait_for_timeout(300)
    check('New completed answer can speak',p.evaluate('__fixture.audio.length===1'))
    check('Text remains visible during speech',p.get_by_text('Your saved quote is ready to open.',exact=False).count()>0)
    screenshot(p,'06-phone-spoken-answer')
    posts=p.evaluate('__fixture.posts.length');p.get_by_role('button',name='Pause speech',exact=True).click();p.get_by_role('button',name='Resume speech',exact=True).click();p.get_by_role('button',name='Stop speech',exact=True).click()
    check('Pause/resume/stop never submits a task',p.evaluate('__fixture.posts.length')==posts)
    check('Stopped speech does not restart on render',p.evaluate('__fixture.audio.length===1'))
    p.close()
    p=mount(browser,'mode=voice&scene=records')
    p.get_by_role('button',name='Attach a photo or file',exact=True).click();p.wait_for_timeout(200)
    check('Attachment opens a dialog sheet',p.get_by_role('dialog',name='Add an attachment').is_visible())
    check('Attachment does not become a third selected input mode',p.locator('[aria-label="Input controls"] button[aria-pressed="true"]').count()==1)
    check('Background assistant is inert while sheet is open',p.evaluate('document.querySelector("[class*=frame]").inert'))
    screenshot(p,'05-phone-attachment-sheet')
    p.keyboard.press('Escape');p.wait_for_timeout(100)
    check('Escape closes sheet, not assistant',p.get_by_role('dialog',name='Add an attachment').count()==0 and p.locator('[data-sa-v2]').is_visible())
    check('Closing sheet restores focus to Attach',p.evaluate('document.activeElement.getAttribute("aria-label")')=='Attach a photo or file')
    p.get_by_role('button',name='Attach a photo or file',exact=True).click()
    p.locator('input[type=file][accept="application/pdf,text/plain"]').set_input_files({'name':'site-notes.txt','mimeType':'text/plain','buffer':b'Roof area 89 m2'})
    p.wait_for_timeout(100)
    check('File preview is explicitly not uploaded',p.get_by_text('On this device · not uploaded',exact=True).is_visible())
    p.get_by_role('button',name='Type',exact=True).click();p.get_by_role('textbox',name='Message the assistant').fill('Read this image')
    check('Sending unsupported attachments is blocked, not fake metadata',p.get_by_role('button',name='Send message',exact=True).is_disabled() and p.evaluate('__fixture.posts.length===0'))
    p.get_by_role('button',name='Remove site-notes.txt',exact=True).click()
    check('Removing preview restores send',p.get_by_role('button',name='Send message',exact=True).is_enabled())
    p.close()
    p=mount(browser,'mode=text&scene=proposal');screenshot(p,'07-phone-proposal')
    p.get_by_role('button',name='Confirm these changes',exact=True).click();p.wait_for_timeout(150)
    post=p.evaluate('__fixture.posts[0]');check('Confirm retains action proof/version/company payload',post['url'].endswith('/actions') and post['body'].get('command')=='confirm' and len(post['body'].get('proofDigest',''))==64 and post['body'].get('version')==1)
    p.close()
    p=mount(browser,'scene=candidates&mode=voice');screenshot(p,'phone-candidates')
    p.get_by_role('button',name='Ridge · Smith Roof',exact=False).click();p.wait_for_timeout(250)
    post=p.evaluate('__fixture.posts[0]');check('Candidate selection uses existing encoded turn, not action confirmation',post['url'].endswith('/turn') and post['body']['message'].startswith('[[sa-resolution:v1:') and post['body']['message'].endswith(']]'))
    p.close()
    p=mount(browser,'scene=stale')
    check('Stale resolver buttons remain disabled',p.get_by_role('button',name='Ridge · Smith Roof',exact=False).is_disabled())
    p.close()
    p=mount(browser,'scene=records')
    p.get_by_role('button',name='Done',exact=True).click();p.wait_for_timeout(150)
    check('Done uses task metadata, never actions endpoint',p.evaluate('__fixture.posts.length===1 && __fixture.posts[0].url.endsWith("/task")'))
    p.close()
    p=mount(browser,'mode=text&scene=failed');screenshot(p,'phone-failed-request')
    check('One failed request has one inline recovery',p.locator('[data-sa-failed-run]').count()==1 and p.get_by_role('button',name='Retry request',exact=True).count()==1)
    p.close()
    p=mount(browser,'mode=voice&scene=records')
    p.get_by_role('button',name='Hide assistant',exact=True).click();p.get_by_role('button',name='Reopen assistant',exact=True).click();p.wait_for_timeout(150)
    check('Hide/reopen preserves conversation',p.get_by_role('button',name='Open Quote #1014 · Smith Roof and hide assistant',exact=True).count()==1)
    p.close()
    p=mount(browser,'mode=text&scene=proposal&host=dialog',1440,900);screenshot(p,'08-desktop-panel')
    mm=metrics(p);check('Desktop panel is compact, not a stretched phone',440<=mm['root']['w']<=500 and mm['root']['x']>800,mm);p.close()
    p=mount(browser,'mode=voice',390,844,reduced=True)
    check('Reduced motion disables decorative transitions',p.get_by_role('button',name='Start recording',exact=True).evaluate('(e)=>getComputedStyle(e).transitionDuration')=='0s')
    p.close()
    # Simulated keyboard-sized visual viewport: the browser is not a real iOS keyboard.
    p=mount(browser,'mode=text&scene=records',390,844)
    p.evaluate('''() => {const v=new EventTarget();Object.assign(v,{height:410,width:390,offsetTop:0,scale:1});Object.defineProperty(window,'visualViewport',{configurable:true,value:v});window.__fixture.setVisible(false);}''');p.wait_for_timeout(50)
    p.evaluate('__fixture.setVisible(true)');p.wait_for_timeout(150)
    mm=metrics(p);check('Visual viewport resize keeps dock above keyboard boundary',mm['dock']['bottom']<=411,mm);screenshot(p,'phone-keyboard-sized-viewport');p.close()
    # Lifecycle regressions: late device/provider events must not cross threads or resume cancelled UI.
    p=mount(browser,'mode=voice');p.evaluate('__fixture.permission="waiting"')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(100)
    p.get_by_role('button',name='Hide assistant',exact=True).click();p.evaluate('__fixture.resolveMic()');p.wait_for_timeout(150)
    check('Hiding during permission request releases a late microphone stream',p.evaluate('__fixture.stops===1 && __fixture.recorders===0 && __fixture.posts.length===0'))
    p.get_by_role('button',name='Reopen assistant',exact=True).click();p.wait_for_timeout(100)
    check('Reopen after late microphone permission is idle',p.get_by_role('button',name='Start recording',exact=True).is_visible())
    p.close()
    p=mount(browser,'mode=voice');p.evaluate('__fixture.delay=600')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(450)
    p.get_by_role('button',name='Finish recording',exact=True).click();p.wait_for_timeout(50)
    p.get_by_role('button',name='Cancel',exact=True).click();p.wait_for_timeout(800)
    check('Late transcription after Cancel cannot refill the composer',p.get_by_role('button',name='Start recording',exact=True).is_visible() and p.get_by_role('button',name='Send message',exact=True).count()==0)
    check('Cancelled transcription never creates an assistant turn',p.evaluate('__fixture.posts.length===0'))
    p.close()
    p=mount(browser,'mode=voice')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(20)
    p.get_by_role('button',name='Finish recording',exact=True).click();p.wait_for_timeout(50)
    check('A quick second tap keeps recording latched',p.evaluate('__fixture.recorders===1 && __fixture.transcriptions===0'))
    p.wait_for_timeout(400);p.get_by_role('button',name='Finish recording',exact=True).click();p.wait_for_timeout(450)
    check('A deliberate Finish after double-tap still reaches review',p.get_by_role('button',name='Send message',exact=True).is_visible())
    p.close()
    p=mount(browser,'mode=voice&scene=records')
    p.get_by_role('button',name='Read this answer aloud',exact=True).click();p.wait_for_timeout(100)
    p.evaluate('__fixture.oldUtterance=__fixture.currentUtterance')
    cancelled=p.evaluate('__fixture.speechCancelled')
    p.get_by_role('button',name='Start recording',exact=True).click();p.wait_for_timeout(450)
    check('Recording stops playback before using the microphone',p.evaluate('__fixture.speechCancelled')>cancelled and p.get_by_role('button',name='Stop speech',exact=True).count()==0)
    p.evaluate('__fixture.oldUtterance.onend?.()');p.wait_for_timeout(100)
    check('A late cancelled speech event cannot restart audio',p.evaluate('__fixture.audio.length===1'))
    p.close()
    p=mount(browser,'scene=records')
    p.get_by_role('button',name='Assistant menu',exact=True).click();p.wait_for_timeout(100)
    p.keyboard.press('Shift+Tab')
    check('Sheet keyboard focus cannot escape to the conversation',p.evaluate("document.activeElement.closest('[role=\"dialog\"]') !== null"))
    p.keyboard.press('Escape');p.wait_for_timeout(100)
    check('Menu closes with focus returned to the branded Q',p.evaluate('document.activeElement.getAttribute("aria-label")')=='Assistant menu')
    p.close()
    p=mount(browser,'mode=text',390,844,touch=True)
    p.get_by_role('textbox',name='Message the assistant').fill('First line')
    p.get_by_role('textbox',name='Message the assistant').press('Enter');p.wait_for_timeout(100)
    check('Mobile Enter inserts a line break instead of sending',p.evaluate('__fixture.posts.length===0') and '\n' in p.get_by_role('textbox',name='Message the assistant').input_value())
    p.close()
    browser.close()
check('No browser runtime exceptions',not errors,errors)
report={'runtime':'actual React '+('18.2.0 (installed offline JupyterLab runtime)' if 'ReactDOM 18.2' in dom else 'project UMD runtime'),'chromium':version,'checks':len(results),'passed':sum(r['passed'] for r in results),'failed':sum(not r['passed'] for r in results),'results':results,'limitations':['Mock transport, not Supabase/RLS or Luna','Simulated audio input and speech output, not real microphone/TTS quality','Not a full Next build or authenticated deployed shell','Keyboard size simulation, not native iOS/Android keyboard certification']}
(out/'browser-results.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:report[k] for k in ['checks','passed','failed','runtime']},indent=2))
if report['failed']:sys.exit(1)
