import {calculateJob,referenceValue,fmt,money,specUnit,TRADE_COPY,type Job} from './measurement-model';
import {csvCell} from './measurement-csv';
export function escapeHtml(text:string|number):string{return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function resultCsv(job:Job,r=calculateJob(job)):string{
 if(!r.valid)throw Error('Complete the measurements before exporting.');
 const rows:(string|number)[][]=[['Area','Component','Unit','Measured after pitch','Waste','Quantity including waste','Packs','Material cost','Labour cost','Total','Currency','Pricing','Measurements / working']];
 for(const row of r.rows.filter(row=>!row.unused))rows.push([row.areaName,row.component.name,row.unit,row.adjusted,row.waste,row.quantity,row.packs,row.material,row.labour,row.total,job.currency,row.example?'EXAMPLE  -  replace rates':'User-entered',row.entries.filter(e=>!e.blank).map(e=>`${e.label}: ${e.working}${e.source?` [linked: ${e.source}]`:''}`).join('; ')]);
 return '\uFEFF'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n');
}
export function resultText(job:Job,r=calculateJob(job)){return `${job.title||'Measurements to pricing'}  -  ${TRADE_COPY[job.trade].name}\n${r.hasExamples?'EXAMPLE PRICING  -  replace before quoting\n':''}${r.rows.filter(x=>!x.unused).map(row=>`${row.areaName} / ${row.component.name}: ${fmt(row.quantity)} ${row.unit} including waste · ${money(row.total,job.currency)}`).join('\n')}\nMaterial ${money(r.material,job.currency)}\nLabour ${money(r.labour,job.currency)}\nTotal ${money(r.total,job.currency)} ${job.currency} before tax & margin.`;}
export function reportHtml(job:Job,r=calculateJob(job)):string{
 if(!r.valid)throw Error('Complete the measurements before exporting.');const h=escapeHtml;
 const groups=r.areas.map(({area,rows,total})=>{const active=rows.filter(row=>!row.unused);if(!active.length)return '';const ref=referenceValue(area,job.units);
 return `<section class="area"><h2>${h(area.name)} <span>${h(money(total,job.currency))}</span></h2>${ref!==null?`<p class="muted">Saved reference size: ${h(fmt(ref))} ${h(specUnit('area',job.units))}. Reference only, not a separate charge.</p>`:''}${active.map(row=>`<section class="component ${row.entries.filter(e=>!e.blank).length<=6?'keep':''}"><table><thead><tr class="component-context"><th colspan="3"><div class="component-title"><h3>${h(row.component.name)}${row.example?' <em>Example rates</em>':''}</h3><b>${h(money(row.total,job.currency))}</b></div><small>${h(area.name)}</small></th></tr><tr><th>Measurement</th><th>Working</th><th>Quantity (${h(row.unit)})</th></tr></thead><tbody>${row.entries.filter(e=>!e.blank).map(e=>`<tr><td>${h(e.label)}${e.source?`<small>Linked: ${h(e.source)}</small>`:''}</td><td>${h(e.working)}</td><td>${h(fmt(e.adjusted,4))}</td></tr>`).join('')}</tbody></table><p class="working">Measured ${h(fmt(row.adjusted,4))} ${h(row.unit)} + waste ${h(fmt(row.waste,4))} = <b>${h(fmt(row.quantity,4))} ${h(row.unit)}</b>${row.packs?` · ${row.packs} whole packs`:''}<br>Material ${h(money(row.material,job.currency))} + labour ${h(money(row.labour,job.currency))}.</p></section>`).join('')}</section>`;
 }).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(job.title||'Measurements to pricing')}  -  QuoteCore+</title><style>
 @page{size:A4;margin:15mm 14mm}*{box-sizing:border-box}body{font:12px/1.5 Arial,sans-serif;color:#191c21;background:#fff;max-width:900px;margin:25px auto;padding:0 20px}header{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #252a31;padding-bottom:16px;margin-bottom:18px}h1{font-size:25px;line-height:1.2;margin:0 0 8px}h2{font-size:16px;line-height:1.4;margin:24px 0 6px;border-bottom:1px solid #c9d0da;padding:8px 0;break-after:avoid}h2 span{float:right;font-size:14px}h3{font-size:13px;margin:0}p{margin:6px 0}small{display:block;color:#525d6c;font-size:10px}.brand{font-size:18px;font-weight:bold;white-space:nowrap}.brand b{color:#b94312}.muted{color:#515b6b;font-size:11px}.notice{border:1px solid #d9a98f;background:#fff5ed;padding:10px 12px;margin:14px 0}.component{padding:12px 0;border-bottom:1px solid #e4e8ed}.keep{break-inside:avoid}.component-title{display:flex;align-items:start;justify-content:space-between;gap:20px;margin-bottom:8px}.component-title>b{white-space:nowrap}.component-context th{background:#fff;padding:4px 0 9px;border:0;text-align:left;width:auto}.component-context small{font-weight:normal;font-size:9px}.component-context .component-title{margin-bottom:2px}em{font-weight:normal;font-style:normal;font-size:10px;color:#91400f}table{border-collapse:collapse;width:100%;table-layout:fixed;font-size:11px}th,td{padding:6px 8px;border-bottom:1px solid #e3e7ed;text-align:left;overflow-wrap:anywhere}th{background:#f2f4f7;font-weight:600}th:last-child,td:last-child{text-align:right;width:23%}thead{display:table-header-group}tr{break-inside:avoid}.working{font-size:11px;color:#4f5a69}.totals{max-width:340px;margin:24px 0 20px auto;break-inside:avoid}.totals p{display:flex;justify-content:space-between}.totals p:last-child{border-top:1px solid #b5bec9;font-size:16px;font-weight:bold;padding-top:10px}.notes{border-top:1px solid #d4dae3;padding-top:12px;font-size:10px;color:#4f5a69;break-inside:avoid}.print-controls{margin:0 0 24px;padding:12px;border:1px solid #d9dfe7;background:#f4f6f9}.print-controls button{padding:10px 14px;cursor:pointer}@media print{body{max-width:none;padding:0;margin:0}.print-controls{display:none}}@media(max-width:600px){header{display:block}.brand{margin-top:12px}body{padding:0 12px}h2 span{float:none;display:block}table{font-size:10px}}
 </style></head><body><div class="print-controls"><button onclick="window.print()">Print / Save PDF</button> Your estimate stays open in the other tab.</div><header><div><h1>${h(job.title||'Measurements to pricing')}</h1><p>${h(TRADE_COPY[job.trade].name)} · ${job.areas.length} areas · ${r.entryCount} measurements · ${h(job.currency)}</p><small>Cost estimate, before tax and margin. Not a customer quotation.</small></div><div class="brand">QuoteCore<b>+</b></div></header>${r.hasExamples?'<div class="notice"><strong>Example pricing  -  not market rates.</strong> Fictitious rates are included. Review and replace them before quoting a customer.</div>':''}${groups}<div class="totals"><p><span>Materials</span><span>${h(money(r.material,job.currency))}</span></p><p><span>Labour</span><span>${h(money(r.labour,job.currency))}</span></p><p><span>Estimated cost</span><span>${h(money(r.total,job.currency))} ${h(job.currency)}</span></p></div><div class="notes"><p>Actual measurements are not pitched again. Roof-plan measurements use the applicable component rule and source-area pitch. Waste is included once. Packs are rounded per component in each area; labour uses measured quantity including waste, not spare pack capacity.</p><p>Saved area sizes are references, not billable items. Openings are not automatically deducted. Quantity pricing does not optimise carpet rolls, cutting layouts, sheet lengths or offcut reuse. Review measurements, allowances and prices for your job.</p>${r.unused?`<p>${r.unused} unmeasured components were not included.</p>`:''}<p>Created with QuoteCore+ free measurements to pricing.</p></div></body></html>`;
}
export function printReport(job:Job){const html=reportHtml(job);const popup=window.open('','_blank');if(!popup)return false;popup.opener=null;popup.document.open();popup.document.write(html);popup.document.close();popup.focus();setTimeout(()=>{if(!popup.closed)popup.print();},150);return true;}
export function downloadCsv(job:Job){const url=URL.createObjectURL(new Blob([resultCsv(job)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`QuoteCore-${job.trade}-estimate.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
