'use client';
import {type Job,type Trade,type Units,type Currency,type Spec,CONFIGS,TRADE_COPY,componentLimit,specUnit,money,TAKEOFF_CURRENCIES} from './measurement-model';
import {Button,ActionLink,Icon,SelectField,Badge,Notice,darkClass} from './MeasurementUI';
import m from './MeasurementPricing.module.css';
export function TradeEntry({onChoose,resume,onResume,onDiscard}:{onChoose:(t:Trade)=>void;resume:Job|null;onResume:()=>void;onDiscard:()=>void}){
 return <><section className={`${m.welcome} ${darkClass}`}><p className={m.eyebrow}>FREE MEASUREMENTS TO PRICING</p><h1>Already measured?<br/>Let’s price the job.</h1><p>Choose your trade. Add your measurements and let Smart Components work out the materials, labour and costs.</p><div className={m.welcomeMeta}><span><Icon name="check"/> No plan needed</span><span><Icon name="check"/> No signup to start</span><span><Icon name="check"/> Your rates or our examples</span></div></section>
 {resume&&<div className={m.resume}><div><strong>Your estimate is still in this tab.</strong><p>{TRADE_COPY[resume.trade].name} · {resume.areas.length} areas · {resume.title||'Untitled estimate'}</p></div><div className={m.actions}><Button onClick={onDiscard}>Discard</Button><Button primary onClick={onResume}>Continue estimate <Icon name="arrow"/></Button></div></div>}
 <div className={m.tradeGrid}>{(['roofing','cladding','flooring'] as const).map(trade=><button type="button" className={m.tradeCard} key={trade} onClick={()=>onChoose(trade)}><Icon name={trade==='roofing'?'roof':trade==='cladding'?'wall':'floor'}/><h2>{TRADE_COPY[trade].name}</h2><p>{TRADE_COPY[trade].description}</p><span>Start {trade} <Icon name="arrow"/></span></button>)}</div><div className={m.entryFoot}><p>Have a plan but need to measure it first?</p><ActionLink href="/free-digital-takeoff">Open digital takeoff <Icon name="arrow"/></ActionLink></div></>;
}
export function Setup({job,onChangeUnits,onChangeCurrency,onChoice,onEdit,onAdd,onDelete,onImport,onContinue,onExample,onTrade}:{job:Job;onChangeUnits:(u:Units)=>void;onChangeCurrency:(c:Currency)=>void;onChoice:(v:'examples'|'custom')=>void;onEdit:(c:Spec)=>void;onAdd:()=>void;onDelete:(c:Spec)=>void;onImport:()=>void;onContinue:()=>void;onExample:()=>void;onTrade:()=>void}){
 const config=CONFIGS[job.trade],copy=TRADE_COPY[job.trade],max=componentLimit(config),custom=job.choice==='custom';
 return <div className={m.setupGrid}><aside className={`${m.setupGuide} ${darkClass}`}><Badge>{copy.name}</Badge><h2>A little setup.<br/>A lot less retyping.</h2><p>A Smart Component pairs a measurement with your material rate, labour and allowances.</p><div className={m.equation}><span>Measurement</span><Icon name="plus"/><span>Component rules</span><span className={m.equals}>=</span><strong>Your price</strong></div><p>Use the same component in several {copy.plural}. Set the rates once; enter only the measurements that change.</p><Button onClick={onTrade}>Change trade</Button><div className={m.guideHelp}><Icon name="info"/><p>Example pricing is for practice. Review and replace it before quoting a real job.</p></div></aside>
 <div className={m.setupMain}><section className={m.panel}><div className={m.sectionHeading}><div><p className={m.kicker}>01 / YOUR PREFERENCES</p><h2>How do you measure?</h2></div></div><fieldset className={m.unitChoices}><legend className={m.srOnly}>Measurement units</legend>{config.unitOptions.map(unit=><label key={unit.value} data-selected={job.units===unit.value}><input type="radio" name="units" checked={job.units===unit.value} onChange={()=>onChangeUnits(unit.value)}/><strong>{unit.label}</strong><small>{unit.description}</small></label>)}</fieldset><div className={m.currencyRow}><SelectField label="Currency" value={job.currency} onChange={c=>onChangeCurrency(c as Currency)}>{TAKEOFF_CURRENCIES.map(c=><option key={c}>{c}</option>)}</SelectField><p>Changing units converts measurements and rates. Changing currency changes the label only.</p></div></section>
 <section className={m.panel}><div className={m.sectionHeading}><div><p className={m.kicker}>02 / YOUR SMART COMPONENTS</p><h2>Use our examples. Or make them yours.</h2></div></div><fieldset className={m.startChoices}><legend className={m.srOnly}>Starting components</legend><label data-selected={!custom}><input type="radio" name="component-choice" checked={!custom} onChange={()=>onChoice('examples')}/><div><strong>Use example components</strong><p>Explore with fictitious prices. No setup required.</p></div></label><label data-selected={custom}><input type="radio" name="component-choice" checked={custom} onChange={()=>onChoice('custom')}/><div><strong>Customise the examples</strong><p>Rename, edit rates or add your own components.</p></div></label></fieldset>
 <p className={m.libraryIntro}>{job.components.length} components ready to use. You’ll choose which ones belong in each {copy.noun}.</p>
 <div className={m.library}>{job.components.map(c=><div className={m.libraryRow} key={c.id}><div className={m.componentGlyph}><Icon name={c.measurementType==='area'?'layers':c.measurementType==='lineal'?'ruler':'plus'}/></div><div className={m.libraryName}><strong>{c.name}</strong><span>{c.pricingStrategy==='per_unit'?`${money(c.materialRate,job.currency)} material`: `${money(c.packPrice??0,job.currency)} / pack`} + {money(c.labourRate,job.currency)} labour / {specUnit(c.measurementType,job.units)}</span></div><Badge example={c.pricingOrigin!=='user'}>{c.pricingOrigin!=='user'?'Example':'Your rates'}</Badge>{custom&&<div className={m.compActions}><Button quiet onClick={()=>onEdit(c)} aria-label={`Edit ${c.name}`}><Icon name="edit"/></Button><Button quiet onClick={()=>onDelete(c)} aria-label={`Remove ${c.name} from library`}><Icon name="trash"/></Button></div>}</div>)}</div>
 {custom&&<div className={m.actions}><Button onClick={onAdd} disabled={job.components.length>=max}><Icon name="plus"/> Add component</Button><Button onClick={onImport} disabled={job.components.length>=max}><Icon name="upload"/> Import CSV</Button></div>}
 {custom&&job.components.length>=max&&<p className={m.help}>Library limit: {max}. Remove an unused example to add another component.</p>}
 <p className={m.help}>You can return and edit this library at any time. It is kept in this browser tab, not saved to an account.</p>
 {job.components.some(c=>c.pricingOrigin!=='user')&&<Notice>Example pricing  -  replace it with your own rates before sending a customer quote.</Notice>}
 </section><div className={m.setupFooter}><Button onClick={onExample}>Try a filled example</Button><Button primary disabled={!job.components.length} onClick={onContinue}>Enter measurements <Icon name="arrow"/></Button></div></div></div>;
}
