'use client';
import {useState} from 'react';
import {readCsv,guessCsv,importCsvRow,type CsvData,type CsvMapping} from './measurement-csv';
import {type Job,type Spec,componentLimit,CONFIGS,specUnit} from './measurement-model';
import {Button,Dialog,SelectField,Notice,Icon} from './MeasurementUI';
import m from './MeasurementPricing.module.css';
export function MeasurementCsvImport({job,onSave,onClose}:{job:Job;onSave:(specs:Spec[])=>void;onClose:()=>void}){
 const [data,setData]=useState<CsvData|null>(null),[mapping,setMapping]=useState<CsvMapping>({name:-1,material:-1,labour:-1,sku:-1}),[selected,setSelected]=useState<number[]>([]),[types,setTypes]=useState<Record<number,Spec['measurementType']>>({}),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);
 const capacity=componentLimit(CONFIGS[job.trade])-job.components.length;
 function save(){try{if(!data||!selected.length)throw Error('Choose at least one row.');if(mapping.name<0)throw Error('Map the component name column.');if(selected.length>capacity)throw Error(`There is space for ${capacity} components. Remove unused examples first.`);if(!confirmed)throw Error('Confirm the units and rates before importing.');onSave(selected.map(i=>importCsvRow(data.rows[i],mapping,types[i]||'area')));}catch(e){setError((e as Error).message);}}
 return <Dialog title="Import components from CSV" description="Map the columns, choose rows and check units. This adds to your library without replacing measurements." onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button primary onClick={save} disabled={!data||!selected.length||busy}>Import {selected.length||''} components <Icon name="arrow"/></Button></>}><div className={m.editor}>
  <p className={m.help}>{capacity} spaces available in this {componentLimit(CONFIGS[job.trade])}-component library. Amounts are interpreted in {job.currency}; no currency conversion.</p>
  <label className={m.upload}>Choose a CSV price list<input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{if(file.size>1_000_000)throw Error('Choose a CSV smaller than 1 MB.');const csv=readCsv(await file.text());setData(csv);setMapping(guessCsv(csv.headers));setSelected([]);setError('');setConfirmed(false);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}/></label>
  {data&&<><div className={m.pair}>{([['name','Name *'],['material','Material rate'],['labour','Labour rate'],['sku','Product code']] as const).map(([k,label])=><SelectField key={k} label={label} value={String(mapping[k])} onChange={v=>setMapping(x=>({...x,[k]:Number(v)}))}><option value="-1">Not mapped</option>{data.headers.map((h,i)=><option key={i} value={i}>{h}</option>)}</SelectField>)}</div>
   <div className={m.csvRows}>{data.rows.map((row,i)=><div key={i} className={m.csvRow}><label className={m.check}><input type="checkbox" checked={selected.includes(i)} disabled={!selected.includes(i)&&selected.length>=capacity} onChange={e=>setSelected(x=>e.target.checked?[...x,i]:x.filter(n=>n!==i))}/><span>{row[mapping.name]||`Row ${i+2}`}<small>Material: {row[mapping.material]||'0'} · Labour: {row[mapping.labour]||'0'}</small></span></label><SelectField label={`Row ${i+2} unit`} value={types[i]||'area'} onChange={v=>setTypes(t=>({...t,[i]:v as Spec['measurementType']}))}>{(['area','lineal','quantity'] as const).map(t=><option value={t} key={t}>{specUnit(t,job.units)}</option>)}</SelectField></div>)}</div>
   <label className={m.check}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have checked that prices match the selected measurement units.</label><p className={m.help}>Imported rows start with no waste, pack or pitch rules. Add those in Edit component. Prices must use a decimal point; quoted thousands separators are accepted.</p>
  </>}{error&&<Notice error>{error}</Notice>}
 </div></Dialog>;
}
