'use client';
import {useState,useRef,useEffect} from 'react';
import {type Job,type JobResult,TRADE_COPY,referenceValue,specUnit,fmt,money,transferToQuote} from './measurement-model';
import {printReport,downloadCsv,resultText} from './measurement-export';
import {Button,Icon,ActionLink,Dialog,Notice,TextField,Badge,darkClass} from './MeasurementUI';
import m from './MeasurementPricing.module.css';
export function MeasurementReport({job,result:r,onBack,onChange,onNotify,onTrack}:{job:Job;result:JobResult;onBack:()=>void;onChange:(j:Job)=>void;onNotify:(s:string)=>void;onTrack:(action:string)=>void}){
 const [transfer,setTransfer]=useState(false),[copied,setCopied]=useState(false),heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus({preventScroll:true});},[]);
 return <><div className={m.reportHeading}><div><p className={m.kicker}>MEASUREMENTS → MATERIALS → PRICING</p><h1 ref={heading} tabIndex={-1}>Your estimate, all together.</h1><p>Check your measurements and rates, then turn them into a free quote.</p></div><Button onClick={onBack}><Icon name="back"/> Back to measurements</Button></div>
 <div className={m.reportGrid}><div><div className={m.stats}><div className={m.reportCost}><span>Estimated cost · {job.currency}</span><strong>{money(r.total,job.currency)}</strong><small>Before tax &amp; margin</small></div><div><span>{TRADE_COPY[job.trade].name} areas</span><strong>{job.areas.length}</strong></div><div><span>Measurements</span><strong>{r.entryCount}</strong></div><div><span>Priced components</span><strong>{r.rows.filter(x=>!x.unused).length}</strong></div></div>
 {r.hasExamples&&<Notice><strong>Example pricing is included.</strong> These are fictitious rates, not a finished customer price. Replace them in your library, or transfer quantities without prices.</Notice>}
 <article className={m.paper} aria-label="Estimate breakdown"><header className={m.paperHeader}><div><TextField label="Estimate name (optional)" value={job.title} maxLength={160} placeholder="e.g. Smith residence  -  flooring" onChange={title=>onChange({...job,title})}/><p>{job.currency} · Before tax and margin</p></div><div className={m.paperBrand}>QuoteCore<span>+</span></div></header>
 {r.areas.map(({area,rows,total})=><section className={m.reportArea} key={area.id}><div className={m.reportAreaHeading}><div><h2>{area.name}</h2><small>{referenceValue(area,job.units)!==null?`${fmt(referenceValue(area,job.units)!)} ${specUnit('area',job.units)} saved reference · not a separate charge`:`${rows.filter(x=>!x.unused).length} measured components`}</small></div><strong>{money(total,job.currency)}</strong></div>
  {rows.filter(x=>!x.unused).map(row=><div className={m.reportComponent} key={row.assignmentId}><div className={m.reportCompHead}><div><h3>{row.component.name}</h3>{row.example&&<Badge example>Example rates</Badge>}</div><strong>{money(row.total,job.currency)}</strong></div><dl className={m.reportValues}><div><dt>Measured</dt><dd>{fmt(row.adjusted)} {row.unit}</dd></div><div><dt>With waste</dt><dd>{fmt(row.quantity)} {row.unit}</dd></div><div><dt>Material</dt><dd>{money(row.material,job.currency)}</dd></div><div><dt>Labour</dt><dd>{money(row.labour,job.currency)}</dd></div></dl>
   <details className={m.reportWorking}><summary>Show {row.entries.filter(e=>!e.blank).length} measurements &amp; working{row.packs?` · ${row.packs} packs`:''}</summary><div>{row.entries.filter(e=>!e.blank).map(e=><div className={m.workingEntry} key={e.id}><span>{e.label}{e.source&&<small>Linked: {e.source}</small>}</span><span>{e.working}</span><strong>{fmt(e.adjusted,4)} {row.unit}</strong></div>)}</div><p>{fmt(row.adjusted,4)} measured + {fmt(row.waste,4)} waste = {fmt(row.quantity,4)} {row.unit}.{row.packs?` ${row.packs} packs × ${money(row.component.packPrice??0,job.currency)}. Packs rounded for this area.`:''}</p></details>
  </div>)}
  {!rows.some(x=>!x.unused)&&<p className={m.help}>No measurements in this area yet. Nothing has been charged.</p>}
 </section>)}
 <div className={m.reportTotals}><p><span>Materials</span><span>{money(r.material,job.currency)}</span></p><p><span>Labour</span><span>{money(r.labour,job.currency)}</span></p><p><span>Estimated cost</span><span>{money(r.total,job.currency)} <small>{job.currency}</small></span></p></div>
 <div className={m.paperNotes}><p>Quantities include the selected pitch and waste rules. Whole packs round separately in each area. Saved reference sizes do not create extra charges.</p><p>No automatic opening deductions, carpet-roll layout, cutting optimisation or offcut sharing. Review the quantities for your actual installation.</p>{r.unused>0&&<p>{r.unused} components have no measurements and are not included.</p>}</div>
 </article><div className={m.exportActions}><Button onClick={()=>{try{if(!printReport(job))onNotify('Allow pop-ups to open the print report. Your estimate is unchanged.');else onTrack('print');}catch(e){onNotify((e as Error).message);}}}><Icon name="download"/> Print / Save PDF</Button><Button onClick={()=>{downloadCsv(job);onTrack('export-csv');}}><Icon name="file"/> Export CSV</Button><Button onClick={async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(resultText(job));setCopied(true);onTrack('copy');}catch{onNotify('Your browser blocked clipboard access. Use Export CSV or Print instead.');}}}>{copied?'Copied':'Copy summary'} <Icon name={copied?'check':'layers'}/></Button></div></div>
 <aside className={m.reportSidebar}><section className={`${m.nextCard} ${darkClass}`}><p className={m.eyebrow}>YOUR NEXT STEP</p><h2>Make it a quote.</h2><p>Move these measured quantities into the Free Quote Generator. Add your customer and review selling prices before you send anything.</p><Button primary onClick={()=>setTransfer(true)}>Create a free quote <Icon name="arrow"/></Button><small>No retyping. This estimate stays open.</small></section><section className={m.upsell}><Icon name="spark"/><h3>Keep the part you’ve already set up.</h3><p>In the paid QuoteCore+ app, your component library and pricing are ready for the next job.</p><ul><li><Icon name="check"/> Save and reuse components and rates</li><li><Icon name="check"/> Keep measurements with your jobs</li><li><Icon name="check"/> Connect quotes, orders and invoices</li></ul><ActionLink href="/takeoff-demo">Try the app demo <Icon name="arrow"/></ActionLink><div className={m.paidLinks}><a href="/">Explore QuoteCore+</a><a href="/done-for-you-setup">Done For You Setup</a></div></section></aside></div>
 <section className={m.mobileUpsell}><Icon name="spark"/><div><h3>Save the setup for your next job.</h3><p>The paid app keeps your components, rates and measurements together, with connected quotes, orders and invoices.</p><ActionLink href="/takeoff-demo">Try the app demo <Icon name="arrow"/></ActionLink><a href="/done-for-you-setup">Explore Done For You Setup</a></div></section>
 {transfer&&<QuoteTransfer job={job} onClose={()=>setTransfer(false)} onTrack={onTrack}/>}
 </>;
}
function QuoteTransfer({job,onClose,onTrack}:{job:Job;onClose:()=>void;onTrack:(a:string)=>void}){
 const r=(()=>{try{return transferToQuote(job,false);}catch{return null;}})();
 const hasExamples=job.areas.some(a=>a.components.some(ac=>job.components.find(c=>c.id===ac.componentId)?.pricingOrigin!=='user'&&ac.entries.some(e=>e.a||e.referenceId)));
 const [prices,setPrices]=useState(!hasExamples),[ack,setAck]=useState(false);let url='',error='';
 try{url=transferToQuote(job,prices,ack).url;}catch(e){error=(e as Error).message;}
 return <Dialog title="Create a free quote" description="Your areas stay separate as quote lines. Nothing is sent to a customer." onClose={onClose} footer={<><Button onClick={onClose}>Back</Button>{url?<ActionLink primary href={url} target="_blank" rel="noopener noreferrer" onClick={()=>onTrack('convert-to-quote')}>Open Free Quote Generator <Icon name="arrow"/></ActionLink>:<Button primary disabled>Open Free Quote Generator <Icon name="arrow"/></Button>}</>}><div className={m.editor}><fieldset className={m.transferChoices}><legend>What would you like to bring across?</legend><label data-selected={!prices}><input type="radio" name="quote-pricing" checked={!prices} onChange={()=>setPrices(false)}/><span><strong>Quantities only</strong><small>Enter your selling prices in the quote.{hasExamples?' Recommended for example components.':''}</small></span></label><label data-selected={prices}><input type="radio" name="quote-pricing" checked={prices} onChange={()=>setPrices(true)}/><span><strong>Quantities and calculated costs</strong><small>Includes material, labour and pack rounding. Review your margin and tax in the quote.</small></span></label></fieldset>
 {prices&&hasExamples&&<Notice><label className={m.check}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I understand example prices are fictitious and will replace them before sending a quote.</label><p>Example-priced lines will be labelled EXAMPLE PRICE  -  REPLACE.</p></Notice>}
 <div className={m.transferPreview}>{r?.lines.slice(0,5).map((line,i)=><div key={i}><span>{line.description}</span><strong>{fmt(line.qty)} {line.unit}</strong></div>)}{r&&r.lines.length>5&&<small>Plus {r.lines.length-5} more lines. All areas are included.</small>}</div><p className={m.help}>Quantities already include pitch and waste. These rules are not applied twice. Tax and margin are not added by this tool.</p>{error&&(!hasExamples||ack||!prices)&&<Notice error>{error}</Notice>}
 </div></Dialog>;
}
