'use client';
import {useState,useId,useRef,useEffect} from 'react';
import {type Job,type Area,type Assignment,type Measurement,type Spec,type Basis,type JobResult,type ComponentResult,TRADE_COPY,CONFIGS,newArea,newMeasurement,addAssignment,duplicateArea,referenceValue,referenceUsers,calculateEntry,id,fmt,money,specUnit,lengthUnit} from './measurement-model';
import {Button,Icon,Dialog,Field,TextField,SelectField,Badge,Notice,darkClass,ActionLink} from './MeasurementUI';
import m from './MeasurementPricing.module.css';
export function MeasurementWorkspace({job,result,onChange,onEditComponent,onLibrary,onReview,onNotify}:{job:Job;result:JobResult;onChange:(j:Job,undoLabel?:string)=>void;onEditComponent:(c:Spec)=>void;onLibrary:()=>void;onReview:()=>void;onNotify:(s:string)=>void}){
 const area=job.areas.find(a=>a.id===job.selectedAreaId)??job.areas[0],copy=TRADE_COPY[job.trade],heading=useRef<HTMLHeadingElement>(null),firstSelection=useRef(true),selectId=useId();
 const [areaForm,setAreaForm]=useState<'new'|'rename'|'duplicate'|null>(null),[manage,setManage]=useState(false),[componentPicker,setComponentPicker]=useState(false);
 useEffect(()=>{if(firstSelection.current){firstSelection.current=false;return;}heading.current?.focus({preventScroll:true});},[area.id]);
 function patchArea(next:Area,undo?:string){onChange({...job,areas:job.areas.map(a=>a.id===next.id?next:a)},undo);}
 function patchAssignment(ac:Assignment,undo?:string){patchArea({...area,components:area.components.map(x=>x.id===ac.id?ac:x)},undo);}
 function removeArea(target:Area){
  if(job.areas.length<=1){onNotify('Keep at least one area. You can rename this one or remove its components.');return;}
  const links=referenceUsers(job,target.id,true);if(links.length){onNotify(`${target.name} is used by ${links.length} linked measurements in other areas. Switch those entries to their own measurements before deleting it.`);return;}
  if(!window.confirm(`Remove “${target.name}” and its measurements? You can undo this until the next edit.`))return;
  const areas=job.areas.filter(a=>a.id!==target.id);onChange({...job,areas,selectedAreaId:job.selectedAreaId===target.id?areas[0].id:job.selectedAreaId},`Removed ${target.name}`);
 }
 const areaTotal=result.areas.find(a=>a.area.id===area.id)?.total??0;
 return <>
 <div className={m.areaSwitchRow}><div className={m.areaSelector}><label htmlFor={selectId}>CURRENT {copy.noun.toUpperCase()} <span>{job.areas.findIndex(a=>a.id===area.id)+1} OF {job.areas.length}</span></label><select id={selectId} value={area.id} onChange={e=>{onChange({...job,selectedAreaId:e.target.value});onNotify(`Now editing ${job.areas.find(a=>a.id===e.target.value)?.name}. Your other areas are still in the selector.`);}} aria-describedby={`${selectId}-help`}>{job.areas.map(a=><option key={a.id} value={a.id}>{a.name}{referenceValue(a,job.units)!==null?` · ${fmt(referenceValue(a,job.units)!)} ${specUnit('area',job.units)}`:''}</option>)}</select><div className={m.selectorMeta}><span id={`${selectId}-help`}>{job.areas.length===1?'Start here. Add another area whenever you need one.':`${job.areas.length} areas in this job. Switch here to see every area you’ve added.`}</span><button type="button" onClick={()=>setManage(true)}>View all {job.areas.length}</button></div></div>
 <Button className={`${m.addArea} ${darkClass}`} onClick={()=>setAreaForm('new')} disabled={job.areas.length>=100}><span className={m.addAreaIcon}><Icon name="plus"/></span><span><strong>Add New Area</strong><small>{job.trade==='flooring'?'Another room or floor zone':job.trade==='cladding'?'Another elevation or cladding type':'Another roof, garage or extension'}</small></span></Button></div>
 <div className={m.workspaceGrid}><div className={m.measureColumn}>
  <section className={m.areaPanel}><div className={m.areaTitle}><div><p className={m.kicker}>YOU’RE WORKING ON</p><h2 ref={heading} tabIndex={-1}>{area.name}</h2></div><div className={m.actions}><Button quiet onClick={()=>setAreaForm('rename')}><Icon name="edit"/> Rename</Button><Button quiet onClick={()=>setManage(true)} aria-label="Manage areas"><Icon name="layers"/></Button></div></div>
   <ReferenceEditor job={job} area={area} onChange={patchArea} onNotify={onNotify}/>
  </section>
  <div className={m.componentsTitle}><div><h2>Components in this {copy.noun}</h2><p>{area.components.length? 'Add a measurement to each component. Use another row for another length or section.':'Choose the materials or work you want to price here.'}</p></div>{area.components.length>0&&<Button onClick={()=>setComponentPicker(true)} className={m.addComponent}><Icon name="plus"/> Add components</Button>}</div>
  {!area.components.length?<section className={m.emptyComponents}><div className={m.emptyIcon}><Icon name="layers"/></div><h3>What goes into {area.name}?</h3><p>{job.trade==='flooring'?'For example: carpet, underlay and skirting. Each gets its own measurements.':job.trade==='cladding'?'For example: cladding, building wrap and trims. Choose only what belongs on this elevation.':'For example: roof covering, ridge flashing and spouting. Each has its own measurements.'}</p><Button primary onClick={()=>setComponentPicker(true)}><Icon name="plus"/> Add components to this {copy.noun}</Button><small>Your {job.components.length} prepared components are ready to choose from.</small></section>:
    area.components.map(ac=>{const c=job.components.find(c=>c.id===ac.componentId);if(!c)return null;const r=result.rows.find(r=>r.assignmentId===ac.id)!;return <ComponentCard key={ac.id} job={job} area={area} assignment={ac} component={c} result={r} onChange={patchAssignment} onEdit={()=>onEditComponent(c)} onRemove={()=>patchArea({...area,components:area.components.filter(x=>x.id!==ac.id)},`Removed ${c.name} from ${area.name}`)}/>;})}
  {area.components.length>0&&<div className={m.addBelow}><Button onClick={()=>setComponentPicker(true)}><Icon name="plus"/> Add another component</Button><button type="button" onClick={onLibrary}>Edit your component library</button></div>}
 </div>
 <aside className={m.summaryColumn}><section className={`${m.runningSummary} ${darkClass}`}><p className={m.eyebrow}>YOUR JOB SO FAR</p><h2>{result.issues.length?'Check your inputs':result.entryCount?'It’s adding up.':'Ready when you are.'}</h2><p className={m.summaryCaption}>{result.entryCount?`${result.entryCount} measurements across ${job.areas.length} ${copy.plural}`:'Enter your first measurement to see the cost.'}</p><div className={m.bigTotal}>{money(result.total,job.currency)}</div><p className={m.totalContext}>{job.currency} · {result.issues.length?'Incomplete subtotal':'Estimated cost'} · before tax &amp; margin</p><dl><div><dt>Materials</dt><dd>{money(result.material,job.currency)}</dd></div><div><dt>Labour</dt><dd>{money(result.labour,job.currency)}</dd></div></dl><div className={m.currentAreaTotal}><span>This {copy.noun}<strong>{area.name}</strong></span><b>{money(areaTotal,job.currency)}</b></div>
  {result.hasExamples&&<p className={m.exampleNote}><Icon name="info"/> Includes fictitious example pricing.</p>}
  <Button primary onClick={onReview} disabled={!result.valid}>Review results <Icon name="arrow"/></Button>
  {!result.valid&&<small>{result.issues.length?'Correct the highlighted measurements to continue.':'Add a valid measurement to review your estimate.'}</small>}
 </section><section className={m.helpCard}><Icon name="spark"/><h3>One size. Several uses.</h3><p>Give this {copy.noun} an optional size. Then choose <strong>Use saved area</strong> in any area-based component. You won’t need to type it again.</p><button type="button" onClick={onLibrary}>Your component library <Icon name="arrow"/></button></section>
 {result.issues.length>0&&<Notice error>{result.issues.length} {result.issues.length===1?'input needs':'inputs need'} attention. Affected components are excluded from the working subtotal until corrected.</Notice>}
 </aside></div>
 <div className={m.mobileSummary}><div><span>{result.issues.length?'Incomplete subtotal':'Job estimate'} · {job.currency}</span><strong>{money(result.total,job.currency)}</strong></div><Button primary disabled={!result.valid} onClick={onReview}>Review results <Icon name="arrow"/></Button></div>
 {areaForm&&<AreaForm key={`${areaForm}-${area.id}`} job={job} area={area} mode={areaForm} onClose={()=>setAreaForm(null)} onSave={(name,copyComponents)=>{
   if(areaForm==='rename'){patchArea({...area,name});}
   else{let next=areaForm==='duplicate'?duplicateArea(area,name):newArea(name,area.basis);if(areaForm==='new'&&copyComponents)next={...next,components:area.components.map(ac=>({id:id('group'),componentId:ac.componentId,entries:[newMeasurement(job.components.find(c=>c.id===ac.componentId)!.measurementType,area.basis)]}))};onChange({...job,areas:[...job.areas,next],selectedAreaId:next.id});onNotify(`Added ${name}. ${job.areas.length+1} areas are now in the selector above.`);}
   setAreaForm(null);
 }}/>} 
 {manage&&<Dialog title={`Your ${job.areas.length} areas`} description="Every area stays in this job. Select one to continue editing, or add a separate area for a different finish." onClose={()=>setManage(false)} footer={<><Button onClick={()=>setManage(false)}>Close</Button><Button primary onClick={()=>{setManage(false);setAreaForm('new');}}><Icon name="plus"/> Add New Area</Button></>}><div className={m.areaList}>{job.areas.map(a=><div key={a.id} data-selected={a.id===area.id}><button type="button" onClick={()=>{onChange({...job,selectedAreaId:a.id});setManage(false);}}><strong>{a.name} {a.id===area.id&&<Badge>Current</Badge>}</strong><small>{a.components.length} components{referenceValue(a,job.units)!==null?` · ${fmt(referenceValue(a,job.units)!)} ${specUnit('area',job.units)} saved size`:''}</small></button><div className={m.compActions}><Button quiet onClick={()=>{onChange({...job,selectedAreaId:a.id});setManage(false);setAreaForm('duplicate');}} aria-label={`Duplicate ${a.name}`}><Icon name="layers"/></Button><Button quiet onClick={()=>removeArea(a)} disabled={job.areas.length===1} aria-label={`Delete ${a.name}`}><Icon name="trash"/></Button></div></div>)}</div></Dialog>}
 {componentPicker&&<ComponentPicker job={job} area={area} onClose={()=>setComponentPicker(false)} onLibrary={()=>{setComponentPicker(false);onLibrary();}} onAdd={(ids,useRef)=>{let next=area;for(const cId of ids){const c=job.components.find(c=>c.id===cId)!;next=addAssignment(next,c,useRef);}patchArea(next);setComponentPicker(false);onNotify(`Added ${ids.length} components to ${area.name}.`);const first=next.components.find(ac=>ids.includes(ac.componentId));requestAnimationFrame(()=>{document.getElementById(first?.id??'')?.querySelector<HTMLElement>('input,select,button')?.focus();});}}/>}
 </>;
}
function AreaForm({job,area,mode,onSave,onClose}:{job:Job;area:Area;mode:'new'|'rename'|'duplicate';onSave:(name:string,copy:boolean)=>void;onClose:()=>void}){
 const copy=TRADE_COPY[job.trade];const [name,setName]=useState(mode==='rename'?area.name:mode==='duplicate'?`${area.name}  -  copy`:''),[reuse,setReuse]=useState(false),[error,setError]=useState('');
 function save(){const n=name.trim();if(!n){setError('Give this area a name so you can find it again.');return;}if(job.areas.some(a=>(mode!=='rename'||a.id!==area.id)&&a.name.toLocaleLowerCase()===n.toLocaleLowerCase())){setError('That name is already in this job. Add a room number, elevation or finish to distinguish it.');return;}onSave(n,reuse);}
 return <Dialog title={mode==='rename'?'Rename area':mode==='duplicate'?'Duplicate area':'Add New Area'} description={mode==='duplicate'?'This copies components and measurements. Check the new sizes before using the total.':`${copy.hint} You don’t have to enter a size.`} onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button primary onClick={save}>{mode==='rename'?'Save name':mode==='duplicate'?'Duplicate area':'Create area'} <Icon name="arrow"/></Button></>}><div className={m.editor} onKeyDown={e=>{if(e.key==='Enter'&&(e.target as HTMLElement).tagName==='INPUT'){e.preventDefault();save();}}}><TextField label={job.trade==='flooring'?'Room / area name':'Area name'} value={name} onChange={setName} placeholder={copy.placeholder} autoFocus/>{mode==='new'&&area.components.length>0&&<label className={m.check}><input type="checkbox" checked={reuse} onChange={e=>setReuse(e.target.checked)}/>Use the same components as {area.name}, with blank measurements.</label>}{error&&<Notice error>{error}</Notice>}</div></Dialog>;
}
function ReferenceEditor({job,area,onChange,onNotify}:{job:Job;area:Area;onChange:(a:Area)=>void;onNotify:(s:string)=>void}){
 const copy=TRADE_COPY[job.trade],r=area.reference??{mode:job.trade==='flooring'?'dimensions' as const:'total' as const,a:'',b:'',basis:area.basis},value=referenceValue(area,job.units),unit=specUnit('area',job.units),len=lengthUnit(job.units);
 function patch(p:Partial<typeof r>){onChange({...area,reference:{...r,...p}});}
 const refCount=referenceUsers(job,area.id).length;
 return <div className={m.referenceBox}><details key={area.id} open={area.reference||job.trade==='flooring'?true:undefined}><summary><Icon name="layers"/><span>Save a size for this {copy.noun}<small>Optional · reuse it in area-based components</small></span>{value!==null?<Badge>{fmt(value)} {unit}</Badge>:<span className={m.optional}>Add a size</span>}</summary><div className={m.referenceBody}>
  <div className={m.segmented} role="group" aria-label="Saved area entry method"><button type="button" aria-pressed={r.mode==='total'} onClick={()=>patch({mode:'total',a:value!==null?String(value):'',b:''})}>Total area</button><button type="button" aria-pressed={r.mode==='dimensions'} onClick={()=>{if(r.mode!=='dimensions')patch({mode:'dimensions',a:'',b:''});}}>Length × {copy.dimension.toLowerCase()}</button></div>
  <div className={m.referenceFields}>{r.mode==='total'?<Field label="Total area" suffix={unit} value={r.a} onChange={a=>patch({a})} placeholder="0.00"/>:<><Field label="Length" suffix={len} value={r.a} onChange={a=>patch({a})} placeholder="0.00"/><Field label={copy.dimension} suffix={len} value={r.b} onChange={b=>patch({b})} placeholder="0.00"/></>}<div className={m.savedSize}><small>Saved size</small><strong>{value!==null?`${fmt(value)} ${unit}`:'Not set'}</strong></div></div>
  {job.units==='squares'&&r.mode==='dimensions'&&<p className={m.help}>Feet × feet ÷ 100 = roofing squares.</p>}
  {job.trade==='roofing'&&<SelectField label="This saved size is measured…" value={r.basis} onChange={basis=>patch({basis:basis as Basis})}><option value="actual">On the roof surface  -  already includes slope</option><option value="plan">On a flat plan  -  apply roof pitch where enabled</option></SelectField>}
  <p className={m.help}>{refCount?`Linked to ${refCount} measurements. Changing this size updates them automatically.`:'A saved size is not charged on its own. Select it in the components that use it.'}</p>
  {area.reference&&<button className={m.textAction} type="button" onClick={()=>{if(refCount){onNotify('This saved size is linked to measurements. Switch those rows to total area or dimensions before removing it.');return;}onChange({...area,reference:null});}}>Remove saved size</button>}
 </div></details>
 {job.trade==='roofing'&&<details className={m.roofSettings} open={area.basis==='plan'||area.reference?.basis==='plan'||undefined}><summary>Roof measurement basis &amp; pitch</summary><div className={m.pair}><SelectField label="Default for new measurements" value={area.basis} onChange={basis=>onChange({...area,basis:basis as Basis})}><option value="actual">Actual / on the roof</option><option value="plan">Flat plan / apply pitch</option></SelectField><Field label="Roof pitch" value={area.pitch} onChange={pitch=>onChange({...area,pitch})} suffix="°" placeholder="e.g. 25"/></div><p className={m.help}>Existing rows keep their own basis. Pitch applies only to flat-plan measurements whose component has a pitch rule.</p></details>}
 </div>;
}
function ComponentPicker({job,area,onClose,onAdd,onLibrary}:{job:Job;area:Area;onClose:()=>void;onAdd:(ids:string[],reference:boolean)=>void;onLibrary:()=>void}){
 const [selected,setSelected]=useState<string[]>([]),[reuse,setReuse]=useState(referenceValue(area,job.units)!==null),[filter,setFilter]=useState('');
 const available=job.components.filter(c=>!area.components.some(ac=>ac.componentId===c.id));
 return <Dialog title={`Add components to ${area.name}`} description="Choose the covering and supporting components you need. You don’t need every example in the library." onClose={onClose} footer={<><Button onClick={onLibrary}>Edit library</Button><Button primary disabled={!selected.length} onClick={()=>onAdd(selected,reuse)}>Add {selected.length||''} {selected.length===1?'component':'components'} <Icon name="arrow"/></Button></>}><div className={m.editor}>
  {available.length>5&&<TextField label="Find a component" value={filter} onChange={setFilter} placeholder="Search by name"/>}
  <div className={m.pickerList}>{available.filter(c=>c.name.toLowerCase().includes(filter.toLowerCase())).map(c=><label key={c.id} data-selected={selected.includes(c.id)}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,c.id]:ids.filter(i=>i!==c.id))}/><span><strong>{c.name}</strong><small>{specUnit(c.measurementType,job.units)} · {c.pricingOrigin==='user'?'Your rates':'Example pricing'}</small></span><Icon name={c.measurementType==='area'?'layers':c.measurementType==='lineal'?'ruler':'plus'}/></label>)}</div>
  {!available.length&&<Notice>All of your library components are already in this area. Edit the library to add something different.</Notice>}
  {referenceValue(area,job.units)!==null&&<label className={m.check}><input type="checkbox" checked={reuse} onChange={e=>setReuse(e.target.checked)}/>Use {area.name} · {fmt(referenceValue(area,job.units)!)} {specUnit('area',job.units)} for selected area-based components.</label>}
  <p className={m.help}>Each component is priced separately. Adding two alternative floor coverings or cladding types will price both; use separate areas for separate finishes.</p>
 </div></Dialog>;
}
function ComponentCard({job,area,assignment,component:c,result:r,onChange,onEdit,onRemove}:{job:Job;area:Area;assignment:Assignment;component:Spec;result:ComponentResult;onChange:(a:Assignment,undo?:string)=>void;onEdit:()=>void;onRemove:()=>void}){
 const unit=specUnit(c.measurementType,job.units);
 function update(e:Measurement){onChange({...assignment,entries:assignment.entries.map(old=>old.id===e.id?e:old)});}
 return <section id={assignment.id} className={m.componentCard} aria-label={`${c.name} measurements`}><header><div className={m.componentGlyph}><Icon name={c.measurementType==='area'?'layers':c.measurementType==='lineal'?'ruler':'plus'}/></div><div className={m.componentHeading}><h3>{c.name}</h3><p>{c.measurementType==='area'?'Area':c.measurementType==='lineal'?'Length':'Count'} · {unit} {r.example&&<Badge example>Example price</Badge>}</p></div><div className={m.compActions}><Button quiet onClick={onEdit} aria-label={`Edit ${c.name} rates`}><Icon name="edit"/></Button><Button quiet onClick={onRemove} aria-label={`Remove ${c.name} from area`}><Icon name="trash"/></Button></div></header>
 <div className={m.entries}>{assignment.entries.map((e,i)=><EntryRow key={e.id} entry={e} index={i} job={job} area={area} component={c} onChange={update} onDuplicate={()=>onChange({...assignment,entries:[...assignment.entries.slice(0,i+1),{...e,id:id('entry')},...assignment.entries.slice(i+1)]})} onRemove={()=>onChange({...assignment,entries:assignment.entries.filter(x=>x.id!==e.id)},`Removed a ${c.name} measurement`)}/>)}</div>
 <div className={m.componentFooter}><Button onClick={()=>onChange({...assignment,entries:[...assignment.entries,newMeasurement(c.measurementType,area.basis)]})} disabled={assignment.entries.length>=500}><Icon name="plus"/> Add measurement</Button><div>{r.issues.length?<strong className={m.invalid}>Check measurements</strong>:<><span>{fmt(r.quantity)} {unit}{r.waste>0?' incl. waste':''}</span><strong>{money(r.total,job.currency)}</strong></>}</div></div>
 <details className={m.componentWorking}><summary>Rates &amp; calculation{r.packs?` · ${r.packs} packs`:''}</summary><div className={m.workingGrid}><span>Measured <b>{fmt(r.adjusted)} {unit}</b></span><span>Waste <b>{fmt(r.waste)} {unit}</b></span><span>Material <b>{money(r.material,job.currency)}</b></span><span>Labour <b>{money(r.labour,job.currency)}</b></span></div><p>{c.pricingStrategy==='per_unit'?`${money(c.materialRate,job.currency)} material / ${unit}`:`${r.packs} packs × ${money(c.packPrice??0,job.currency)} (${c.packSize} ${unit} per pack)`} + {money(c.labourRate,job.currency)} labour / {unit}. Labour uses quantity including waste. {c.pricingStrategy!=='per_unit'?'Packs round separately in each area.':''}</p></details>
 </section>;
}
function EntryRow({entry:e,index,job,area,component:c,onChange,onDuplicate,onRemove}:{entry:Measurement;index:number;job:Job;area:Area;component:Spec;onChange:(e:Measurement)=>void;onDuplicate:()=>void;onRemove:()=>void}){
 const r=calculateEntry(e,c,area,job),unit=specUnit(c.measurementType,job.units),refs=job.areas.filter(a=>referenceValue(a,job.units)!==null),copy=TRADE_COPY[job.trade];
 function patch(p:Partial<Measurement>){onChange({...e,...p});}
 return <div className={`${m.entryRow} ${r.error?m.entryError:''}`}><div className={m.entryTop}><span>MEASUREMENT {index+1}</span><div className={m.compActions}><Button quiet onClick={onDuplicate} aria-label={`Duplicate measurement ${index+1}`}><Icon name="layers"/></Button><Button quiet onClick={onRemove} aria-label={`Remove measurement ${index+1}`}><Icon name="close"/></Button></div></div>
 {c.measurementType==='area'&&<div className={m.segmented} role="group" aria-label={`Measurement ${index+1} method`}><button type="button" aria-pressed={e.mode==='total'} onClick={()=>{if(e.mode!=='total')patch({mode:'total',a:!r.error&&!r.blank?String((e.mode==='reference'?r.adjusted:r.raw)/Number(e.repeat||1)):'',b:'',referenceId:'',basis:e.mode==='reference'?'actual':r.basis,pitchOverride:e.mode==='reference'?'':e.pitchOverride});}}>Total area</button><button type="button" aria-pressed={e.mode==='dimensions'} onClick={()=>{if(e.mode!=='dimensions')patch({mode:'dimensions',a:'',b:'',referenceId:''});}}>Length × {copy.dimension.toLowerCase()}</button><button type="button" aria-pressed={e.mode==='reference'} onClick={()=>patch({mode:'reference',referenceId:referenceValue(area,job.units)!==null?area.id:refs[0]?.id||'',a:'',b:''})}>Use saved area</button></div>}
 <div className={`${m.entryFields} ${e.mode==='dimensions'&&c.measurementType==='area'?m.dimensionFields:''}`}>
  {e.mode==='reference'&&c.measurementType==='area'?<SelectField label="Saved area measurement" value={e.referenceId} onChange={referenceId=>patch({referenceId})} help={refs.length?'Linked size: source-area edits update this row.':'Add an optional saved size above, or use total area / dimensions.'}><option value="">Choose a saved area</option>{refs.map(a=><option key={a.id} value={a.id}>{a.name} · {fmt(referenceValue(a,job.units)!)} {unit}{a.reference?.basis==='plan'?' · flat plan':''}</option>)}</SelectField>:
   e.mode==='dimensions'&&c.measurementType==='area'?<><Field label="Length" suffix={lengthUnit(job.units)} value={e.a} onChange={a=>patch({a})} placeholder="0.00"/><Field label={copy.dimension} suffix={lengthUnit(job.units)} value={e.b} onChange={b=>patch({b})} placeholder="0.00"/></>:
   <Field label={c.measurementType==='quantity'?'Count':c.measurementType==='area'?'Area':'Length'} suffix={unit} value={e.a} onChange={a=>patch({a})} placeholder={c.measurementType==='quantity'?'0':'0.00'} integer={c.measurementType==='quantity'}/>}
  {c.measurementType!=='quantity'&&<Field label="Repeat" value={e.repeat} onChange={repeat=>patch({repeat})} integer/>}
  <div className={m.entryValue}><small>{r.factor!==1?'After pitch':'Measured'}</small><strong>{r.blank?' - ':r.error?'Check input':`${fmt(r.adjusted)} ${unit}`}</strong></div>
 </div>
 {r.error&&<p className={m.invalid} role="alert">{r.error}</p>}
 {!r.error&&e.mode==='dimensions'&&c.measurementType==='area'&&job.units==='squares'&&<p className={m.help}>Feet × feet ÷ 100 gives roofing squares.</p>}
 <details className={m.entryDetails}><summary>{e.label||'Label'}{job.trade==='roofing'&&c.measurementType!=='quantity'&&e.mode!=='reference'?' / measurement basis':''} <span>optional</span></summary><div className={m.editor}><TextField label="Measurement label" value={e.label} onChange={label=>patch({label})} placeholder="e.g. Alcove, north edge, window 1"/>
  {job.trade==='roofing'&&c.measurementType!=='quantity'&&e.mode!=='reference'&&<div className={m.pair}><SelectField label="Measurement basis" value={e.basis} onChange={basis=>patch({basis:basis as Basis})}><option value="actual">Actual / already on slope</option><option value="plan">Flat plan / apply pitch rule</option></SelectField>{e.basis==='plan'&&c.pitchEnabled&&<Field label="Pitch override (optional)" suffix="°" value={e.pitchOverride} onChange={pitchOverride=>patch({pitchOverride})} placeholder={area.pitch||'Uses area pitch'}/>}</div>}
 </div></details>
 </div>;
}
