/** Shared by the visible FAQ and its route-local JSON-LD. */
export const ROOFING_FAQS = [
  {q:'What is the difference between plan area and roof surface area?',a:'Plan area is the flat footprint viewed from above. Roof surface area is measured along the slope. For one pitch, surface area = plan area ÷ cos(pitch). Choose “Already measured” when your value already includes the slope; no second pitch factor is applied.'},
  {q:'Do I enter the full width or half the width?',a:'For Roof area, enter the full plan width and length of the section you want to calculate. For Rafter length, enter the horizontal run from wall to ridge. On a symmetrical gable, that run is half the building width. Include overhangs only where your chosen measurements include them.'},
  {q:'Does the result include waste?',a:'Roof area and rafter / hip lengths do not include waste. Battens include the waste percentage you enter. Material pricing applies your selected waste rule before pricing. Transferring a batten total into pricing switches additional waste off to avoid counting it twice.'},
  {q:'Can I use feet and inches?',a:'Yes. Switching to Imperial converts existing measurements instead of just changing their labels. Lengths use feet, areas use square feet, and batten gauge uses inches. Per-unit material rates also convert. Currency selection changes the currency label only; it is not an exchange-rate conversion.'},
  {q:'How should I handle a roof with different pitches?',a:'Calculate each differently pitched section separately, then add its surface area to your estimate. The hip / valley length mode assumes equal roof pitches at a 90° plan corner. Junction allowances, penetrations and material coverage requirements need to be assessed separately.'},
  {q:'Can I turn these measurements into a quote?',a:'Use “Add to a free quote” to transfer a measurement, or price it first and use “Create a free quote” to transfer material and labour line items. Review tax, margins and your customer details in the Quote Generator. These calculator estimates do not include tax or profit margin.'},
  {q:'Do I need to create an account?',a:'No account is required for calculations, copying or downloading results. Your working inputs are kept in session storage in this browser tab where available. Saving a Smart Component to QuoteCore+ sends the draft to the app and requires the appropriate paid workspace; it is a separate, optional action. The site’s normal authentication and analytics remain in place.'},
];
