/**
 * Static seed data for starter component collections.
 * Sourced from secarter23@gmail.com's "Roofing" and "Generic" libraries.
 *
 * To update: edit the libraries in the secarter23@gmail.com account,
 * then ask Gavin to re-fetch from DB and regenerate this file.
 * Updates only affect NEW signups — existing companies are never touched.
 */

export interface StarterComponent {
  name: string;
  component_type: 'main' | 'extra';
  measurement_type: string;
  default_material_rate: number;
  default_labour_rate: number;
  default_waste_type: 'percent' | 'fixed' | 'fixed_per_segment' | 'none';
  default_waste_percent: number;
  default_waste_fixed: number;
  default_pitch_type: 'none' | 'rafter' | 'valley_hip';
  eligible_for_orders: boolean;
  pricing_strategy: string;
  pack_price: number | null;
  pack_size: number | null;
  pack_coverage_m2: number | null;
  height_value_mm: number | null;
  depth_value_mm: number | null;
  waste_unit: string;
  notes: string | null;
}

export const ROOFING_STARTER_COMPONENTS: StarterComponent[] = [
  {
    name: 'Corrugate .40g',
    component_type: 'main',
    measurement_type: 'area',
    default_material_rate: 30,
    default_labour_rate: 7.5,
    default_waste_type: 'percent',
    default_waste_percent: 3,
    default_waste_fixed: 0,
    default_pitch_type: 'rafter',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: null,
  },
  {
    name: 'Parapet Flashings (Standard)',
    component_type: 'main',
    measurement_type: 'lineal',
    default_material_rate: 13,
    default_labour_rate: 8,
    default_waste_type: 'fixed',
    default_waste_percent: 0,
    default_waste_fixed: 0.3,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: null,
  },
  {
    name: 'Ridge (Soft Edge, Standard)',
    component_type: 'main',
    measurement_type: 'lineal',
    default_material_rate: 15,
    default_labour_rate: 12,
    default_waste_type: 'fixed',
    default_waste_percent: 0,
    default_waste_fixed: 0.3,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: null,
  },
  {
    name: 'Roofing Underlay',
    component_type: 'main',
    measurement_type: 'area',
    default_material_rate: 11,
    default_labour_rate: 3,
    default_waste_type: 'percent',
    default_waste_percent: 5,
    default_waste_fixed: 0,
    default_pitch_type: 'rafter',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'You can use area squared measurement type for many things in roofing, from underlay, to netting, tray long run, tiles, corrugated iron, rubber membrane and more! You can also define the waste type, as well as specify how you order your materials, per area squared, per roll, per pack etc. With these settings you can emulate basically any type of roofing material.',
  },
  {
    name: 'Rubber Membrane Roofing',
    component_type: 'main',
    measurement_type: 'area',
    default_material_rate: 0,
    default_labour_rate: 15,
    default_waste_type: 'percent',
    default_waste_percent: 10,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_pack_area',
    pack_price: 150,
    pack_size: 50,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Another example of area squared',
  },
  {
    name: 'Tek Screws (50mm)',
    component_type: 'main',
    measurement_type: 'area',
    default_material_rate: 1.5,
    default_labour_rate: 0,
    default_waste_type: 'percent',
    default_waste_percent: 5,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: null,
  },
  {
    name: 'Valley Flashing (Standard)',
    component_type: 'main',
    measurement_type: 'lineal',
    default_material_rate: 11,
    default_labour_rate: 5,
    default_waste_type: 'fixed',
    default_waste_percent: 0,
    default_waste_fixed: 0.4,
    default_pitch_type: 'valley_hip',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: null,
  },
];

export const GENERIC_STARTER_COMPONENTS: StarterComponent[] = [
  {
    name: 'Concrete Slab',
    component_type: 'main',
    measurement_type: 'volume_3d',
    default_material_rate: 25,
    default_labour_rate: 5,
    default_waste_type: 'percent',
    default_waste_percent: 5,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Volume measured components can cover many things from pools, foundations, soil for landscaping, shingle, internal spaces (attics etc)',
  },
  {
    name: 'Door',
    component_type: 'main',
    measurement_type: 'fixed',
    default_material_rate: 150,
    default_labour_rate: 50,
    default_waste_type: 'none',
    default_waste_percent: 0,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Another example of a fixed measurement component item. Fixed items can represent anything, travel allowance, accommodation, site visit, quote cost, inspection cost. Or many other examples like in the "Light Fixture" component',
  },
  {
    name: 'Electric Cable (Standard)',
    component_type: 'main',
    measurement_type: 'multi_lineal',
    default_material_rate: 15,
    default_labour_rate: 3,
    default_waste_type: 'fixed_per_segment',
    default_waste_percent: 0,
    default_waste_fixed: 0.1,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'This measurement (Multi-Line total) allows all kinds of components from pipes, fascia board, skirting, cables and more. This particular component uses fixed per segment waste. Meaning each point to point segment gets a set amount of waste. Example, you add 3 segments, 1m, 3m, and 4m - They get 0.1 added to each giving a total length of 8.3m',
  },
  {
    name: 'Floor Area',
    component_type: 'main',
    measurement_type: 'area',
    default_material_rate: 50,
    default_labour_rate: 15,
    default_waste_type: 'percent',
    default_waste_percent: 0,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Floor area could be used for many things. Tiles, carpet, timber flooring, varnish or polish areas, its very flexible',
  },
  {
    name: 'Light Fixture',
    component_type: 'main',
    measurement_type: 'fixed',
    default_material_rate: 25,
    default_labour_rate: 18,
    default_waste_type: 'none',
    default_waste_percent: 0,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Fixed measurement offers the most flexibility. It can represent literally anything, electrical components, brackets, fixings, consumables, skylights, solar panels, toilets, traps, fireplace, light switch, delivery cost, clean up cost, skip hire, just to name a few!',
  },
  {
    name: 'Plasterboard (Standard height)',
    component_type: 'main',
    measurement_type: 'multi_lineal_lxh',
    default_material_rate: 35,
    default_labour_rate: 8,
    default_waste_type: 'fixed_per_segment',
    default_waste_percent: 0,
    default_waste_fixed: 0.25,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: 2400,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Multi-Line height x length can be used for many items from fences, brick walls, retaining walls, internal walls, painting (walls), plastering etc!',
  },
  {
    name: 'Steel Beam',
    component_type: 'main',
    measurement_type: 'lineal',
    default_material_rate: 55,
    default_labour_rate: 30,
    default_waste_type: 'percent',
    default_waste_percent: 0,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Lineal, point to point measured items could represent many components from cables, pipes, drains, spouting, skirting boards and more',
  },
  {
    name: 'Tiled wall',
    component_type: 'main',
    measurement_type: 'length_x_height',
    default_material_rate: 28,
    default_labour_rate: 12,
    default_waste_type: 'percent',
    default_waste_percent: 10,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: 2400,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Length x Height components will measure an area for a specific section. This can be used for anything, screens, feature walls, paint, curtains, signs etc.',
  },
  {
    name: 'Wall area',
    component_type: 'main',
    measurement_type: 'area',
    default_material_rate: 55,
    default_labour_rate: 25,
    default_waste_type: 'percent',
    default_waste_percent: 5,
    default_waste_fixed: 0,
    default_pitch_type: 'none',
    eligible_for_orders: true,
    pricing_strategy: 'per_unit',
    pack_price: null,
    pack_size: null,
    pack_coverage_m2: null,
    height_value_mm: null,
    depth_value_mm: null,
    waste_unit: 'percent',
    notes: 'Area measurements can be used in multiple ways - floors, walls, coverings etc. Cladding (elevation plans), flooring (plan view) etc.',
  },
];
