-- P1.7.1 DRAFT / NOT APPLIED. Review on testing only before enabling
-- SMART_ASSISTANT_RESOLVER_ENABLED. Requires accepted P0/P1/P1.5/P1.6/P1.7.
-- Generated by scripts/generate-sa-resolver-sql.cjs. Original migrations,
-- registry, app business rows, RLS policies, quota and P3 mutations unchanged.
-- Candidate prefilter relies on existing server-built catalog_rows.search_text;
-- run DATABASE_ACCEPTANCE.md import-invariant and EXPLAIN gates first.
BEGIN;
-- Private short-lived resolver metadata, NOT a shadow copy of business data.
-- No direct privileges or RLS policy are granted to browser roles.
CREATE TABLE public.assistant_v2_resolution_states (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 run_id uuid NOT NULL UNIQUE REFERENCES public.smart_assistant_runs(id) ON DELETE CASCADE,
 company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
 conversation_id uuid NOT NULL REFERENCES public.smart_assistant_conversations(id) ON DELETE CASCADE,
 permission_revision integer NOT NULL CHECK(permission_revision>=0),
 sections text[] NOT NULL CHECK(cardinality(sections)<=9 AND array_position(sections,NULL) IS NULL
  AND sections <@ ARRAY['quotes','draft_quotes','orders','invoices','components','customers','emails','billing','settings']::text[]),
 state jsonb NOT NULL CHECK(jsonb_typeof(state)='object' AND octet_length(state::text)<=30000),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 expires_at timestamptz NOT NULL DEFAULT (clock_timestamp()+interval '15 minutes')
);
CREATE INDEX assistant_v2_resolution_owner_expiry ON public.assistant_v2_resolution_states(company_id,user_id,expires_at);
ALTER TABLE public.assistant_v2_resolution_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.assistant_v2_resolution_states FROM PUBLIC,anon,authenticated,service_role;
COMMENT ON TABLE public.assistant_v2_resolution_states IS 'Bounded expiring identity hints and clarification clues. No authoritative prices or business snapshots; proposed user inputs may be included. Read through current admitted-run/owner/revision boundary; every chosen business record is reread under invoker RLS.';

CREATE FUNCTION public.sa_v2_resolution_store(p_run_id uuid,p_user_id uuid,p_revision integer,p_sections text[],p_state jsonb) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $state$
DECLARE r public.smart_assistant_runs%ROWTYPE; saved public.assistant_v2_resolution_states%ROWTYPE; actual_revision integer;
BEGIN
 IF auth.role() IS DISTINCT FROM 'service_role' THEN RAISE EXCEPTION 'trusted_only' USING ERRCODE='42501'; END IF;
 SELECT * INTO r FROM public.smart_assistant_runs WHERE id=p_run_id AND user_id=p_user_id;
 IF NOT FOUND OR r.status NOT IN ('accepted','running')
  OR NOT EXISTS(SELECT 1 FROM public.users u WHERE u.id=p_user_id AND u.company_id=r.company_id)
  OR NOT EXISTS(SELECT 1 FROM public.smart_assistant_conversations c WHERE c.id=r.conversation_id AND c.user_id=p_user_id AND c.company_id=r.company_id)
  OR NOT COALESCE(public.smart_assistant_enabled(r.company_id),false)
  OR NOT EXISTS(SELECT 1 FROM public.assistant_v2_rollout f WHERE f.company_id=r.company_id AND f.p1)
  OR NOT EXISTS(SELECT 1 FROM public.assistant_v2_retrieval_rollout f WHERE f.company_id=r.company_id AND f.enabled)
  OR NOT EXISTS(SELECT 1 FROM public.assistant_v2_run_scopes sc WHERE sc.run_id=r.id AND sc.user_id=p_user_id AND sc.company_id=r.company_id AND sc.permission_revision=p_revision)
 THEN RAISE EXCEPTION 'access_changed' USING ERRCODE='42501'; END IF;
 SELECT COALESCE((SELECT p.revision FROM public.assistant_section_permissions p WHERE p.company_id=r.company_id),0) INTO actual_revision;
 IF actual_revision IS DISTINCT FROM p_revision THEN RAISE EXCEPTION 'access_changed' USING ERRCODE='42501'; END IF;
 IF jsonb_typeof(p_state) IS DISTINCT FROM 'object' OR octet_length(p_state::text)>30000
  OR p_state->'version' IS DISTINCT FROM '1'::jsonb OR COALESCE(p_state->>'status','') NOT IN ('pending','resolved','closed')
  OR jsonb_typeof(p_state->'intent') IS DISTINCT FROM 'object'
  OR jsonb_typeof(p_state->'candidates') IS DISTINCT FROM 'array' OR jsonb_array_length(p_state->'candidates')>5
  OR jsonb_typeof(p_state->'rejected') IS DISTINCT FROM 'array' OR jsonb_array_length(p_state->'rejected')>20
  OR p_sections IS NULL OR cardinality(p_sections)>9 OR array_position(p_sections,NULL) IS NOT NULL
  OR NOT p_sections <@ ARRAY['quotes','draft_quotes','orders','invoices','components','customers','emails','billing','settings']::text[]
 THEN RAISE EXCEPTION 'invalid_resolution_state' USING ERRCODE='22023'; END IF;
 -- One immutable resolution outcome per run. Retrying this trusted write is
 -- idempotent; attempting to change the choices after publication is rejected.
 INSERT INTO public.assistant_v2_resolution_states(run_id,company_id,user_id,conversation_id,permission_revision,sections,state)
 VALUES(r.id,r.company_id,r.user_id,r.conversation_id,p_revision,p_sections,p_state)
 ON CONFLICT(run_id) DO NOTHING;
 SELECT * INTO saved FROM public.assistant_v2_resolution_states WHERE run_id=r.id;
 IF saved.state IS DISTINCT FROM p_state OR saved.sections IS DISTINCT FROM p_sections OR saved.permission_revision IS DISTINCT FROM p_revision
 THEN RAISE EXCEPTION 'resolution_already_set' USING ERRCODE='22023'; END IF;
 -- Opportunistic bounded pruning of THIS ACTOR's expired resolver hints only.
 -- Does not delete messages, audit proofs, action proposals or other companies.
 DELETE FROM public.assistant_v2_resolution_states x WHERE x.id IN (
  SELECT old.id FROM public.assistant_v2_resolution_states old
  WHERE old.company_id=r.company_id AND old.user_id=r.user_id AND old.expires_at<clock_timestamp()
  ORDER BY old.expires_at LIMIT 100);
 RETURN jsonb_build_object('id',saved.id,'expires_at',saved.expires_at);
END;
$state$;
REVOKE ALL ON FUNCTION public.sa_v2_resolution_store(uuid,uuid,integer,text[],jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.sa_v2_resolution_store(uuid,uuid,integer,text[],jsonb) TO service_role;

-- SECURITY DEFINER here is limited to private ASSISTANT metadata. This function
-- cannot read any business source and is not a substitute for invoker RLS.
CREATE FUNCTION public.sa_v2_resolution_read(p_run_id uuid,p_revision integer,p_state_id uuid DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $state$
DECLARE v jsonb:=public.sa_v2_retrieval_scope(p_run_id,p_revision); current_run public.smart_assistant_runs%ROWTYPE; prior_id uuid; result jsonb;
BEGIN
 IF NOT COALESCE((v->>'retrieval_enabled')::boolean,false) THEN RAISE EXCEPTION 'retrieval_disabled' USING ERRCODE='42501'; END IF;
 SELECT * INTO current_run FROM public.smart_assistant_runs WHERE id=p_run_id AND user_id=auth.uid() AND company_id=(v->>'company_id')::uuid;
 IF NOT FOUND THEN RAISE EXCEPTION 'access_changed' USING ERRCODE='42501'; END IF;
 SELECT r.id INTO prior_id FROM public.smart_assistant_runs r
 WHERE r.conversation_id=current_run.conversation_id AND r.company_id=current_run.company_id AND r.user_id=auth.uid()
  AND r.id<>current_run.id AND r.status='completed' AND r.started_at<=current_run.started_at
 ORDER BY r.started_at DESC,r.id DESC LIMIT 1;
 -- Expired, wrong-conversation, rejected-state, foreign and stale references all
 -- return the same null. No cross-tenant existence oracle is exposed.
 SELECT jsonb_build_object('id',s.id,'expires_at',s.expires_at,'state',s.state) INTO result
 FROM public.assistant_v2_resolution_states s
 WHERE s.run_id=prior_id AND (p_state_id IS NULL OR s.id=p_state_id)
  AND s.user_id=auth.uid() AND s.company_id=current_run.company_id AND s.conversation_id=current_run.conversation_id
  AND s.permission_revision=p_revision AND s.expires_at>CURRENT_TIMESTAMP
  AND s.created_at>=COALESCE((v->>'history_after')::timestamptz,'-infinity'::timestamptz)
  AND s.created_at>=COALESCE((v->>'knowledge_history_after')::timestamptz,'-infinity'::timestamptz)
  AND NOT EXISTS(SELECT 1 FROM unnest(s.sections) sec WHERE COALESCE(v->'permissions'->>sec,'hidden')='hidden');
 RETURN result;
END;
$state$;
REVOKE ALL ON FUNCTION public.sa_v2_resolution_read(uuid,integer,uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.sa_v2_resolution_read(uuid,integer,uuid) TO authenticated;


CREATE FUNCTION public.sa_v2_retrieval_query_v171(p_run_id uuid,p_revision integer,p_plan jsonb) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path=pg_catalog,pg_temp SET row_security=on SET statement_timeout='8s' AS $fn$
DECLARE
 v jsonb:=public.sa_v2_retrieval_scope(p_run_id,p_revision); source text; spec jsonb; mode text; field text; f jsonb; item jsonb; rel jsonb; child jsonb;
 selected jsonb; groups jsonb; metrics jsonb; ordering jsonb; filters jsonb; related jsonb; vals jsonb:='[]'; compiled jsonb;
 base text; predicate text; childpred text; childbase text; query text; rows jsonb; result jsonb; obj text; selects text; sorts text:=''; group_sql text:='';
 rank_sql text:='jsonb_build_object(''tier'',0,''score'',0)'; search_json jsonb; limit_n integer; idx integer:=0; j integer; dir text; fn text;
 engine boolean:=false; truncated boolean:=false; complete boolean:=true; ids uuid[]; snapshots jsonb; dims jsonb; d text; period_field text; preset text; boundary text; scope text; isresolve boolean;
 ranking_field text; ranking_metric jsonb; rank_dimensions jsonb:='[]'::jsonb; dimension_sql text:=''; dimension_missing_sql text:='false';
 catalogue_candidates integer; token text; prefilter_index integer;
 coverage_sql text; coverage jsonb; missing_sql text; rank_extra text:=''; input_columns text; input_fields jsonb;

BEGIN
 IF jsonb_typeof(p_plan) IS DISTINCT FROM 'object' OR octet_length(p_plan::text)>16000
 OR p_plan->'version' IS DISTINCT FROM '1'::jsonb
 OR EXISTS(SELECT 1 FROM jsonb_object_keys(p_plan) k(key) WHERE k.key NOT IN ('version','source','mode','fields','filters','related','search','quoteScope','owner','period','groupBy','metrics','orderBy','limit','resolve','current'))
 THEN RAISE EXCEPTION 'invalid_plan' USING ERRCODE='22023'; END IF;
 source:=p_plan->>'source'; spec:=public.sa_v2_retrieval_check_source(source,v); mode:=COALESCE(p_plan->>'mode','rows');
 IF mode NOT IN ('rows','aggregate') OR (p_plan ? 'current' AND p_plan->'current'<>'false'::jsonb)
   OR (p_plan ? 'resolve' AND jsonb_typeof(p_plan->'resolve')<>'boolean') THEN RAISE EXCEPTION 'invalid_mode_or_context' USING ERRCODE='22023'; END IF;
 isresolve:=COALESCE((p_plan->>'resolve')::boolean,false);
 IF mode='aggregate' AND isresolve THEN RAISE EXCEPTION 'invalid_aggregate_resolution' USING ERRCODE='22023'; END IF;
 IF p_plan ? 'limit' AND (jsonb_typeof(p_plan->'limit')<>'number' OR p_plan->>'limit' !~ '^([1-9]|1[0-9]|20)$') THEN RAISE EXCEPTION 'invalid_limit' USING ERRCODE='22023'; END IF;
 limit_n:=COALESCE((p_plan->>'limit')::integer,10); IF isresolve THEN limit_n:=GREATEST(5,limit_n); END IF;
 selected:=COALESCE(p_plan->'fields',CASE WHEN mode='rows' THEN spec->'defaults' ELSE '[]'::jsonb END);
 groups:=COALESCE(p_plan->'groupBy','[]'); metrics:=COALESCE(p_plan->'metrics','[]'); ordering:=COALESCE(p_plan->'orderBy','[]'); filters:=COALESCE(p_plan->'filters','[]'); related:=COALESCE(p_plan->'related','[]');
 IF jsonb_typeof(selected)<>'array' OR jsonb_array_length(selected)>16 OR jsonb_typeof(groups)<>'array' OR jsonb_array_length(groups)>5
 OR jsonb_typeof(metrics)<>'array' OR jsonb_array_length(metrics)>3 OR jsonb_typeof(ordering)<>'array' OR jsonb_array_length(ordering)>3
 OR jsonb_typeof(related)<>'array' OR jsonb_array_length(related)>2 THEN RAISE EXCEPTION 'invalid_array_bounds' USING ERRCODE='22023'; END IF;
 IF (mode='aggregate' AND (jsonb_array_length(metrics)=0 OR jsonb_array_length(selected)<>0))
 OR (mode='rows' AND (jsonb_array_length(metrics)>0 OR jsonb_array_length(groups)>0)) THEN RAISE EXCEPTION 'invalid_projection' USING ERRCODE='22023'; END IF;
 FOR field IN SELECT value FROM jsonb_array_elements_text(selected) LOOP
  f:=public.sa_v2_retrieval_field(source,field,v); engine:=engine OR f ? 'engine';
  IF mode='rows' THEN
   dims:=COALESCE(f->'dimensions',CASE WHEN f ? 'dimension' THEN jsonb_build_array(f->>'dimension') ELSE '[]'::jsonb END);
   FOR d IN SELECT value FROM jsonb_array_elements_text(dims) LOOP
    PERFORM public.sa_v2_retrieval_field(source,d,v);
    IF NOT selected ? d THEN selected:=selected||jsonb_build_array(d); END IF;
   END LOOP;
  END IF;
 END LOOP;
 IF jsonb_array_length(selected)>16 THEN RAISE EXCEPTION 'row_dimension_limit' USING ERRCODE='22023'; END IF;
 FOR field IN SELECT value FROM jsonb_array_elements_text(groups) LOOP
  f:=public.sa_v2_retrieval_field(source,field,v); IF f ? 'engine' OR f->>'type'='json' THEN RAISE EXCEPTION 'invalid_group' USING ERRCODE='22023'; END IF;
 END LOOP;
 FOR item IN SELECT value FROM jsonb_array_elements(metrics) LOOP
  IF jsonb_typeof(item)<>'object' OR EXISTS(SELECT 1 FROM jsonb_object_keys(item) k(key) WHERE k.key NOT IN ('field','op')) OR item->>'op' IS NULL OR item->>'op' NOT IN ('count','sum','min','max','avg') THEN RAISE EXCEPTION 'invalid_metric' USING ERRCODE='22023'; END IF;
  IF item->>'op'<>'count' OR item ? 'field' THEN
   f:=public.sa_v2_retrieval_field(source,item->>'field',v); engine:=engine OR f ? 'engine';
   IF item->>'op'<>'count' AND (NOT COALESCE((f->>'aggregate')::boolean,false) OR f->>'type'<>'number') THEN RAISE EXCEPTION 'invalid_numeric_metric' USING ERRCODE='P1603'; END IF;
   IF item->>'op'<>'count' THEN
    dims:=COALESCE(f->'dimensions',CASE WHEN f ? 'dimension' THEN jsonb_build_array(f->>'dimension') ELSE '[]'::jsonb END);
    FOR d IN SELECT value FROM jsonb_array_elements_text(dims) LOOP IF NOT groups ? d THEN groups:=groups||jsonb_build_array(d); END IF; END LOOP;
   END IF;
  END IF;
 END LOOP;
 IF jsonb_array_length(groups)>5 THEN RAISE EXCEPTION 'too_many_dimensions' USING ERRCODE='22023'; END IF;
 FOR item IN SELECT value FROM jsonb_array_elements(ordering) LOOP
  IF jsonb_typeof(item)<>'object' OR EXISTS(SELECT 1 FROM jsonb_object_keys(item) k(key) WHERE k.key NOT IN ('field','direction')) OR COALESCE(item->>'direction','asc') NOT IN ('asc','desc') THEN RAISE EXCEPTION 'invalid_sort' USING ERRCODE='22023'; END IF;
  field:=item->>'field';
  IF mode='aggregate' THEN
   IF NOT groups ? field AND NOT (field ~ '^metric_[0-2]$' AND substring(field FROM 8)::integer<jsonb_array_length(metrics)) THEN RAISE EXCEPTION 'invalid_sort_field' USING ERRCODE='22023'; END IF;
  ELSE f:=public.sa_v2_retrieval_field(source,field,v); engine:=engine OR f ? 'engine'; IF f->>'type'='json' THEN RAISE EXCEPTION 'invalid_sort_field' USING ERRCODE='22023'; END IF;
  END IF;
 END LOOP;
 -- Primary numeric order defines a value ranking. Secondary order keys only
 -- break display ties, never create a false unique winner. No fuzzy population.
 IF jsonb_array_length(ordering)>0 THEN
  field:=ordering->0->>'field';
  IF mode='aggregate' AND field ~ '^metric_[0-2]$' THEN
   ranking_field:=field; ranking_metric:=metrics->(substring(field FROM 8)::integer);
   IF ranking_metric->>'op'<>'count' THEN
    f:=public.sa_v2_retrieval_field(source,ranking_metric->>'field',v);
    rank_dimensions:=COALESCE(f->'dimensions',CASE WHEN f ? 'dimension' THEN jsonb_build_array(f->>'dimension') ELSE '[]'::jsonb END);
   END IF;
  ELSIF mode='rows' THEN
   f:=public.sa_v2_retrieval_field(source,field,v);
   IF f->>'type'='number' THEN
    ranking_field:=field;
    rank_dimensions:=COALESCE(f->'dimensions',CASE WHEN f ? 'dimension' THEN jsonb_build_array(f->>'dimension') ELSE '[]'::jsonb END);
    IF NOT selected ? field THEN selected:=selected||jsonb_build_array(field); END IF;
   END IF;
  END IF;
 END IF;
 IF ranking_field IS NOT NULL AND p_plan ? 'search' AND COALESCE(p_plan->'search'->>'match','natural')='natural' THEN RAISE EXCEPTION 'numeric_ranking_requires_definite_membership' USING ERRCODE='22023'; END IF;
 SELECT COALESCE(jsonb_agg(x.value ORDER BY x.value),'[]'::jsonb) INTO rank_dimensions FROM (SELECT DISTINCT value FROM jsonb_array_elements_text(rank_dimensions)) x;
 FOR d IN SELECT value FROM jsonb_array_elements_text(rank_dimensions) LOOP
  PERFORM public.sa_v2_retrieval_field(source,d,v);
  IF mode='rows' AND NOT selected ? d THEN selected:=selected||jsonb_build_array(d); END IF;
  dimension_sql:=dimension_sql||CASE WHEN dimension_sql='' THEN '' ELSE ',' END||format('r.%I',d);
  dimension_missing_sql:=dimension_missing_sql||format(' OR r.%I IS NULL',d);
 END LOOP;
 IF jsonb_array_length(selected)>16 THEN RAISE EXCEPTION 'row_dimension_limit' USING ERRCODE='22023'; END IF;
 IF engine AND source<>'quotes' THEN RAISE EXCEPTION 'unsupported_engine_source' USING ERRCODE='P1603'; END IF;
 base:=public.sa_v2_retrieval_base(source,v);
 compiled:=public.sa_v2_retrieval_filters(source,filters,v,0); predicate:=compiled->>'sql'; vals:=compiled->'values';
 scope:=COALESCE(p_plan->>'quoteScope','all_permitted');
 IF scope NOT IN ('quotes','drafts','all_permitted') OR (NOT COALESCE((spec->>'quoteScoped')::boolean,false) AND scope<>'all_permitted') THEN RAISE EXCEPTION 'invalid_quote_scope' USING ERRCODE='22023'; END IF;
 IF COALESCE((spec->>'quoteScoped')::boolean,false) AND scope<>'all_permitted' THEN
  IF COALESCE(v->'permissions'->>(CASE WHEN scope='drafts' THEN 'draft_quotes' ELSE 'quotes' END),'hidden')='hidden' THEN RAISE EXCEPTION 'section_hidden' USING ERRCODE='P1604'; END IF;
  predicate:=predicate||format(' AND r.%I %s ''draft''',spec->>'quoteStatus',CASE WHEN scope='drafts' THEN '=' ELSE '<>' END);
 END IF;
 IF COALESCE(p_plan->>'owner','workspace') NOT IN ('me','workspace') THEN RAISE EXCEPTION 'invalid_owner' USING ERRCODE='22023'; END IF;
 IF p_plan->>'owner'='me' THEN
  IF NOT spec ? 'ownerField' THEN RAISE EXCEPTION 'owner_not_supported' USING ERRCODE='P1603'; END IF;
  predicate:=predicate||format(' AND r.%I=($1->>''user_id'')::uuid',spec->>'ownerField');
 END IF;
 IF p_plan ? 'period' THEN
  item:=p_plan->'period';
  IF jsonb_typeof(item)<>'object' OR EXISTS(SELECT 1 FROM jsonb_object_keys(item) k(key) WHERE k.key NOT IN ('field','preset')) THEN RAISE EXCEPTION 'invalid_period' USING ERRCODE='22023'; END IF;
  period_field:=item->>'field'; f:=public.sa_v2_retrieval_field(source,period_field,v); preset:=item->>'preset';
  IF f->>'type' NOT IN ('date','timestamp') OR preset IS NULL OR preset NOT IN ('this_month','last_month','this_year','last_year') THEN RAISE EXCEPTION 'invalid_period' USING ERRCODE='22023'; END IF;
  boundary:=CASE WHEN preset IN ('this_month','last_month') THEN 'date_trunc(''month'',CURRENT_TIMESTAMP AT TIME ZONE ''UTC'')' ELSE 'date_trunc(''year'',CURRENT_TIMESTAMP AT TIME ZONE ''UTC'')' END;
  IF preset IN ('last_month','last_year') THEN boundary:='('||boundary||CASE WHEN preset='last_month' THEN ' - interval ''1 month'')' ELSE ' - interval ''1 year'')' END; END IF;
  predicate:=predicate||format(' AND r.%I >= (%s AT TIME ZONE ''UTC'') AND r.%I < ((%s + interval %L) AT TIME ZONE ''UTC'')',period_field,boundary,period_field,boundary,CASE WHEN preset IN ('this_month','last_month') THEN '1 month' ELSE '1 year' END);
 END IF;
 -- Each relationship is an EXISTS semi-join over another independently scoped
 -- registered source. It cannot multiply rows, loosen parent scope, or recurse.
 idx:=0;
 FOR item IN SELECT value FROM jsonb_array_elements(related) LOOP
  IF jsonb_typeof(item)<>'object' OR EXISTS(SELECT 1 FROM jsonb_object_keys(item) k(key) WHERE k.key NOT IN ('relation','filters','search')) THEN RAISE EXCEPTION 'invalid_relation' USING ERRCODE='22023'; END IF;
  rel:=spec->'relations'->(item->>'relation'); IF rel IS NULL THEN RAISE EXCEPTION 'unsupported_relation' USING ERRCODE='P1603'; END IF;
  child:=public.sa_v2_retrieval_check_source(rel->>'source',v); childbase:=public.sa_v2_retrieval_base(rel->>'source',v);
  compiled:=public.sa_v2_retrieval_filters(rel->>'source',COALESCE(item->'filters','[]'),v,jsonb_array_length(vals)); childpred:=compiled->>'sql'; vals:=vals||(compiled->'values');
  IF item ? 'search' THEN
   IF rel->>'source'='catalogue_rows' THEN RAISE EXCEPTION 'catalogue_query_rows_with_parent_filter' USING ERRCODE='P1712'; END IF;
   IF NOT COALESCE(public.sa_v2_retrieval_search_valid(item->'search',false),false) THEN RAISE EXCEPTION 'invalid_related_search' USING ERRCODE='22023'; END IF;
   childpred:=childpred||format(' AND (public.sa_v2_retrieval_rank(r._names,r._search,$2->''related''->%s->''search''->>''text'',$2->''related''->%s->''search''->>''match'')->>''tier'')::integer>0',idx,idx);
  END IF;
  predicate:=predicate||format(' AND EXISTS(SELECT 1 FROM (SELECT * FROM (%s) r WHERE %s) rel_match WHERE rel_match.%I=r.%I)',childbase,childpred,rel->>'foreign',rel->>'local'); idx:=idx+1;
 END LOOP;
 IF p_plan ? 'search' THEN
  search_json:=p_plan->'search';
  IF NOT COALESCE(public.sa_v2_retrieval_search_valid(search_json-'field',mode='rows'),false) THEN RAISE EXCEPTION 'invalid_search' USING ERRCODE='22023'; END IF;
  rank_sql:='public.sa_v2_retrieval_rank(r._names,r._search,$2->''search''->>''text'',COALESCE($2->''search''->>''match'',''natural''))';
  IF search_json ? 'field' THEN
   IF jsonb_typeof(search_json->'field')<>'string' THEN RAISE EXCEPTION 'invalid_search_field' USING ERRCODE='22023'; END IF;
   f:=public.sa_v2_retrieval_field(source,search_json->>'field',v);
   IF f->>'type'<>'text' OR f ? 'engine' THEN RAISE EXCEPTION 'invalid_search_field' USING ERRCODE='22023'; END IF;
   rank_sql:=format('public.sa_v2_retrieval_rank(jsonb_build_array(r.%I),r.%I,$2->''search''->>''text'',COALESCE($2->''search''->>''match'',''natural''))',search_json->>'field',search_json->>'field');
  END IF;
  -- A necessary indexed prefilter, never a replacement for the exact/words
  -- predicate. Imported search_text is server-built from ALL raw_row values.
  -- Do not prefilter a parent catalogue_name: that isn't an imported cell.
  IF source='catalogue_rows' THEN
   IF COALESCE(search_json->>'match','natural') NOT IN ('words','exact') THEN
    RAISE EXCEPTION 'catalogue_use_words_or_exact' USING ERRCODE='P1712';
   END IF;
   IF NOT search_json ? 'field' OR search_json->>'field' IN ('description','mapped_price_text','mapped_quantity_text') THEN
    FOR token IN SELECT word FROM regexp_split_to_table(public.sa_v2_retrieval_normalize(search_json->>'text'),' +') word WHERE length(word)>=3 LOOP
     -- Alphanumeric normalisation eliminates LIKE wildcards. Values remain
     -- parameters in $3, not SQL expressions or model-authored identifiers.
     prefilter_index:=jsonb_array_length(vals);
     vals:=vals||jsonb_build_array('%'||token||'%');
     predicate:=predicate||format(' AND r.search_text ILIKE ($3->>%s)',prefilter_index);
    END LOOP;
   END IF;
   -- Dense catalogues must fail clearly rather than rank an arbitrary page or
   -- scan 100k expensive PL/pgSQL rank calls. This is a count of at most 1501
   -- candidates BEFORE ranking; no subset is presented as a complete result.
   EXECUTE format('SELECT count(*) FROM (SELECT 1 FROM (%s) r WHERE %s LIMIT 1501) bounded_candidates',base,predicate)
    INTO catalogue_candidates USING v,p_plan,vals;
   IF catalogue_candidates>1500 THEN RAISE EXCEPTION 'catalogue_candidates_too_broad' USING ERRCODE='P1711'; END IF;
  END IF;
  predicate:=predicate||' AND ('||rank_sql||'->>''tier'')::integer>0';
 END IF;

 IF engine THEN
  -- Materialise every matching quote up to a hard refuse boundary, never the
  -- first 200 advertised as a global winner. Do not include calculated fields
  -- here: their ONLY producer is the unchanged QuoteCore engine in the server.
  selected:=selected||groups||' ["id","quote_number","customer_name","job_name","status","currency","updated_at"]'::jsonb;
  FOR item IN SELECT value FROM jsonb_array_elements(metrics) LOOP IF item ? 'field' THEN selected:=selected||jsonb_build_array(item->>'field'); END IF; END LOOP;
  obj:='jsonb_build_object(''_row_id'',r.id::text,''_kind'',r._kind,''_section'',r._section,''_target_id'',r._target_id,''_touched'',r._touched,''_rank'','||rank_sql;
  FOR field IN SELECT DISTINCT value FROM jsonb_array_elements_text(selected) LOOP
   f:=public.sa_v2_retrieval_field(source,field,v); IF f ? 'engine' THEN CONTINUE; END IF;
   obj:=obj||format(',%L,r.%I%s',field,field,CASE WHEN f->>'type'='number' THEN '::text' ELSE '' END);
  END LOOP; obj:=obj||')';
  query:=format('SELECT COALESCE(jsonb_agg(z.obj ORDER BY z.id),''[]''::jsonb) FROM (SELECT r.id,%s AS obj FROM (%s) r WHERE %s ORDER BY r.id LIMIT 201) z',obj,base,predicate);
  EXECUTE query INTO rows USING v,p_plan,vals;
  IF jsonb_array_length(rows)>200 OR octet_length(rows::text)>262144 THEN
   RETURN jsonb_build_object('version',1,'schema_hash','feaff3719950d5d17cd163326b06d5641f1b03a915fe947aa9b9abfa94b6eaad','source',source,'mode','engine_inputs','rows','[]'::jsonb,'as_of',CURRENT_TIMESTAMP,'complete',false,'truncated',true,'group_by',groups,'status','too_broad','warnings',jsonb_build_array('The quote batch exceeds 200 records or its bounded payload. Narrow by date, customer, status or selected fields; no partial global total or ranking was calculated.'));
  END IF;
  SELECT COALESCE(array_agg((r.value->>'id')::uuid),ARRAY[]::uuid[]) INTO ids FROM jsonb_array_elements(rows) r(value);
  snapshots:=public.sa_v2_retrieval_quote_inputs(p_run_id,p_revision,ids);
  RETURN jsonb_build_object('version',1,'schema_hash','feaff3719950d5d17cd163326b06d5641f1b03a915fe947aa9b9abfa94b6eaad','source',source,'mode','engine_inputs','rows',rows,'as_of',CURRENT_TIMESTAMP,'complete',(snapshots->>'complete')::boolean,'truncated',false,'group_by',groups,'snapshots',snapshots,'warnings',CASE WHEN (snapshots->>'complete')::boolean THEN '[]'::jsonb ELSE jsonb_build_array('The selected quotes exceed the bounded engine-input reader. No partial calculation was made.') END);
 END IF;

 -- Stored-value execution. Full-population evidence is computed in this SAME
 -- RLS/admitted-run snapshot, before LIMIT. No totals/ranks from a page sample.
 IF mode='rows' THEN
  obj:='jsonb_build_object(''_row_id'',r.id::text,''_kind'',r._kind,''_section'',r._section,''_target_id'',r._target_id,''_touched'',r._touched,''_rank'','||rank_sql;
  FOR field IN SELECT DISTINCT value FROM jsonb_array_elements_text(selected) LOOP
   f:=public.sa_v2_retrieval_field(source,field,v);
   obj:=obj||format(',%L,r.%I%s',field,field,CASE WHEN f->>'type'='number' THEN '::text' ELSE '' END);
  END LOOP;
  IF ranking_field IS NOT NULL THEN
   obj:=obj||format(',''_position'',(rank() OVER (ORDER BY r.%I %s NULLS LAST))::text,''_tie_count'',(count(*) OVER (PARTITION BY r.%I))::text',ranking_field,upper(ordering->0->>'direction'),ranking_field);
  END IF;
  obj:=obj||')';
  IF search_json IS NOT NULL AND ranking_field IS NULL THEN sorts:='('||rank_sql||'->>''tier'')::integer DESC,('||rank_sql||'->>''score'')::numeric DESC,'; END IF;
  FOR item IN SELECT value FROM jsonb_array_elements(ordering) LOOP sorts:=sorts||format('r.%I %s NULLS LAST,',item->>'field',upper(COALESCE(item->>'direction','asc'))); END LOOP;
  sorts:=sorts||'r._touched DESC NULLS LAST,r.id::text';
  IF ranking_field IS NULL THEN
   -- Leave ordinary record resolution on the existing inexpensive bounded path.
   query:=format('SELECT COALESCE(jsonb_agg(z.obj ORDER BY z.n),''[]''::jsonb) FROM (SELECT %s AS obj,row_number() OVER (ORDER BY %s) n FROM (%s) r WHERE %s ORDER BY %s LIMIT %s) z',obj,sorts,base,predicate,sorts,limit_n+1);
   EXECUTE query INTO rows USING v,p_plan,vals;
  ELSE
   -- Materialise only the requested data/ordering plus bounded search metadata.
   input_fields:=selected||jsonb_build_array('id','_kind','_section','_target_id','_touched','_names','_search');
   IF search_json ? 'field' THEN input_fields:=input_fields||jsonb_build_array(search_json->>'field'); END IF;
   FOR item IN SELECT value FROM jsonb_array_elements(ordering) LOOP input_fields:=input_fields||jsonb_build_array(item->>'field'); END LOOP;
   input_columns:=''; FOR field IN SELECT DISTINCT value FROM jsonb_array_elements_text(input_fields) LOOP input_columns:=input_columns||CASE WHEN input_columns='' THEN '' ELSE ',' END||format('r.%I',field); END LOOP;
   missing_sql:=format('(SELECT (count(*)-count(r.%I))::text FROM filtered r)',ranking_field);
   coverage_sql:=format('jsonb_build_object(''version'',1,''ranked'',true,''matchedRows'',(SELECT count(*)::text FROM filtered),''groupCount'',(SELECT count(*)::text FROM filtered),''missingValues'',%s,''dimensions'',%L::jsonb,''dimensionCount'',%s,''missingDimensions'',%s)',missing_sql,rank_dimensions::text,
    CASE WHEN dimension_sql='' THEN '''0''::text' ELSE format('(SELECT count(DISTINCT ROW(%s))::text FROM filtered r)',dimension_sql) END,
    CASE WHEN dimension_sql='' THEN '''0''::text' ELSE format('(SELECT count(*)::text FROM filtered r WHERE %s)',dimension_missing_sql) END);
   query:=format('WITH filtered AS MATERIALIZED (SELECT %s FROM (%s) r WHERE %s), ranked AS (SELECT %s AS obj,row_number() OVER (ORDER BY %s) n FROM filtered r) SELECT jsonb_build_object(''rows'',(SELECT COALESCE(jsonb_agg(z.obj ORDER BY z.n),''[]''::jsonb) FROM (SELECT * FROM ranked ORDER BY n LIMIT %s) z),''coverage'',%s)',input_columns,base,predicate,obj,sorts,limit_n+1,coverage_sql);
   EXECUTE query INTO result USING v,p_plan,vals;
   rows:=result->'rows'; coverage:=result->'coverage';
  END IF;
 ELSE
  selects:=''; group_sql:=''; obj:='jsonb_build_object(''_matched'',a._matched::text'; idx:=0; missing_sql:='0'; input_fields:=groups;
  FOR field IN SELECT DISTINCT value FROM jsonb_array_elements_text(groups) LOOP
   f:=public.sa_v2_retrieval_field(source,field,v);
   selects:=selects||format('r.%I AS %I,',field,field); group_sql:=group_sql||CASE WHEN group_sql='' THEN '' ELSE ',' END||format('r.%I',field);
   obj:=obj||format(',%L,a.%I%s',field,field,CASE WHEN f->>'type'='number' THEN '::text' ELSE '' END);
  END LOOP;
  FOR item IN SELECT value FROM jsonb_array_elements(metrics) LOOP
   fn:=item->>'op'; field:=item->>'field';
   IF field IS NOT NULL THEN input_fields:=input_fields||jsonb_build_array(field); END IF;
   selects:=selects||CASE WHEN field IS NULL THEN 'count(*)' ELSE format('%s(r.%I)',fn,field) END||format(' AS metric_%s,',idx);
   IF field IS NOT NULL AND fn<>'count' THEN
    selects:=selects||format('(count(*)-count(r.%I)) AS _missing_%s,',field,idx);
    obj:=obj||format(',%L,a._missing_%s::text','_missing_'||idx,idx);
    missing_sql:=missing_sql||format('+a._missing_%s',idx);
   END IF;
   obj:=obj||format(',%L,a.metric_%s::text','metric_'||idx,idx); idx:=idx+1;
  END LOOP;
  selects:=selects||'count(*) AS _matched';
  IF ranking_field IS NOT NULL THEN obj:=obj||format(',''_position'',(rank() OVER (ORDER BY a.%I %s NULLS LAST))::text,''_tie_count'',(count(*) OVER (PARTITION BY a.%I))::text',ranking_field,upper(ordering->0->>'direction'),ranking_field); END IF;
  obj:=obj||')';
  FOR item IN SELECT value FROM jsonb_array_elements(ordering) LOOP sorts:=sorts||format('a.%I %s NULLS LAST,',item->>'field',upper(COALESCE(item->>'direction','asc'))); END LOOP;
  FOR field IN SELECT DISTINCT value FROM jsonb_array_elements_text(groups) LOOP sorts:=sorts||format('a.%I ASC NULLS LAST,',field); END LOOP;
  sorts:=CASE WHEN sorts='' THEN 'a._matched DESC' ELSE left(sorts,length(sorts)-1) END;
  input_columns:=''; FOR field IN SELECT DISTINCT value FROM jsonb_array_elements_text(input_fields||rank_dimensions) LOOP input_columns:=input_columns||CASE WHEN input_columns='' THEN '' ELSE ',' END||format('r.%I',field); END LOOP;
  IF input_columns='' THEN input_columns:='1 AS _input_row'; END IF;
  coverage_sql:=format('jsonb_build_object(''version'',1,''ranked'',%s,''matchedRows'',(SELECT count(*)::text FROM filtered),''groupCount'',(SELECT count(*)::text FROM aggregate_data),''missingValues'',(SELECT COALESCE(sum(%s),0)::text FROM aggregate_data a),''dimensions'',%L::jsonb,''dimensionCount'',%s,''missingDimensions'',%s)',CASE WHEN ranking_field IS NULL THEN 'false' ELSE 'true' END,missing_sql,rank_dimensions::text,
   CASE WHEN dimension_sql='' THEN '''0''::text' ELSE format('(SELECT count(DISTINCT ROW(%s))::text FROM filtered r)',dimension_sql) END,
   CASE WHEN dimension_sql='' THEN '''0''::text' ELSE format('(SELECT count(*)::text FROM filtered r WHERE %s)',dimension_missing_sql) END);
  query:=format('WITH filtered AS MATERIALIZED (SELECT %s FROM (%s) r WHERE %s), aggregate_data AS MATERIALIZED (SELECT %s FROM filtered r %s), ranked AS (SELECT %s AS obj,row_number() OVER (ORDER BY %s) n FROM aggregate_data a) SELECT jsonb_build_object(''rows'',(SELECT COALESCE(jsonb_agg(z.obj ORDER BY z.n),''[]''::jsonb) FROM (SELECT * FROM ranked ORDER BY n LIMIT %s) z),''coverage'',%s)',input_columns,base,predicate,selects,CASE WHEN group_sql='' THEN '' ELSE 'GROUP BY '||group_sql END,obj,sorts,limit_n+1,coverage_sql);
  EXECUTE query INTO result USING v,p_plan,vals;
  rows:=result->'rows'; coverage:=result->'coverage';
 END IF;
 truncated:=jsonb_array_length(rows)>limit_n;
 IF truncated THEN rows:=rows-limit_n; END IF;
 IF coverage IS NOT NULL THEN complete:=(coverage->>'missingValues')::numeric=0 AND (coverage->>'missingDimensions')::numeric=0; END IF;
 result:=jsonb_build_object('version',1,'schema_hash','feaff3719950d5d17cd163326b06d5641f1b03a915fe947aa9b9abfa94b6eaad','source',source,'mode',mode,'rows',rows,'as_of',CURRENT_TIMESTAMP,'complete',complete,'truncated',truncated,'group_by',groups,'warnings',
   CASE WHEN complete THEN '[]'::jsonb ELSE jsonb_build_array('Some matching rows have missing numeric values. Available-value aggregates are not complete totals.') END);
 IF coverage IS NOT NULL THEN result:=result||jsonb_build_object('coverage',coverage); END IF;
 IF octet_length(result::text)>262144 THEN
  RETURN jsonb_build_object('version',1,'schema_hash','feaff3719950d5d17cd163326b06d5641f1b03a915fe947aa9b9abfa94b6eaad','source',source,'mode',mode,'rows','[]'::jsonb,'as_of',CURRENT_TIMESTAMP,'complete',false,'truncated',true,'group_by',groups,'status','too_broad','warnings',jsonb_build_array('The result is too large. Request fewer fields or narrower filters; no silently truncated field values were returned.'));
 END IF;
 RETURN result;
END;
$fn$;
REVOKE ALL ON FUNCTION public.sa_v2_retrieval_query_v171(uuid,integer,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.sa_v2_retrieval_query_v171(uuid,integer,jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.sa_v2_retrieval_capabilities(p_run_id uuid,p_revision integer) RETURNS jsonb
LANGUAGE sql STABLE SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $fn$
 SELECT jsonb_build_object('version',1,'intelligence_version',1,'resolver_version',1,'schema_hash','feaff3719950d5d17cd163326b06d5641f1b03a915fe947aa9b9abfa94b6eaad','enabled',(v->>'retrieval_enabled')::boolean,
   'knowledge_enabled',(v->>'retrieval_knowledge')::boolean,'knowledge_revision',v->>'knowledge_revision','knowledge_history_after',v->>'knowledge_history_after','catalogues_allowed',(v->>'catalogues_allowed')::boolean)
 FROM (SELECT public.sa_v2_retrieval_scope(p_run_id,p_revision) v) a;
$fn$;
REVOKE ALL ON FUNCTION public.sa_v2_retrieval_capabilities(uuid,integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.sa_v2_retrieval_capabilities(uuid,integer) TO authenticated;

COMMIT;
