import type { CopilotGuide } from './types';

export const COPILOT_GUIDES: CopilotGuide[] = [
  {
    id: 'components',
    name: 'Components',
    description: 'Learn to create and manage reusable components for your quotes.',
    steps: [
      {
        id: 'components-nav',
        target: '[data-copilot="nav-components"]',
        title: 'Components Page',
        description: 'This is where you manage all your reusable components like materials, labour items, and extras — anything that appears in your quotes. Click "Components" to get started.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'components-add',
        target: '[data-copilot="add-component"]',
        title: 'Add a Component',
        description: 'Click "+ Add Component" to create your first component. Components are the building blocks of every quote — things like roofing iron, tiles, underlay, flashings, etc.',
        position: 'bottom',
        page: '/components',
        validation: 'click',
        validationTarget: '[data-copilot="component-name"]',
        nudgeText: 'Please click + Add Component to continue.',
      },
      {
        id: 'components-name',
        target: '[data-copilot="component-name"]',
        title: 'Component Name',
        description: 'Name the component something recognizable. For example: "Roofing Iron", "Building Paper", "Ridge Cap". This name will be used in multiple phases, but can be edited anytime.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-type',
        target: '[data-copilot="component-type"]',
        title: 'Component Type',
        description: 'Choose "Main Component" for primary materials (roofing iron, underlay, flashings) or "Extra" for additional items (clean up, sealant, delivery). Main components attach to defined roof areas, extras are standalone.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-measurement',
        target: '[data-copilot="component-measurement"]',
        title: 'Measurement Type',
        description: 'How is this component measured? Area (m²) for anything measured by square area, Linear (m) for flashings/gutters per length, Quantity for items like vents or downpipes, or Fixed for flat-rate items.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-material-rate',
        target: '[data-copilot="component-rates"]',
        title: 'Material Price',
        description: 'Set the price per unit for materials. For example, roofing iron might be $25/m². This rate auto-calculates material totals in your quotes based on measurements. Be sure to calculate for material cover.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-labour-rate',
        target: '[data-copilot="component-labour"]',
        title: 'Labour Rate',
        description: 'Set the labour rate per unit. For example, $15/m² or $10/Lm for installation. This is calculated separately from materials so you can track costs and margins independently. It also allows you to create a \"labor only\" sheet later.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-waste',
        target: '[data-copilot="component-waste"]',
        title: 'Waste Allowance',
        description: 'Add a waste factor to account for cuts and off-cuts. Percentage (e.g., 5–10%) or per length (e.g., 0.25m). This automatically adds extra material to your quotes — so you never under-quote/order.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-waste-amount',
        target: '[data-copilot="component-waste-amount"]',
        title: 'Waste Amount',
        description: 'Enter the waste value. For percentage, enter a number like 10 (for 10%). For fixed, enter the extra lineal length (m) to add.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-pitch-toggle',
        target: '[data-copilot="component-pitch"]',
        title: 'Pitch Calculation',
        description: 'Enable this if the component quantity is affected by roof pitch and your measurement is not actual, it\'s from a plan. When enabled, measurements are automatically adjusted using the pitch angle — steeper roofs need more material.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-pitch-type',
        target: '[data-copilot="component-pitch-type"]',
        title: 'Pitch Type',
        description: 'Rafter Pitch: For materials that follow the roof slope (iron, shingles, underlay). Hip/Valley Pitch: For materials along hip or valley lines (hip flashings, valley flashings).',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-flashings',
        target: '[data-copilot="component-flashings"]',
        title: 'Assign Flashings',
        description: 'Link flashing drawings to this component. When you create a material order, the flashing design will appear next to this item — this speeds up the ordering stage.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-save',
        target: '[data-copilot="component-save"]',
        title: 'Save Your Component',
        description: 'Click "Create" to save this component to your library. Once saved, you can use it when creating quotes — it will appear as an option to add to any roof area.',
        position: 'top',
        page: '/components',
        validation: 'none',
      },
    ],
  },
  {
    id: 'quotes',
    name: 'Create a Quote',
    description: 'Learn to create and manage roofing quotes from start to finish.',
    steps: [
      {
        id: 'quotes-nav',
        target: '[data-copilot="nav-quotes"]',
        title: 'Quotes Page',
        description: 'This is your quotes hub — where you create, track, and manage all your roofing quotes. Click "Quotes" to get started.',
        position: 'bottom',
      },
      {
        id: 'quotes-new',
        target: '[data-copilot="new-quote"]',
        title: 'Create a New Quote',
        description: 'Click "+ New Quote" to start a fresh quote. You\'ll enter the customer name, job reference, and optionally upload a roof plan for digital takeoff.',
        position: 'bottom',
        page: '/quotes',
      },
      {
        id: 'quotes-customer',
        target: '[data-copilot="quote-customer"]',
        title: 'Customer Details',
        description: 'Enter the customer\'s name and a job reference. The job reference helps you identify this quote later — use something like the address or project name.',
        position: 'right',
        page: '/quotes/new',
      },
      {
        id: 'quotes-template',
        target: '[data-copilot="quote-template"]',
        title: 'Choose a Template',
        description: 'Select a template to pre-load components, or start blank. Templates save time on repeat job types — you can create them in the Templates section.',
        position: 'right',
        page: '/quotes/new',
      },
      {
        id: 'quotes-entry-mode',
        target: '[data-copilot="quote-entry"]',
        title: 'Entry Mode',
        description: 'Choose "Manual" to enter measurements by hand, or "Digital Takeoff" to measure directly from an uploaded roof plan. Digital takeoff is faster for complex roofs.',
        position: 'right',
        page: '/quotes/new',
      },
      {
        id: 'quotes-status',
        target: '[data-copilot="quote-status"]',
        title: 'Track Quote Status',
        description: 'Each confirmed quote has a status you can update: Unsent → Sent → Accepted → and through to Finished. Click the status pill to change it as the job progresses.',
        position: 'left',
        page: '/quotes',
      },
    ],
  },
  {
    id: 'customer-labor',
    name: 'Customer Quotes & Labor Sheets',
    description: 'Learn to create professional customer-facing quotes and labor sheets.',
    steps: [
      {
        id: 'cl-summary',
        target: '[data-copilot="summary-tabs"]',
        title: 'Quote Documents',
        description: 'Each quote has three views: Summary (your internal costs), Customer Quote (what the client sees), and Labor Sheet (for subcontractors). Switch between them using these tabs.',
        position: 'bottom',
      },
      {
        id: 'cl-customer-tab',
        target: '[data-copilot="tab-customer"]',
        title: 'Customer Quote',
        description: 'Click "Customer Quote" to see what your client will receive. If you haven\'t created one yet, you\'ll see a prompt to create it.',
        position: 'bottom',
      },
      {
        id: 'cl-edit-customer',
        target: '[data-copilot="edit-customer"]',
        title: 'Edit Customer Quote',
        description: 'The editor lets you control exactly what the customer sees. Toggle items on/off, show/hide prices, edit descriptions, and add custom line items. Your margins are built in but hidden from the customer.',
        position: 'bottom',
      },
      {
        id: 'cl-send',
        target: '[data-copilot="send-quote"]',
        title: 'Send to Customer',
        description: 'Click "Send Quote" to generate an acceptance link. You can copy the URL directly or use an email template to send a professional message with the link embedded.',
        position: 'bottom',
      },
    ],
  },
  {
    id: 'flashings-orders',
    name: 'Flashings & Material Orders',
    description: 'Learn to draw flashings and create material orders.',
    steps: [
      {
        id: 'fo-flashings-nav',
        target: '[data-copilot="nav-components"]',
        title: 'Flashings Library',
        description: 'Flashings are accessible from the Components page. Click "Components" then the orange "Flashings" button to manage your flashing designs.',
        position: 'bottom',
      },
      {
        id: 'fo-draw',
        target: '[data-copilot="draw-flashing"]',
        title: 'Draw a Flashing',
        description: 'Click "Draw Flashing" to open the drawing tool. Use the Line tool to draw accurate flashing profiles with measurements and angles. The Pencil tool is great for freehand annotations.',
        position: 'bottom',
        page: '/flashings',
      },
      {
        id: 'fo-orders-nav',
        target: '[data-copilot="nav-orders"]',
        title: 'Material Orders',
        description: 'Navigate to Material Orders to create order forms for your suppliers. You can order from a quote (pre-populated) or create a custom order from scratch.',
        position: 'bottom',
      },
      {
        id: 'fo-order-create',
        target: '[data-copilot="order-custom"]',
        title: 'Create an Order',
        description: 'Choose "Custom Order" to start from scratch, or "Order from Quote" to pre-fill from an existing quote. Add your supplier details, items, and flashing drawings.',
        position: 'right',
        page: '/material-orders',
      },
    ],
  },
];
