import type { CopilotGuide } from './types';

export const COPILOT_GUIDES: CopilotGuide[] = [
  {
    id: 'components',
    name: 'Components',
    description: 'Learn to create and manage reusable components for your quotes.',
    steps: [
      {
        id: 'components-nav',
        target: '[data-copilot="nav-components"]',
        title: 'Components Page',
        description: 'This is where you manage all your reusable components like materials, labour items, and extras - anything that appears in your quotes. Click "Components" to get started.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'components-add',
        target: '[data-copilot="add-component"]',
        title: 'Add a Component',
        description: 'Click "+ Add Component" to create your first component. Components are the building blocks of every quote - things like _roofing iron, tiles, underlay, flashings,_ etc.',
        position: 'bottom',
        page: '/components',
        validation: 'click',
        validationTarget: '[data-copilot="component-name"]',
        nudgeText: 'Please click + Add Component to continue.',
      },
      {
        id: 'components-name',
        target: '[data-copilot="component-name"]',
        title: 'Component Name',
        description: 'Name the component something recognizable. For example: _Roofing Iron, Building Paper, Ridge Cap._ This name will be used in multiple phases, but can be edited anytime.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-type',
        target: '[data-copilot="component-type"]',
        title: 'Component Type',
        description: 'Choose "Main Component" for primary materials _(roofing iron, underlay, flashings)_ or "Extra" for additional items _(clean up, sealant, delivery)._. Main components attach to defined roof areas, extras are standalone.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-measurement',
        target: '[data-copilot="component-measurement"]',
        title: 'Measurement Type',
        description: 'How is this component measured? _Area_ (m\u00B2) for anything measured by square area, _Linear_ (m) for flashings/gutters per length, _Quantity_ for items like vents or downpipes, or _Fixed_ for flat-rate items.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-material-rate',
        target: '[data-copilot="component-rates"]',
        title: 'Material Price',
        description: 'Set the price per unit for materials. For example, _roofing iron might be $25/m\u00B2. This rate auto-calculates material totals in your quotes based on measurements._ Be sure to calculate for material cover.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-labour-rate',
        target: '[data-copilot="component-labour"]',
        title: 'Labour Rate',
        description: 'Set the labour rate per unit. For example, _$15/m\u00B2 or $10/Lm for installation._ This is calculated separately from materials so you can track costs and margins independently. It also allows you to create a "labor only" sheet later.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-waste',
        target: '[data-copilot="component-waste"]',
        title: 'Waste Allowance',
        description: 'Add a waste factor to account for cuts and off-cuts. _Percentage (e.g., 5-10%)_ or _per length (e.g., 0.25m)._. This automatically adds extra material to your quotes - so you never under-quote/order.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-waste-amount',
        target: '[data-copilot="component-waste-amount"]',
        title: 'Waste Amount',
        description: 'Enter the waste value. For percentage, enter a number like _10 (for 10%)._. For fixed, enter the extra lineal length _(m)_ to add.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-pitch-toggle',
        target: '[data-copilot="component-pitch"]',
        title: 'Pitch Calculation',
        description: 'Enable this if the component quantity is affected by roof pitch and your measurement is not actual, it\'s from a plan. When enabled, measurements are automatically adjusted using the pitch angle - steeper roofs need more material.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-pitch-type',
        target: '[data-copilot="component-pitch-type"]',
        title: 'Pitch Type',
        description: '_Rafter Pitch:_ For materials that follow the roof slope _(iron, shingles, underlay)._. _Hip/Valley Pitch:_ For materials along hip or valley lines _(hip flashings, valley flashings)._.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-flashings',
        target: '[data-copilot="component-flashings"]',
        title: 'Assign Flashings',
        description: 'Link flashing drawings to this component. When you create a material order, the flashing design will appear next to this item - this speeds up the ordering stage.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-save',
        target: '[data-copilot="component-save"]',
        title: 'Save Your Component',
        description: 'Click "Create" to save this component to your library. Once saved, you can use it when creating quotes - it will appear as an option to add to any roof area.',
        position: 'top',
        page: '/components',
        validation: 'none',
      },
    ],
  },
  {
    id: 'create-quote',
    name: 'Create a Quote',
    description: 'Learn to set up a new quote with customer details and entry mode.',
    steps: [
      {
        id: 'cq-nav',
        target: '[data-copilot="nav-quotes"]',
        title: 'Quotes Page',
        description: 'This is your quotes hub - where you create, track, and manage all your quotes. Click "Quotes" to get started.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cq-new',
        target: '[data-copilot="new-quote"]',
        title: 'Create a New Quote',
        description: 'Click "+ New Quote" to start creating a quote. You will enter the customer name, job details, and choose how you want to build the quote.',
        position: 'bottom',
        page: '/quotes',
        validation: 'none',
      },
      {
        id: 'cq-customer',
        target: '[data-copilot="quote-customer"]',
        title: 'Customer Name',
        description: 'Enter the customer or company name for this quote. For example: _John Smith, ABC Builders._ This will appear on all documents for this job. You can change this later too.',
        position: 'right',
        page: '/quotes/new',
        validation: 'input',
      },
      {
        id: 'cq-job',
        target: '[data-copilot="quote-job"]',
        title: 'Job Reference',
        description: 'Add a job name or reference to help identify this quote later. For example: _Residential Re-roof, 123 Main St._ This is optional but very helpful when you have multiple quotes.',
        position: 'right',
        page: '/quotes/new',
        validation: 'none',
      },
      {
        id: 'cq-template',
        target: '[data-copilot="quote-template"]',
        title: 'Choose a Template',
        description: 'Templates can help save time with repetition, they can only be used for manual mode, you can create templates from the templates page.',
        position: 'right',
        page: '/quotes/new',
        validation: 'none',
      },
      {
        id: 'cq-entry-mode',
        target: '[data-copilot="quote-entry"]',
        title: 'Entry Mode',
        description: 'Choose how to build this quote. _Manual Mode_ - enter measurements manually from an existing roof takeoff. _Digital Mode_ - upload a roof plan and measure directly on screen. For this guide, select _Manual Mode._ To learn digital takeoff with Copilot, select Digital Mode, upload your roof plan, then turn Copilot on when you arrive at the takeoff station.',
        position: 'bottom',
        page: '/quotes/new',
        validation: 'none',
      },
      {
        id: 'cq-create-btn',
        target: '[data-copilot="quote-create"]',
        title: 'Create the Quote',
        description: 'Click "Create Quote" to start the Quote Builder stage where you can add roof areas and assign components.',
        position: 'right',
        page: '/quotes/new',
        validation: 'none',
      },
    ],
  },
  {
    id: 'quote-builder',
    name: 'Quote Builder',
    description: 'Learn to add roof areas, set measurements, and assign components.',
    steps: [
      {
        id: 'qb-add-area',
        target: '[data-copilot="quote-add-area-row"]',
        title: 'Add a Roof Area',
        description: 'Type a name for your first roof area - for example: _Main Roof, Garage, Extension_ - then click the Add Roof Area button. You can add more areas later if needed.',
        position: 'bottom',
        validation: 'click',
        validationTarget: '[data-copilot="quote-pitch"]',
        nudgeText: 'Type a roof area name and click "Add Roof Area" first.',
      },
      {
        id: 'qb-pitch',
        target: '[data-copilot="quote-pitch"]',
        title: 'Roof Pitch',
        description: 'Enter the roof pitch in degrees. This is the angle of the roof slope - adding the pitch here helps the program auto calculate true lengths and areas based on the pitch calculation.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-add-measurement',
        target: '[data-copilot="quote-add-measurement"]',
        title: 'Add an Area Measurement',
        description: 'Click "+ Add area measurement" to enter the dimensions of this roof area. You will need to enter a width and length for this roof area, then click "Add". This calculates the total area for quantities.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'qb-measurement-inputs',
        target: '[data-copilot="quote-measurement-inputs"]',
        title: 'Enter Dimensions',
        description: 'Enter the width and length of the roof area, then click "Add". For example: _10 x 5 for a 50m\u00B2 area._ You can add multiple measurements if the roof area has different sections.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'qb-confirm-area',
        target: '[data-copilot="quote-confirm-area"]',
        title: 'Confirm the Roof Area',
        description: 'Click "Confirm" to lock this roof area. Once confirmed, the measurements are set and you can move on to adding components. You can still edit it later.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'qb-next-components',
        target: '[data-copilot="quote-next-components"]',
        title: 'Move to Components',
        description: 'Click "Next: Components" to start assigning materials. _Tip: outside of Copilot, you can go back and add more roof areas anytime._',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-select-component',
        target: '[data-copilot="quote-add-from-library"]',
        title: 'Select a Component',
        description: 'Use the dropdown to choose a component from your library - for example: _Tiles, Underlay, Flashings._ Each component will calculate quantities based on your roof area measurements and pitch.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-click-add-component',
        target: '[data-copilot="quote-add-from-library-add-btn"]',
        title: 'Add the Component',
        description: 'Click the "+" button to add the selected component to this roof area.',
        position: 'left',
        validation: 'none',
        validationTarget: '[data-copilot="quote-first-component"]',
      },
      {
        id: 'qb-expand-component',
        target: '[data-copilot="quote-first-component"]',
        title: 'Expand the Component',
        description: 'Click the arrow on a component to expand it. Inside, you can add individual lengths/areas, or quantities depending on the component type. You can also link it to a roof area to auto-calculate from your measurements.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-next-extras',
        target: '[data-copilot="quote-next-extras"]',
        title: 'Move to Extras',
        description: 'Once you have added components to your areas, click "Next: Extras" to add any additional items that are not tied to a specific roof area - for example: _scaffolding, skip hire, travel costs._',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-extras',
        target: '[data-copilot="quote-extras-phase"]',
        title: 'Add Extras',
        description: 'Extras are items that apply to the whole job, not a specific roof area. Add any additional costs here using the library dropdown. _This section is optional - click Next: Review if you have no extras._',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'qb-next-review',
        target: '[data-copilot="quote-next-review"]',
        title: 'Move to Review',
        description: 'Click "Next: Review" to see a full summary of your quote before confirming. You can still go back and edit items after confirming.',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'qb-margins',
        target: '[data-copilot="quote-margins"]',
        title: 'Profit Margins',
        description: 'Here you can add a percentage amounts for material and labour margin. You can edit this later again. _This step is optional - you can skip it and come back later._',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'qb-confirm',
        target: '[data-copilot="quote-confirm"]',
        title: 'Confirm Your Quote',
        description: 'Review all your areas, components, and totals. When everything looks right, click "Confirm Quote" to lock the quote and move to the summary page where you can generate documents, create customer quotes from this master quote and more.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'customer-labor',
    name: 'Customer Quotes & Labor Sheets',
    description: 'Learn to create professional customer-facing quotes and send them to clients.',
    steps: [
      {
        id: 'cl-summary',
        target: '[data-copilot="summary-tabs"]',
        title: 'Quote Summary',
        description: 'After confirming your quote, you land on the summary page. This shows your internal costs and has three tabs: Summary, Customer Quote, and Labor Sheet.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-customer-tab',
        target: '[data-copilot="tab-customer"]',
        title: 'Customer Quote Tab',
        description: 'Click the Customer Quote tab to see what your client will receive. If you have not created one yet, you will see a prompt to create it.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-create-edit',
        target: '[data-copilot="create-customer-quote"]',
        title: 'Create Customer Quote',
        description: 'Click to create your customer quote. This will open the editor where you can customise exactly what the customer sees.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-template',
        target: '[data-copilot="cl-template-dropdown"]',
        title: 'Quote Template',
        description: 'You can select a premade customer quote template for the quote header here if you wish, or you can edit it as desired from the right side panel.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-left-panel',
        target: '[data-copilot="cl-left-panel"]',
        title: 'Component Controls',
        description: 'You can hide/show description or price, include price in customer quote or not from this left panel using the buttons. You can also create entirely new custom items that will react the same.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'cl-right-panel',
        target: '[data-copilot="cl-right-panel"]',
        title: 'Edit Details',
        description: 'You can manually edit the component name, description, area/lengths/quantity and price from the right side column. Just click the pencil icon next to the line you want to edit.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'cl-save-hint',
        target: '[data-copilot="cl-save-return"]',
        title: 'Save and Return',
        description: 'Between the 2 columns you can completely change every aspect of the quote. Make sure you save everything and return to the summary page.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'cl-preview-tab',
        target: '[data-copilot="tab-customer"]',
        title: 'Preview Customer Quote',
        description: 'Now you can preview your customer quote to see what your customer will see. Click the Customer Quote tab.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-edit-icon',
        target: '[data-copilot="edit-customer-icon"]',
        title: 'Edit Again',
        description: 'If you want to make more changes, simply click the edit icon here.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'cl-go-summary',
        target: '[data-copilot="tab-summary"]',
        title: 'Back to Summary',
        description: 'If you are happy with the customer quote, now you can send the quote to your customer. Click the Summary tab.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-send-btn',
        target: '[data-copilot="send-quote"]',
        title: 'Send Quote',
        description: 'Click "Send Quote" to open the sending options.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-copy-url',
        target: '[data-copilot="cl-copy-url-option"]',
        title: 'Copy URL Link',
        description: 'Here you can select "Copy URL Link" to generate a link your customer can click to see the quote and accept or decline it, or you can click "Generate Email". Click "Copy URL Link".',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-url-view',
        target: '[data-copilot="cl-url-mode"]',
        title: 'Share the Link',
        description: 'Simply copy this URL link and send it to your client via email or message so they can view the quote and accept or decline it. Now go "Back to options".',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-gen-email',
        target: '[data-copilot="cl-email-option"]',
        title: 'Generate Email',
        description: 'Now click "Generate Email".',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-email-view',
        target: '[data-copilot="cl-email-mode"]',
        title: 'Email Template',
        description: 'Here you can create an email that includes the URL link that you can copy and paste into your desired email client (Gmail, Outlook etc). You can also use a premade email template to auto fill the email with your desired content and structure to save time. Now click "Back to options".',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'cl-final',
        target: '[data-copilot="cl-send-modal"]',
        title: 'Test It Out',
        description: 'You can test the generated URL link - copy and paste it into your browser. You will see exactly what your customer sees, and you can even accept or decline the quote to see what happens. You will get an alert notification, and the status of your quote will automatically update on the main quotes page. Click the Customer Quote tab anytime to download the PDF, edit, or preview it.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'labor-sheet',
    name: 'Labor Sheet',
    description: 'Learn to create labor-only breakdowns for subcontractors.',
    steps: [
      {
        id: 'ls-tab',
        target: '[data-copilot="tab-labor"]',
        title: 'Labor Sheet Tab',
        description: 'Click the Labor Sheet tab to get started.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-create',
        target: '[data-copilot="create-labor-sheet"]',
        title: 'Create Labor Sheet',
        description: 'Click to create your labor sheet. This will open the editor where you can customise the labor-only breakdown for subcontractors.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-template',
        target: '[data-copilot="cl-template-dropdown"]',
        title: 'Template',
        description: 'Just like the customer quote, you can select a premade template for the header, or edit it from the right side panel.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-left-panel',
        target: '[data-copilot="cl-left-panel"]',
        title: 'Component Controls',
        description: 'Use these controls to hide/show items, toggle prices, and add custom line items. The labor sheet only shows labour costs - no material pricing.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'ls-right-panel',
        target: '[data-copilot="cl-right-panel"]',
        title: 'Edit Details',
        description: 'Edit the component name, description, quantities and labour rates from this panel. Click the pencil icon next to the line you want to edit.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'ls-save',
        target: '[data-copilot="cl-save-return"]',
        title: 'Save and Return',
        description: 'Make sure you save everything and return to the summary page.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'ls-preview-tab',
        target: '[data-copilot="tab-labor"]',
        title: 'Preview Labor Sheet',
        description: 'Now preview your labor sheet. Click the Labor Sheet tab to see what it looks like.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-edit-icon',
        target: '[data-copilot="edit-labor-icon"]',
        title: 'Edit Again',
        description: 'If you want to make more changes, click the edit icon here.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'ls-back-summary',
        target: '[data-copilot="tab-summary"]',
        title: 'Back to Summary',
        description: 'Click the Summary tab when you are done.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-final',
        target: '[data-copilot="summary-tabs"]',
        title: 'All Done',
        description: 'The labor sheet is designed for subcontractors - it shows labor costs only, keeping your material pricing private. Click the Labor Sheet tab anytime to download the PDF, edit, or preview it.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'digital-quote-builder',
    name: 'Digital Quote Builder',
    description: 'Review and edit your digital takeoff in the quote builder.',
    steps: [
      {
        id: 'dqb-areas',
        target: '[data-copilot="quote-next-components"]',
        title: 'Roof Areas',
        description: 'Your roof areas and components from the digital takeoff are pre-populated here. You can add more areas manually, edit existing ones, or go straight to Components if everything looks right.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-components',
        target: '[data-copilot="quote-next-components"]',
        title: 'Components',
        description: 'Click "Next: Components" to assign materials. Components measured in the takeoff will already have their quantities. You can add more from your library or adjust any values.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-extras',
        target: '[data-copilot="quote-next-extras"]',
        title: 'Extras',
        description: 'Click "Next: Extras" to add any additional items not tied to a specific roof area - scaffolding, skip hire, travel costs etc. This section is optional.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-review',
        target: '[data-copilot="quote-next-review"]',
        title: 'Review',
        description: 'Click "Next: Review" to see your full quote summary. You can set profit margins and review all totals before confirming.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-confirm',
        target: '[data-copilot="quote-confirm"]',
        title: 'Confirm Your Quote',
        description: 'When everything looks right, click "Confirm Quote" to lock the quote and move to the summary page where you can generate customer documents.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'digital-takeoff',
    name: 'Digital Takeoff',
    description: 'Learn to measure roof plans digitally using the takeoff workstation.',
    steps: [
      {
        id: 'dt-more-areas',
        target: '[data-copilot="takeoff-toolbar"]',
        title: 'Roof Areas',
        description: 'You can also add multiple roof areas, like garage, lower roof, flat roof (different pitch roofs). Add them now before adding components if you need them, use the area tool, or manually add them in the quote builder phase.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-area-hint',
        target: '[data-copilot="takeoff-toolbar"]',
        title: 'Area Components',
        description: 'Any components defined by the roof area you just created do not need to be redrawn or added in this stage. It is faster to add those components in the Components phase of the Quote Builder (after the digital takeoff phase), there, you can auto add based on your roof areas defined here.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-sidebar',
        target: '[data-copilot="takeoff-sidebar"]',
        title: 'Components Panel',
        description: 'This is your component panel. Click the "+" icon next to a component to add it to the active list. Components need to be active and assigned a colour before you can measure for them.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'dt-tool-calibrate',
        target: '[data-copilot="takeoff-tool-calibrate"]',
        title: 'Calibrate',
        description: 'You have already calibrated the plan. You can recalibrate anytime if needed by clicking this button.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-tool-area',
        target: '[data-copilot="takeoff-tool-area"]',
        title: 'Area Tool',
        description: 'You already used this to create your roof area. You can also use it to measure area for a specific component - just select the component first, then trace the area.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-tool-line',
        target: '[data-copilot="takeoff-tool-line"]',
        title: 'Line Tool',
        description: 'Use the Line tool to measure linear components like flashings, gutters, and ridges. Select a component first, then click two points to measure the length. The measurement is automatically assigned to the selected component.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-line-hint',
        target: '[data-copilot="takeoff-tool-line"]',
        title: 'Line Measurements',
        description: 'You can add multiple measurements for each component if you want. Always measure the individual lengths to allow for waste calculation and full editing ability in later stages.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-tool-point',
        target: '[data-copilot="takeoff-tool-point"]',
        title: 'Point Tool',
        description: 'Use the Point tool for quantity-based items like vents, downpipes, or brackets. Select a component, then click on the plan to place a marker. Each click adds one to the count.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-measure-hint',
        target: '[data-copilot="takeoff-toolbar"]',
        title: 'Start Measuring',
        description: 'Make sure you select the correct measuring tool for each component. Measure the lengths, areas, or locations for each component, then select the next component. When you are finished, click "Save & Continue to Components" to move to the Quote Builder.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-save',
        target: '[data-copilot="takeoff-save"]',
        title: 'Save & Continue',
        description: 'When you have finished measuring all your components, click "Save & Continue to Components" to save your takeoff and move to the Quote Builder. Your roof areas and component measurements will be pre-populated.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'flashing-draw',
    name: 'Flashing Drawing',
    description: 'Learn to draw accurate flashing profiles with measurements.',
    steps: [
      {
        id: 'fd-inputs',
        target: '[data-copilot="flashing-inputs"]',
        title: 'Name Your Flashing',
        description: 'Enter a name for your flashing - for example: _Custom Ridge Cap, Barge Flashing._ You can also add a description and choose a canvas size.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-line',
        target: '[data-copilot="flashing-tool-line"]',
        title: 'Line Tool',
        description: 'The Line tool is your main drawing tool. Click to place points and draw straight lines with automatic length and angle measurements. Click "Finish Line" or press Escape to stop drawing.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-text',
        target: '[data-copilot="flashing-tool-text"]',
        title: 'Text Tool',
        description: 'Use the Text tool to add labels or annotations anywhere on the canvas. Click where you want to place text.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-pencil',
        target: '[data-copilot="flashing-tool-pencil"]',
        title: 'Pencil Tool',
        description: 'The Pencil tool lets you freehand draw for quick annotations, sketches, or markup. You can choose between 3 thicknesses.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-edit',
        target: '[data-copilot="flashing-tool-edit"]',
        title: 'Edit Tool',
        description: 'The Edit tool lets you select, move, and resize any element on the canvas. Click on a line, text, or drawing to select it.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-adjust',
        target: '[data-copilot="flashing-tool-adjust"]',
        title: 'Adjust Points',
        description: 'Adjust Points lets you fine-tune individual line points after drawing. Drag any point to reposition it - all connected measurements update automatically.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-measurements',
        target: '[data-copilot="flashing-measurements"]',
        title: 'Measurements Panel',
        description: 'All your measurements appear here. Click a measurement to select it on the canvas. You can edit values, toggle visibility, or delete measurements.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'fd-live-readout',
        target: '[data-copilot="flashing-live-readout"]',
        title: 'Live Readout',
        description: 'As you draw, the live readout shows the current length and angle in real time. This helps you draw accurately to scale.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-save',
        target: '[data-copilot="flashing-save"]',
        title: 'Save Flashing',
        description: 'When you are finished, click Save Flashing. Your drawing will be saved to your flashings library and can be linked to components for material orders.',
        position: 'top',
        validation: 'none',
      },
    ],
  },
  {
    id: 'account-settings',
    name: 'Account Settings',
    description: 'Manage your company, preferences, and security.',
    steps: [
      {
        id: 'as-company',
        target: '[data-copilot="settings-company"]',
        title: 'Company & Preferences',
        description: 'Set your company name, display name, default currency, measurement system, and language. You can also set default profit margins that apply to all new quotes.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'as-security',
        target: '[data-copilot="settings-security"]',
        title: 'Security',
        description: 'Manage your password here. If you signed in with Google, you can add a password for email login. Two-factor authentication is coming soon.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'as-billing',
        target: '[data-copilot="settings-billing"]',
        title: 'Billing & Subscription',
        description: 'You are currently on the Free Beta plan. Subscription plans and billing options will be available soon.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'as-links',
        target: '[data-copilot="settings-links"]',
        title: 'Quick Links',
        description: 'Quick access to Email Templates, Quote Templates, Flashings, and Components. These shortcuts take you directly to each section.',
        position: 'top',
        validation: 'none',
      },
    ],
  },
  {
    id: 'flashings-orders',
    name: 'Flashings Library',
    description: 'Manage your flashing designs.',
    steps: [
      {
        id: 'fo-draw',
        target: '[data-copilot="draw-flashing"]',
        title: 'Draw a Flashing',
        description: 'Click "Draw Flashing" to open the drawing tool where you can create accurate flashing profiles with measurements and angles.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'material-orders-hub',
    name: 'Material Orders',
    description: 'Learn to create material orders for your suppliers.',
    steps: [
      {
        id: 'moh-overview',
        target: '[data-copilot="mo-action-cards"]',
        title: 'Material Orders',
        description: 'This is your Material Orders hub. You can create a custom order from scratch, create an order from a confirmed quote with pre-populated components, or manage supplier templates.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moh-custom',
        target: '[data-copilot="mo-custom-order"]',
        title: 'Custom Order',
        description: 'Click Custom Order to start a blank order form. You will enter supplier details and add items manually.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moh-from-quote',
        target: '[data-copilot="mo-order-from-quote"]',
        title: 'Order from Quote',
        description: 'Click Order from Quote to pre-populate with components from a confirmed quote. This saves time as all materials and quantities are pulled in automatically.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'material-order-create',
    name: 'Create Material Order',
    description: 'Learn to build and customise a material order.',
    steps: [
      {
        id: 'moc-template',
        target: '[data-copilot="mo-template"]',
        title: 'Supplier Template',
        description: 'You can select a saved supplier template to auto-fill supplier details, or enter them manually below.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moc-header',
        target: '[data-copilot="mo-header-form"]',
        title: 'Supplier & Company Details',
        description: 'Enter the supplier name, reference, order type, colours, delivery date, and address on the left. Your company details appear on the right.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moc-minimize',
        target: '[data-copilot="mo-minimize-header"]',
        title: 'Minimize Header',
        description: 'Click "Minimize Header" to collapse the supplier details and see more of your order. You can expand it again anytime by clicking "Edit Header".',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'moc-layout',
        target: '[data-copilot="mo-layout-toggle"]',
        title: 'Layout Mode',
        description: 'Choose Single Column for a standard list view, or Double Column to fit more items side by side on the printed order. You can switch between them anytime.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moc-sidebar',
        target: '[data-copilot="mo-sidebar"]',
        title: 'Order Components',
        description: 'This panel controls what appears in your order. Click "+ Add Component" to add items. Each component can include a description, quantities, measurements, and a linked flashing drawing.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'moc-visibility',
        target: '[data-copilot="mo-sidebar"]',
        title: 'Show & Hide Elements',
        description: 'For each component, you can show or hide the name, flashing drawing, and measurements using the checkboxes. This lets you fully customise what appears on the printed order for each item.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'moc-save',
        target: '[data-copilot="mo-save"]',
        title: 'Save Order',
        description: 'When you are finished, click Save Order. You can preview and print the order, or come back and edit it later from the Material Orders page.',
        position: 'left',
        validation: 'none',
      },
    ],
  },
];
