import type { CopilotGuide } from './types';

export const COPILOT_GUIDES_GENERIC: CopilotGuide[] = [
  {
    id: 'components',
    name: 'Components',
    description: 'Learn to create and manage reusable components for your quotes.',
    steps: [
      {
        id: 'components-nav',
        target: '[data-copilot="resources-card-components"]',
        title: 'Components',
        description: 'Components are your reusable materials, labour items, and extras - anything that appears in your quotes. Open the _Resources_ menu and click the _"Components"_ card to manage them.',
        position: 'bottom',
        page: '/resources',
        validation: 'none',
      },
      {
        id: 'components-add',
        target: '[data-copilot="add-component"]',
        title: 'Add a Component',
        description: 'Click "+ Add Component" to create your first component. Components are the building blocks of every quote - things like _materials (timber/paint), fixings/hardware, labor,_ etc.',
        position: 'bottom',
        page: '/components',
        validation: 'click',
        validationTarget: '[data-copilot="component-name"]',
        nudgeText: 'Please click + Add Component to continue.',
      },
      {
        id: 'components-name',
        target: '[data-copilot="component-name"]',
        title: 'Component Name',
        description: 'Name the component something recognizable. For example: _Waste Pipe, Electrical Switchboard, Decking Timber._ This name will be used in multiple phases, but can be edited anytime.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-type',
        target: '[data-copilot="component-type"]',
        title: 'Component Type',
        description: 'Choose "Main Component" for primary materials _(cladding, lining, trims)_ or "Extra" for additional items _(clean up, sealant, delivery)._. Main components attach to defined areas, extras are standalone.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-measurement',
        target: '[data-copilot="component-measurement"]',
        title: 'Measurement Type',
        description: 'How is this component measured? _Area_ (m\u00B2) for anything measured by square area, _Linear_ (m) for trims, gutters, or edging per length, _Quantity_ for items like fixings or fittings, or _Fixed_ for flat-rate items.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-material-rate',
        target: '[data-copilot="component-rates"]',
        title: 'Material Price',
        description: 'Set the price per unit for materials. For example, _wall cladding might be $25/m\u00B2. This rate auto-calculates material totals in your quotes based on measurements._ Be sure to calculate for material cover.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-labour-rate',
        target: '[data-copilot="component-labour"]',
        title: 'Labour Rate',
        description: 'Set the labour rate per unit. For example, _$15/m\u00B2 or $10/Lm for installation._ This is calculated separately from materials so you can track costs and margins independently. It also allows you to create a "labor only" sheet later.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-waste',
        target: '[data-copilot="component-waste"]',
        title: 'Waste Allowance',
        description: 'Add a waste factor to account for cuts and off-cuts. _Percentage (e.g., 5-10%)_ or _per length (e.g., 0.25m)._. This automatically adds extra material to your quotes - so you never under-quote/order.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-waste-amount',
        target: '[data-copilot="component-waste-amount"]',
        title: 'Waste Amount',
        description: 'Enter the waste value. For percentage, enter a number like _10 (for 10%)._. For fixed, enter the extra lineal length _(m)_ to add.',
        position: 'right',
        page: '/components',
        validation: 'input',
      },
      {
        id: 'components-pitch-toggle',
        target: '[data-copilot="component-pitch"]',
        title: 'Slope/Angle Calculation',
        description: 'Enable this only if your measurements come from a plan and the surface has an angle or slope that affects material quantity. If you measure on-site, or your surfaces are flat, leave this off.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-flashings',
        target: '[data-copilot="component-flashings"]',
        title: 'Assign Drawings & Images',
        description: 'Link drawings or images to this component. When you create a material order, they will appear next to this item - this speeds up the ordering stage.',
        position: 'right',
        page: '/components',
        validation: 'none',
      },
      {
        id: 'components-save',
        target: '[data-copilot="component-save"]',
        title: 'Save Your Component',
        description: 'Click "Create" to save this component to your library. Once saved, you can use it when creating quotes - it will appear as an option to add to any area.',
        position: 'top',
        page: '/components',
        validation: 'none',
      },
    ],
  },
  {
    id: 'create-quote',
    name: 'Create a Quote',
    description: 'Learn to set up a new quote with customer details and entry mode.',
    steps: [
      {
        id: 'cq-nav',
        target: '[data-copilot="nav-quotes"]',
        title: 'Quotes Page',
        description: 'This is your quotes hub - where you create, track, and manage all your quotes. Click "Quotes" to get started.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cq-new',
        target: '[data-copilot="new-quote"]',
        title: 'Create a New Quote',
        description: 'Click "+ New Quote" to start creating a quote. You will enter the customer name, job details, and choose how you want to build the quote.',
        position: 'bottom',
        page: '/quotes',
        validation: 'none',
      },
      {
        id: 'cq-customer',
        target: '[data-copilot="quote-customer"]',
        title: 'Customer Name',
        description: 'Enter the customer or company name for this quote. For example: _John Smith, ABC Builders._ This will appear on all documents for this job. You can change this later too.',
        position: 'right',
        page: '/quotes/new',
        validation: 'input',
      },
      {
        id: 'cq-job',
        target: '[data-copilot="quote-job"]',
        title: 'Job Reference',
        description: 'Add a job name or reference to help identify this quote later. For example: _Residential Cladding, 123 Main St._ This is optional but very helpful when you have multiple quotes.',
        position: 'right',
        page: '/quotes/new',
        validation: 'none',
      },
      {
        id: 'cq-template',
        target: '[data-copilot="quote-template"]',
        title: 'Choose a Template',
        description: 'Templates can help save time with repetition, they can only be used for manual mode, you can create templates from the templates page.',
        position: 'right',
        page: '/quotes/new',
        validation: 'none',
      },
      {
        id: 'cq-entry-mode',
        target: '[data-copilot="quote-entry"]',
        title: 'Entry Mode',
        description: 'Choose how to build this quote. _Manual Mode_ - enter measurements manually from an existing takeoff. _Digital Mode_ - upload a plan and measure directly on screen. For this guide, select _Manual Mode._ To learn digital takeoff with Copilot, select Digital Mode, upload your plan, then turn Copilot on when you arrive at the takeoff station.',
        position: 'bottom',
        page: '/quotes/new',
        validation: 'none',
      },
      {
        id: 'cq-create-btn',
        target: '[data-copilot="quote-create"]',
        title: 'Create the Quote',
        description: 'Click "Create Quote" to start the Quote Builder stage where you can add areas and assign components.',
        position: 'right',
        page: '/quotes/new',
        validation: 'none',
      },
    ],
  },
  {
    id: 'quote-builder',
    name: 'Quote Builder',
    description: 'Learn to add areas, set measurements, and assign components.',
    steps: [
      {
        id: 'qb-add-area',
        target: '[data-copilot="quote-add-area-row"]',
        title: 'Add an Area',
        description: 'Type a name for your first area - for example: _Main Wall, Garage, Extension_ - then click the Add Area button. You can add more areas later if needed.',
        position: 'bottom',
        validation: 'click',
        validationTarget: '[data-copilot="quote-pitch"]',
        nudgeText: 'Type an area name and click "Add Area" first.',
      },
      {
        id: 'qb-pitch',
        target: '[data-copilot="quote-pitch"]',
        title: 'Slope / Angle',
        description: 'Enter the surface angle in degrees if applicable. Adding the angle here helps the program auto-calculate true lengths and areas - useful when measuring from a plan rather than the actual surface. If your surfaces are flat or you are measuring on-site, leave this as 0.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-add-measurement',
        target: '[data-copilot="quote-add-measurement"]',
        title: 'Add an Area Measurement',
        description: 'Click "+ Add area measurement" to enter the dimensions of this area. You will need to enter a width and length, then click "Add". This calculates the total area for quantities.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'qb-measurement-inputs',
        target: '[data-copilot="quote-measurement-inputs"]',
        title: 'Enter Dimensions',
        description: 'Enter the width and length of the area, then click "Add". For example: _10 x 5 for a 50m\u00B2 area._ You can add multiple measurements if the area has different sections.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'qb-confirm-area',
        target: '[data-copilot="quote-confirm-area"]',
        title: 'Confirm the Area',
        description: 'Click "Confirm" to lock this area. Once confirmed, the measurements are set and you can move on to adding components. You can still edit it later.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'qb-next-components',
        target: '[data-copilot="quote-next-components"]',
        title: 'Move to Components',
        description: 'Click "Next: Components" to start assigning materials. _Tip: outside of Copilot, you can go back and add more areas anytime._',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-select-component',
        target: '[data-copilot="quote-add-from-library"]',
        title: 'Select a Component',
        description: 'Use the dropdown to choose a component from your library - for example: _Decking Timber, Wall Lining, Labor._ Each component will calculate quantities based on your area measurements.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-click-add-component',
        target: '[data-copilot="quote-add-from-library-add-btn"]',
        title: 'Add the Component',
        description: 'Click the "+" button to add the selected component to this area.',
        position: 'left',
        validation: 'none',
        validationTarget: '[data-copilot="quote-first-component"]',
      },
      {
        id: 'qb-expand-component',
        target: '[data-copilot="quote-first-component"]',
        title: 'Expand the Component',
        description: 'Click the arrow on a component to expand it. Inside, you can add individual lengths/areas, or quantities depending on the component type. You can also link it to an area to auto-calculate from your measurements.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-next-extras',
        target: '[data-copilot="quote-next-extras"]',
        title: 'Move to Extras',
        description: 'Once you have added components to your areas, click "Next: Extras" to add any additional items that are not tied to a specific area - for example: _scaffolding, skip hire, travel costs._',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'qb-extras',
        target: '[data-copilot="quote-extras-phase"]',
        title: 'Add Extras',
        description: 'Extras are items that apply to the whole job, not a specific area. Add any additional costs here using the library dropdown. _This section is optional - click Next: Review if you have no extras._',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'qb-next-review',
        target: '[data-copilot="quote-next-review"]',
        title: 'Move to Review',
        description: 'Click "Next: Review" to see a full summary of your quote before confirming. You can still go back and edit items after confirming.',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'qb-margins',
        target: '[data-copilot="quote-margins"]',
        title: 'Profit Margins',
        description: 'Here you can add a percentage amounts for material and labour margin. You can edit this later again. _This step is optional - you can skip it and come back later._',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'qb-confirm',
        target: '[data-copilot="quote-confirm"]',
        title: 'Confirm Your Quote',
        description: 'Review all your areas, components, and totals. When everything looks right, click "Confirm Quote" to lock the quote and move to the summary page where you can generate documents, create customer quotes from this master quote and more.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'customer-labor',
    name: 'Customer Quotes & Labor Sheets',
    description: 'Learn to create professional customer-facing quotes and send them to clients.',
    steps: [
      {
        id: 'cl-summary',
        target: '[data-copilot="summary-tabs"]',
        title: 'Quote Summary',
        description: 'After confirming your quote, you land on the summary page. This shows your internal costs and has three tabs: Summary, Customer Quote, and Labor Sheet.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-customer-tab',
        target: '[data-copilot="tab-customer"]',
        title: 'Customer Quote Tab',
        description: 'Click the Customer Quote tab to see what your client will receive. If you have not created one yet, you will see a prompt to create it.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-create-edit',
        target: '[data-copilot="create-customer-quote"]',
        title: 'Create Customer Quote',
        description: 'Click to create your customer quote. This will open the editor where you can customise exactly what the customer sees.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-template',
        target: '[data-copilot="cl-template-dropdown"]',
        title: 'Quote Template',
        description: 'You can select a premade customer quote template for the quote header here if you wish, or you can edit it as desired from the right side panel.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-left-panel',
        target: '[data-copilot="cl-left-panel"]',
        title: 'Component Controls',
        description: 'You can hide/show description or price, include price in customer quote or not from this left panel using the buttons. You can also create entirely new custom items that will react the same.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'cl-right-panel',
        target: '[data-copilot="cl-right-panel"]',
        title: 'Edit Details',
        description: 'You can manually edit the component name, description, area/lengths/quantity and price from the right side column. Just click the pencil icon next to the line you want to edit.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'cl-save-hint',
        target: '[data-copilot="cl-save-return"]',
        title: 'Save and Return',
        description: 'Between the 2 columns you can completely change every aspect of the quote. Make sure you save everything and return to the summary page.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'cl-preview-tab',
        target: '[data-copilot="tab-customer"]',
        title: 'Preview Customer Quote',
        description: 'Now you can preview your customer quote to see what your customer will see. Click the Customer Quote tab.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-edit-icon',
        target: '[data-copilot="edit-customer-icon"]',
        title: 'Edit Again',
        description: 'If you want to make more changes, simply click the edit icon here.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'cl-go-summary',
        target: '[data-copilot="tab-summary"]',
        title: 'Back to Summary',
        description: 'If you are happy with the customer quote, now you can send the quote to your customer. Click the Summary tab.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-send-btn',
        target: '[data-copilot="send-quote"]',
        title: 'Send Quote',
        description: 'Click "Send Quote" to open the sending options.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-copy-url',
        target: '[data-copilot="cl-copy-url-option"]',
        title: 'Copy URL Link',
        description: 'Here you can select "Copy URL Link" to generate a link your customer can click to see the quote and accept or decline it, or you can click "Generate Email". Click "Copy URL Link".',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-url-view',
        target: '[data-copilot="cl-url-mode"]',
        title: 'Share the Link',
        description: 'Simply copy this URL link and send it to your client via email or message so they can view the quote and accept or decline it. Now go "Back to options".',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-gen-email',
        target: '[data-copilot="cl-email-option"]',
        title: 'Generate Email',
        description: 'Now click "Generate Email".',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'cl-email-view',
        target: '[data-copilot="cl-email-mode"]',
        title: 'Email Template',
        description: 'Here you can create an email that includes the URL link that you can copy and paste into your desired email client (Gmail, Outlook etc). You can also use a premade email template to auto fill the email with your desired content and structure to save time. Now click "Back to options".',
        position: 'top',
        validation: 'none',
      },
      {
        id: 'cl-final',
        target: '[data-copilot="cl-send-modal"]',
        title: 'Test It Out',
        description: 'You can test the generated URL link - copy and paste it into your browser. You will see exactly what your customer sees, and you can even accept or decline the quote to see what happens. You will get an alert notification, and the status of your quote will automatically update on the main quotes page. Click the Customer Quote tab anytime to download the PDF, edit, or preview it.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'labor-sheet',
    name: 'Labor Sheet',
    description: 'Learn to create labor-only breakdowns for subcontractors.',
    steps: [
      {
        id: 'ls-tab',
        target: '[data-copilot="tab-labor"]',
        title: 'Labor Sheet Tab',
        description: 'Click the Labor Sheet tab to get started.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-create',
        target: '[data-copilot="create-labor-sheet"]',
        title: 'Create Labor Sheet',
        description: 'Click to create your labor sheet. This will open the editor where you can customise the labor-only breakdown for subcontractors.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-template',
        target: '[data-copilot="cl-template-dropdown"]',
        title: 'Template',
        description: 'Just like the customer quote, you can select a premade template for the header, or edit it from the right side panel.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-left-panel',
        target: '[data-copilot="cl-left-panel"]',
        title: 'Component Controls',
        description: 'Use these controls to hide/show items, toggle prices, and add custom line items. The labor sheet only shows labour costs - no material pricing.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'ls-right-panel',
        target: '[data-copilot="cl-right-panel"]',
        title: 'Edit Details',
        description: 'Edit the component name, description, quantities and labour rates from this panel. Click the pencil icon next to the line you want to edit.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'ls-save',
        target: '[data-copilot="cl-save-return"]',
        title: 'Save and Return',
        description: 'Make sure you save everything and return to the summary page.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'ls-preview-tab',
        target: '[data-copilot="tab-labor"]',
        title: 'Preview Labor Sheet',
        description: 'Now preview your labor sheet. Click the Labor Sheet tab to see what it looks like.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-edit-icon',
        target: '[data-copilot="edit-labor-icon"]',
        title: 'Edit Again',
        description: 'If you want to make more changes, click the edit icon here.',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'ls-back-summary',
        target: '[data-copilot="tab-summary"]',
        title: 'Back to Summary',
        description: 'Click the Summary tab when you are done.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ls-final',
        target: '[data-copilot="summary-tabs"]',
        title: 'All Done',
        description: 'The labor sheet is designed for subcontractors - it shows labor costs only, keeping your material pricing private. Click the Labor Sheet tab anytime to download the PDF, edit, or preview it.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'digital-quote-builder',
    name: 'Digital Quote Builder',
    description: 'Review and edit your digital takeoff in the quote builder.',
    steps: [
      {
        id: 'dqb-areas',
        target: '[data-copilot="quote-next-components"]',
        title: 'Areas',
        description: 'Your areas and components from the digital takeoff are pre-populated here. You can add more areas manually, edit existing ones, or go straight to Components if everything looks right.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-components',
        target: '[data-copilot="quote-next-components"]',
        title: 'Components',
        description: 'Click "Next: Components" to assign materials. Components measured in the takeoff will already have their quantities. You can add more from your library or adjust any values.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-extras',
        target: '[data-copilot="quote-next-extras"]',
        title: 'Extras',
        description: 'Click "Next: Extras" to add any additional items not tied to a specific area - scaffolding, skip hire, travel costs etc. This section is optional.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-review',
        target: '[data-copilot="quote-next-review"]',
        title: 'Review',
        description: 'Click "Next: Review" to see your full quote summary. You can set profit margins and review all totals before confirming.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dqb-confirm',
        target: '[data-copilot="quote-confirm"]',
        title: 'Confirm Your Quote',
        description: 'When everything looks right, click "Confirm Quote" to lock the quote and move to the summary page where you can generate customer documents.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'digital-takeoff',
    name: 'Digital Takeoff',
    description: 'Learn to measure plans digitally using the takeoff workstation.',
    steps: [
      {
        id: 'dt-more-areas',
        target: '[data-copilot="takeoff-toolbar"]',
        title: 'Areas',
        description: 'You can also add multiple areas - for example: Wall(s), Floor(s), Ceiling(s). Add them now before adding components if you need them, use the area tool, or manually add them in the quote builder phase.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-area-hint',
        target: '[data-copilot="takeoff-toolbar"]',
        title: 'Area Components',
        description: 'Any components defined by the area you just created do not need to be redrawn or added in this stage. It is faster to add those components in the Components phase of the Quote Builder (after the digital takeoff phase), there, you can auto add based on your areas defined here.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-sidebar',
        target: '[data-copilot="takeoff-sidebar"]',
        title: 'Components Panel',
        description: 'This is your component panel. Click the "+" icon next to a component to add it to the active list. Components need to be active and assigned a colour before you can measure for them.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'dt-tool-calibrate',
        target: '[data-copilot="takeoff-tool-calibrate"]',
        title: 'Calibrate',
        description: 'You have already calibrated the plan. You can recalibrate anytime if needed by clicking this button.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-tool-area',
        target: '[data-copilot="takeoff-tool-area"]',
        title: 'Area Tool',
        description: 'You already used this to create your area. You can also use it to measure area for a specific component - just select the component first, then trace the area.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-tool-line',
        target: '[data-copilot="takeoff-tool-line"]',
        title: 'Line Tool',
        description: 'Use the Line tool for linear measured point to point components like trims, cables/pipes, and edging. Select a component first, then click two points to measure the length. The measurement is automatically assigned to the selected component.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-line-hint',
        target: '[data-copilot="takeoff-tool-line"]',
        title: 'Line Measurements',
        description: 'You can add multiple measurements for each component if you want. Always measure the individual lengths to allow for waste calculation and full editing ability in later stages.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-tool-point',
        target: '[data-copilot="takeoff-tool-point"]',
        title: 'Point Tool',
        description: 'Use the Point tool for quantity-based items like lights, doors, solar panels, or showers. Select a component, then click on the plan to place a marker. Each click adds one to the count.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-measure-hint',
        target: '[data-copilot="takeoff-toolbar"]',
        title: 'Start Measuring',
        description: 'Make sure you select the correct measuring tool for each component. Measure the lengths, areas, or locations for each component, then select the next component. When you are finished, click "Save & Continue to Components" to move to the Quote Builder.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'dt-save',
        target: '[data-copilot="takeoff-save"]',
        title: 'Save & Continue',
        description: 'When you have finished measuring all your components, click "Save & Continue to Components" to save your takeoff and move to the Quote Builder. Your areas and component measurements will be pre-populated.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'flashing-draw',
    name: 'Profile Drawing',
    description: 'Draw accurate profile drawings with measurements for any component - helpful for placing orders, or for specific details you need to design or quote.',
    steps: [
      {
        id: 'fd-inputs',
        target: '[data-copilot="flashing-inputs"]',
        title: 'Name Your Drawing',
        description: 'Enter a name for your drawing - for example: _Custom Trim Profile, Corner Detail._ You can also add a description and choose a canvas size.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-line',
        target: '[data-copilot="flashing-tool-line"]',
        title: 'Line Tool',
        description: 'The Line tool is your main drawing tool. Click to place points and draw straight lines with automatic length and angle measurements. Click "Finish Line" or press Escape to stop drawing.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-text',
        target: '[data-copilot="flashing-tool-text"]',
        title: 'Text Tool',
        description: 'Use the Text tool to add labels or annotations anywhere on the canvas. Click where you want to place text.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-pencil',
        target: '[data-copilot="flashing-tool-pencil"]',
        title: 'Pencil Tool',
        description: 'The Pencil tool lets you freehand draw for quick annotations, sketches, or markup. You can choose between 3 thicknesses.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-edit',
        target: '[data-copilot="flashing-tool-edit"]',
        title: 'Edit Tool',
        description: 'The Edit tool lets you select, move, and resize any element on the canvas. Click on a line, text, or drawing to select it.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-tool-adjust',
        target: '[data-copilot="flashing-tool-adjust"]',
        title: 'Adjust Points',
        description: 'Adjust Points lets you fine-tune individual line points after drawing. Drag any point to reposition it - all connected measurements update automatically.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-measurements',
        target: '[data-copilot="flashing-measurements"]',
        title: 'Measurements Panel',
        description: 'All your measurements appear here. Click a measurement to select it on the canvas. You can edit values, toggle visibility, or delete measurements.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'fd-live-readout',
        target: '[data-copilot="flashing-live-readout"]',
        title: 'Live Readout',
        description: 'As you draw, the live readout shows the current length and angle in real time. This helps you draw accurately to scale.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'fd-save',
        target: '[data-copilot="flashing-save"]',
        title: 'Save Drawing',
        description: 'When you are finished, click Save. Your drawing will be saved to your drawings library and can be linked to components for material orders.',
        position: 'top',
        validation: 'none',
      },
    ],
  },
  {
    id: 'account-settings',
    name: 'Account',
    description: 'Your account, company, security, notifications and billing - all from one menu.',
    steps: [
      {
        id: 'as-welcome',
        target: 'nav[aria-label="Account sections"]',
        title: 'Find what you need',
        description: 'Use the sidebar to switch between Account (your name and sign-in email), Company (workspace settings), Security (password and 2FA), Notifications (email alerts and Copilot), and Billing.',
        position: 'right',
        validation: 'none',
      },
    ],
  },
  {
    id: 'flashings-orders',
    name: 'Drawings Library',
    description: 'Manage your profile drawings.',
    steps: [
      {
        id: 'fo-draw',
        target: '[data-copilot="create-drawing"]',
        title: 'Create a Drawing',
        description: 'Click "Create Drawing" to open the drawing tool where you can create accurate profile drawings with measurements and angles.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'material-orders-hub',
    name: 'Material Orders',
    description: 'Learn to create material orders for your suppliers.',
    steps: [
      {
        id: 'moh-overview',
        target: '[data-copilot="mo-action-cards"]',
        title: 'Material Orders',
        description: 'This is your Material Orders hub. You can create a custom order from scratch, create an order from a confirmed quote with pre-populated components, or manage supplier templates.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moh-custom',
        target: '[data-copilot="mo-custom-order"]',
        title: 'Custom Order',
        description: 'Click Custom Order to start a blank order form. You will enter supplier details and add items manually.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moh-from-quote',
        target: '[data-copilot="mo-order-from-quote"]',
        title: 'Order from Quote',
        description: 'Click Order from Quote to pre-populate with components from a confirmed quote. This saves time as all materials and quantities are pulled in automatically.',
        position: 'bottom',
        validation: 'none',
      },
    ],
  },
  {
    id: 'material-order-create',
    name: 'Create Material Order',
    description: 'Learn to build and customise a material order.',
    steps: [
      {
        id: 'moc-template',
        target: '[data-copilot="mo-template"]',
        title: 'Supplier Template',
        description: 'You can select a saved supplier template to auto-fill supplier details, or enter them manually below.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moc-header',
        target: '[data-copilot="mo-header-form"]',
        title: 'Supplier & Company Details',
        description: 'Enter the supplier name, reference, order type, colours, delivery date, and address on the left. Your company details appear on the right.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moc-minimize',
        target: '[data-copilot="mo-minimize-header"]',
        title: 'Minimize Header',
        description: 'Click "Minimize Header" to collapse the supplier details and see more of your order. You can expand it again anytime by clicking "Edit Header".',
        position: 'left',
        validation: 'none',
      },
      {
        id: 'moc-layout',
        target: '[data-copilot="mo-layout-toggle"]',
        title: 'Layout Mode',
        description: 'Choose Single Column for a standard list view, or Double Column to fit more items side by side on the printed order. You can switch between them anytime.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'moc-sidebar',
        target: '[data-copilot="mo-sidebar"]',
        title: 'Order Components',
        description: 'This panel controls what appears in your order. Click "+ Add Component" to add items. Each component can include a description, quantities, measurements, and a linked drawing/image.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'moc-visibility',
        target: '[data-copilot="mo-sidebar"]',
        title: 'Show & Hide Elements',
        description: 'For each component, you can show or hide the name, profile drawing, and measurements using the checkboxes. This lets you fully customise what appears on the printed order for each item.',
        position: 'right',
        validation: 'none',
      },
      {
        id: 'moc-save',
        target: '[data-copilot="mo-save"]',
        title: 'Save Order',
        description: 'When you are finished, click Save Order. You can preview and print the order, or come back and edit it later from the Material Orders page.',
        position: 'left',
        validation: 'none',
      },
    ],
  },
  {
    id: 'catalog-upload',
    name: 'Upload & Map a Catalog',
    description: 'Import a supplier CSV price list and map the columns so items can be searched on quote lines.',
    steps: [
      {
        id: 'catalog-upload-open',
        target: '[data-copilot="upload-catalog"]',
        title: 'Open the upload wizard',
        description: 'This is your Catalog Library. Click _"Upload catalog"_ to open the import wizard.',
        position: 'bottom',
        page: '/resources/catalogs',
        validation: 'click',
        validationTarget: '[data-copilot="catalog-wizard-drop"]',
        nudgeText: 'Click "Upload catalog" to continue.',
      },
      {
        id: 'catalog-upload-drop',
        target: '[data-copilot="catalog-wizard-drop"]',
        title: 'Choose your CSV file',
        description: 'Drop your supplier CSV here, or click to browse. _One item per row works best._ No headers? Columns are auto-labelled A, B, C…',
        position: 'bottom',
        page: '/resources/catalogs',
        validation: 'none',
        validationTarget: '[data-copilot="catalog-wizard-name"]',
        nudgeText: 'Choose a CSV file to continue.',
      },
      {
        id: 'catalog-upload-name',
        target: '[data-copilot="catalog-wizard-name"]',
        title: 'Name the catalog',
        description: 'Give it a recognisable name (e.g. _"Supplier Price List 2026"_) so you can find it when quoting, then click _Next_.',
        position: 'bottom',
        page: '/resources/catalogs',
        validation: 'none',
        validationTarget: '[data-copilot="catalog-wizard-map"]',
        nudgeText: 'Enter a name, then click Next.',
      },
      {
        id: 'catalog-upload-map',
        target: '[data-copilot="catalog-wizard-map"]',
        title: 'Map the columns',
        description: 'Match each column to a field: _Item / Description_ (the main line text), _Description / Quantity_ (optional detail), and _Price_ (fills the quote line). Auto-detection picks likely matches - adjust if needed, then click _Next_.',
        position: 'top',
        page: '/resources/catalogs',
        validation: 'none',
        validationTarget: '[data-copilot="catalog-wizard-save"]',
        nudgeText: 'Map your columns, then click Next.',
      },
      {
        id: 'catalog-upload-save',
        target: '[data-copilot="catalog-wizard-save"]',
        title: 'Save the catalog',
        description: 'Click _"Save catalog"_ to import all rows. When the status shows _Ready_, the catalog is searchable on any quote line. (Need the same file mapped differently later? Open the catalog and use the **Maps** tab - no re-upload needed.)',
        position: 'top',
        page: '/resources/catalogs',
        validation: 'none',
      },
    ],
  },
  {
    id: 'catalog-add-to-quote',
    name: 'Add a Catalog Item to a Quote',
    description: 'Search your supplier catalog and insert a priced line directly onto a customer quote.',
    steps: [
      {
        id: 'catalog-atq-nav',
        target: '[data-copilot="nav-quotes"]',
        title: 'Go to Quotes',
        description: 'Click _"Quotes"_ to open your quotes hub.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'catalog-atq-open-quote',
        // No per-row anchor on the quotes hub - instruct without a highlight.
        target: 'main',
        title: 'Open a Quote',
        description: 'Click an existing quote in the list to open its summary page. _No quote yet? Create one first, then come back to this guide._',
        position: 'bottom',
        page: '/quotes',
        validation: 'none',
      },
      {
        id: 'catalog-atq-customer-tab',
        target: '[data-copilot="tab-customer"]',
        title: 'Open the Customer Quote Tab',
        description: 'On the summary page, click the _Customer Quote_ tab. _If you have not built a customer quote yet, click "Create customer quote" to start one._',
        position: 'bottom',
        page: '/quotes/[id]/summary',
        validation: 'click',
        nudgeText: 'Please open the Customer Quote tab to continue.',
      },
      {
        id: 'catalog-atq-edit-icon',
        target: '[data-copilot="edit-customer-icon"]',
        title: 'Edit the Customer Quote',
        description: 'Click the _pencil / edit icon_ on the Customer Quote to open the editor, where you can add and price lines.',
        position: 'bottom',
        page: '/quotes/[id]/summary',
        validation: 'click',
        nudgeText: 'Please click the edit icon to open the editor.',
      },
      {
        id: 'catalog-atq-add-line',
        target: '[data-copilot="cl-add-line-btn"]',
        title: 'Add a New Line',
        description: 'Click _"+ Add New Line"_ to open the line picker. It gives you three options: a custom line, a component from your library, or a catalog search.',
        position: 'bottom',
        page: '/quotes/[id]/customer-edit',
        validation: 'click',
        validationTarget: '[data-copilot="add-line-tabs"]',
        nudgeText: 'Please click "+ Add New Line" to continue.',
      },
      {
        id: 'catalog-atq-tab',
        target: '[data-copilot="add-line-catalog-tab"]',
        title: 'Switch to Catalog Search',
        description: 'Click the _"Search catalog"_ tab. If no catalogs are listed, go to your _Resources → Catalogs_ section first and upload a supplier CSV.',
        position: 'bottom',
        page: '/quotes/[id]/customer-edit',
        validation: 'click',
        nudgeText: 'Please click "Search catalog" to continue.',
      },
      {
        id: 'catalog-atq-search',
        target: '[data-copilot="catalog-search-input"]',
        title: 'Search for an Item',
        description: 'Type a product name, code, or keyword to search your catalog. Results appear instantly. _Tip: use the catalog dropdown above the search box to narrow results to a specific price list._',
        position: 'bottom',
        page: '/quotes/[id]/customer-edit',
        validation: 'input',
      },
      {
        id: 'catalog-atq-result',
        target: '[data-copilot="catalog-search-results"]',
        title: 'Select a Result',
        description: 'Click a result to add it to the quote. The item description and price are filled in from the catalog - you can edit the line afterwards using the pencil icon.',
        position: 'top',
        page: '/quotes/[id]/customer-edit',
        validation: 'none',
      },
      {
        id: 'catalog-atq-save',
        target: '[data-copilot="cl-save-return"]',
        title: 'Save and Return',
        description: 'The catalog item is now a line on the quote. Check the right-hand preview - use the pencil icon to edit any line. When you are happy, click _"Save and Return"_ to go back to the quote summary.',
        position: 'right',
        page: '/quotes/[id]/customer-edit',
        validation: 'none',
      },
    ],
  },
  {
    id: 'attachments-upload',
    name: 'Upload a File to Your Attachment Library',
    description: 'Add reusable images, drawings or documents to your attachment library so they can be sent with any quote.',
    steps: [
      {
        id: 'attachments-upload-nav',
        target: '[data-copilot="nav-resources"]',
        title: 'Go to Resources',
        description: 'Click _"Resources"_ in the navigation to open your Resource Library. The _Attachments_ section is where your reusable files live.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'attachments-upload-card',
        target: '[data-copilot="resources-card-attachments"]',
        title: 'Open Attachments',
        description: 'Click the _"Attachments"_ card to open your file library. You can store images, drawings, PDFs - anything you regularly send with quotes. _Attachment library is available on Pro and above._',
        position: 'bottom',
        page: '/resources',
        validation: 'click',
        nudgeText: 'Please click the "Attachments" card to continue.',
      },
      {
        id: 'attachments-upload-btn',
        target: '[data-copilot="attachment-upload-btn"]',
        title: 'Upload a File',
        description: 'Click _"Upload file"_ to add an image or document. Give it a clear name - for example: _"Safety Data Sheet", "Product Spec Sheet", "Terms & Conditions"._ Once uploaded, it can be attached to any quote when you send it.',
        position: 'bottom',
        page: '/resources/attachments',
        validation: 'none',
      },
    ],
  },
  {
    id: 'attachments-send',
    name: 'Send a Quote with an Attachment',
    description: 'Attach files to a customer quote at send time - from the quote summary, open Send Quote and pick the attachments to include.',
    steps: [
      {
        id: 'attachments-send-nav',
        target: '[data-copilot="nav-quotes"]',
        title: 'Go to Quotes',
        description: 'Click _"Quotes"_ to open your quotes hub.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'attachments-send-open-quote',
        target: 'main',
        title: 'Open the Quote',
        description: 'Click the quote you want to send to open its summary page. _The quote needs to be ready to send._',
        position: 'bottom',
        page: '/quotes',
        validation: 'none',
      },
      {
        id: 'attachments-send-btn',
        target: '[data-copilot="send-quote"]',
        title: 'Send Quote',
        description: 'On the summary page, click _"Send Quote"_ to open the send options. You can send via email, copy a link, or use a send template.',
        position: 'top',
        page: '/quotes/[id]/summary',
        validation: 'click',
        validationTarget: '[data-copilot="cl-send-modal"]',
        nudgeText: 'Please click "Send Quote" to continue.',
      },
      {
        id: 'attachments-send-picker',
        target: '[data-copilot="attachment-send-picker"]',
        title: 'Add Attachments',
        description: 'In the send details, open the _"Attachments"_ picker and tick the files to include. _Library files_ come from your attachment library; _quote files_ are documents uploaded directly to this job. _No files in the list? Add some to your library first (ask me "how do I upload a file to my attachment library")._',
        position: 'bottom',
        page: '/quotes/[id]/summary',
        validation: 'none',
      },
      {
        id: 'attachments-send-confirm',
        target: '[data-copilot="cl-send-mode"]',
        title: 'Send with Attachments',
        description: 'With your files selected, complete the send - enter the customer\'s email or copy the link. _Attachments are included automatically in whatever delivery method you choose._ The customer sees them alongside the quote.',
        position: 'top',
        page: '/quotes/[id]/summary',
        validation: 'none',
      },
    ],
  },
  {
    id: 'order-line-by-line',
    name: 'Build a Line-by-Line Material Order',
    description: 'Create a clean text-based material order with individual priced lines - ideal for sending to a supplier with a clear itemised list.',
    steps: [
      {
        id: 'olbl-nav',
        target: '[data-copilot="nav-orders"]',
        title: 'Orders',
        description: 'Click _"Orders"_ to go to the orders hub. From here you can create new orders or manage existing ones.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'olbl-custom',
        target: '[data-copilot="mo-custom-order"]',
        title: 'Start a Custom Order',
        description: 'Click _"Custom Order"_ to start a blank order from scratch. A layout picker will appear - choose your order format before building it.',
        position: 'bottom',
        page: '/material-orders',
        validation: 'click',
        validationTarget: '[data-copilot="order-layout-picker"]',
        nudgeText: 'Please click "Custom Order" to continue.',
      },
      {
        id: 'olbl-layout-pick',
        target: '[data-copilot="order-layout-line-by-line"]',
        title: 'Choose Line by Line',
        description: 'Select _"Line by Line"_ from the layout picker. This creates a clean text list - item, description, qty, and price - just like a customer quote. _You cannot switch layout after saving, so choose carefully._',
        position: 'top',
        page: '/material-orders',
        validation: 'click',
        nudgeText: 'Please select "Line by Line" to continue.',
      },
      {
        id: 'olbl-controls',
        target: '[data-copilot="order-lbl-controls"]',
        title: 'Order Items Panel',
        description: 'This is the _Order items_ panel on the left. It lists every line you add. The right-hand side shows a live print preview so you can see exactly how the order will look.',
        position: 'right',
        page: '/material-orders/create',
        validation: 'none',
      },
      {
        id: 'olbl-add-line',
        target: '[data-copilot="order-lbl-add-line"]',
        title: 'Add Lines',
        description: 'Click _"+ Add New Line"_ to add items. You have three options: a _Custom line_ (free text + price), a _Component_ from your library, or a _Catalog search_ (searches your imported supplier price lists). Add as many lines as you need.',
        position: 'bottom',
        page: '/material-orders/create',
        validation: 'none',
      },
      {
        id: 'olbl-line-controls',
        target: '[data-copilot="order-lbl-add-line"]',
        title: 'Line Controls',
        description: 'Each line has quick toggles: _Show_ (include or hide it on the order), _Price_ (show or hide the price for that line), and _In total_ (include or exclude it from the subtotal). Use the _Edit_ link to change the text or amount.',
        position: 'bottom',
        page: '/material-orders/create',
        validation: 'none',
      },
      {
        id: 'olbl-footer',
        target: '[data-copilot="order-lbl-footer"]',
        title: 'Footer (Optional)',
        description: 'Add any footer text below the items - for example: _"Payment terms: 14 days", "Delivery instructions", or "Call before delivering"._ This prints under the item list.',
        position: 'top',
        page: '/material-orders/create',
        validation: 'none',
      },
      {
        id: 'olbl-taxes',
        target: '[data-copilot="order-lbl-taxes"]',
        title: 'Taxes (Optional)',
        description: 'Orders have no tax applied by default. If you need to include _GST, VAT,_ or any other tax, add it here. You can type a custom rate or apply a company default if one is saved in your settings.',
        position: 'top',
        page: '/material-orders/create',
        validation: 'none',
      },
    ],
  },
  {
    id: 'order-from-quote',
    name: 'Create an Order from a Quote',
    description: 'Pre-populate a material order from a quote - all priced lines carried over automatically.',
    steps: [
      {
        id: 'ofq-nav',
        target: '[data-copilot="nav-orders"]',
        title: 'Orders',
        description: 'Click _"Orders"_ to go to the orders hub.',
        position: 'bottom',
        validation: 'none',
      },
      {
        id: 'ofq-hub-card',
        target: '[data-copilot="mo-order-from-quote"]',
        title: 'Order from Quote',
        description: 'Click _"Order from Quote"_ to pre-populate an order with data from a quote. A layout picker will appear - choose how you want the order to look before selecting your quote.',
        position: 'bottom',
        page: '/material-orders',
        validation: 'click',
        validationTarget: '[data-copilot="order-layout-picker"]',
        nudgeText: 'Please click "Order from Quote" to continue.',
      },
      {
        id: 'ofq-layout',
        target: '[data-copilot="order-layout-line-by-line"]',
        title: 'Choose a Layout',
        description: 'Select _"Line by Line"_ for a clean itemised list with prices - ideal when you want to show the supplier exactly what you need. Or choose Single/Double Column if you prefer the components-and-images format.',
        position: 'top',
        page: '/material-orders',
        validation: 'none',
      },
      {
        id: 'ofq-select-quote',
        target: '[data-copilot="order-from-quote-list"]',
        title: 'Select a Quote',
        description: 'Find and click the quote you want to order from. You can search by quote number, client name, or job name, and filter by status.',
        position: 'top',
        page: '/material-orders/order-from-quote',
        validation: 'none',
      },
      {
        id: 'ofq-confirm',
        target: '[data-copilot="order-from-quote-confirm"]',
        title: 'Confirm Quote Selection',
        description: 'A summary of the quote appears. Click _"Create Order"_ to open the order editor pre-populated with all the quote\'s priced lines.',
        position: 'bottom',
        page: '/material-orders/order-from-quote',
        validation: 'click',
        nudgeText: 'Please select a quote and click "Create Order" to continue.',
      },
      {
        id: 'ofq-review',
        target: '[data-copilot="mo-header-form"]',
        title: 'Fill In Supplier Details',
        description: 'The order editor opens with all quote lines pre-filled. Add your supplier name, reference, and delivery details in the header form. _Review each line - you can edit, hide, or remove any item before saving._',
        position: 'bottom',
        page: '/material-orders/create',
        validation: 'none',
      },
      {
        id: 'ofq-save',
        target: '[data-copilot="mo-save"]',
        title: 'Save the Order',
        description: 'Click _"Save Order"_ when everything looks right. From the preview page you can print, download, or send the order to your supplier. The quote is not modified - the order is a separate document.',
        position: 'left',
        page: '/material-orders/create',
        validation: 'none',
      },
    ],
  },

  // ── Invoice flows ──────────────────────────────────────────────────────────

  {
    id: 'create-invoice',
    name: 'Create an Invoice',
    description: 'Walk through creating, building, and sending a complete invoice from start to finish.',
    steps: [
      {
        id: 'inv-new',
        target: '[data-copilot="new-invoice"]',
        title: 'Create a New Invoice',
        description: 'Click **+ New Invoice** to start. A pop-up opens where you can create a blank invoice or generate one from an accepted quote.',
        position: 'bottom',
        page: '/invoices',
        validation: 'click',
        validationTarget: '[data-copilot="invoice-method-blank"]',
        nudgeText: 'Click + New Invoice to continue.',
      },
      {
        id: 'inv-method-blank',
        target: '[data-copilot="invoice-method-blank"]',
        title: 'Blank Invoice',
        description: '**Blank Invoice** - enter a customer name (and optional email) and start from scratch. Great for standalone invoices.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-method-from-quote',
        target: '[data-copilot="invoice-method-from-quote"]',
        title: 'From a Quote',
        description: '**From a Quote** - search by customer name or quote number to find an accepted quote. QuoteCore+ imports the customer details, branding, and all visible line items automatically. Pick your option and complete the form.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-choose-template',
        target: '[data-copilot="invoice-choose-template"]',
        title: 'Choose Template',
        description: 'Once your details are in, click **Choose Template** to move to the template step.',
        position: 'top',
        page: '/invoices',
        validation: 'click',
        validationTarget: '[data-copilot="invoice-template-none"]',
        nudgeText: 'Click Choose Template to continue.',
      },
      {
        id: 'inv-pick-template',
        target: '[data-copilot="invoice-template-none"]',
        title: 'Pick a Template (or none)',
        description: 'Pick a saved **invoice template** to apply your branding and payment details automatically, or choose **No template** to fill those in manually. _Templates are managed in Resources → Invoice Templates._ Then click **Create Invoice** to open the editor.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-editor-overview',
        target: '[data-copilot="invoice-preview"]',
        title: 'Invoice Editor Overview',
        description: 'Welcome to the invoice editor. It has two panels:\n\n**Left panel** - Line Items, Details, and Activity tabs. This is where you build the invoice content.\n\n**Right panel** - a live preview showing exactly what your customer will see. Every change updates here instantly.',
        position: 'left',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-lines-tab',
        target: '[data-copilot="invoice-lines-tab"]',
        title: 'Line Items Tab',
        description: 'You start on the **Line Items** tab. This is where you add and manage the items that appear on the invoice - materials, labour, call-out fees, anything you want to charge for.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-add-line',
        target: '[data-copilot="invoice-add-line"]',
        title: 'Add a Line Item',
        description: 'Click **Add Line Item** to add your first item. You have three options:\n\n**Custom** - enter a title, description, quantity, and price manually.\n**Catalog** - search your supplier catalog and import a row with the price pre-filled.\n**Component** - pull from your component library.',
        position: 'top',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-line-toggles',
        target: '[data-copilot="invoice-lines-list"]',
        title: 'Show / Hide Toggles',
        description: 'After adding a line, each item shows four checkboxes:\n\n**Show** - displays or hides the line on the customer invoice.\n**Price** - shows or hides the price for that line.\n**Qty** - shows or hides the quantity.\n**Add $** - includes or excludes the line from the invoice total.\n\n_Tip: Show and Add $ are independent - you can hide a line but still include its amount in the total, useful for a built-in contingency._',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-line-edit',
        target: '[data-copilot="invoice-lines-list"]',
        title: 'Edit & Reorder Lines',
        description: 'Click the **pencil icon** on any line to edit its title, description, quantity, unit, or price inline. Use the **↑ / ↓ arrows** on the left to reorder lines. Click the **×** to remove a line.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-switch-details',
        target: '[data-copilot="invoice-details-tab"]',
        title: 'Switch to Details Tab',
        description: 'Click the **Details** tab to set dates, notes, terms, business info, and payment details for this invoice.',
        position: 'right',
        page: '/invoices',
        validation: 'click',
        nudgeText: 'Click the Details tab to continue.',
      },
      {
        id: 'inv-dates',
        target: '[data-copilot="invoice-details-tab"]',
        title: 'Invoice Dates',
        description: 'Set the **Invoice Date** and an optional **Due Date**. The due date appears on the customer-facing invoice - it makes payment expectations clear. _For example: "Payment due 14 days from invoice date."_',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-notes-terms',
        target: '[data-copilot="invoice-details-tab"]',
        title: 'Notes & Terms',
        description: 'Add any **Notes** for the customer (shown below the line items on the invoice) and your **Terms** - payment conditions, dispute process, or anything you want stated clearly.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-edit-header',
        target: '[data-copilot="invoice-edit-header"]',
        title: 'Business Details',
        description: 'Click **Edit** next to Business Details to update the company info shown on this invoice - name, address, email, phone, logo, and footer text. _Changes here only affect this invoice. To set defaults for all future invoices, save an Invoice Template in Resources._',
        position: 'left',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-payment-details',
        target: '[data-copilot="invoice-payment-details"]',
        title: 'Payment Details',
        description: 'Enter your bank account details - account name, bank, account number, sort code, and an optional payment link. These appear in a **Payment Instructions** box on the customer invoice with a one-tap copy button for each field, making it easy for them to pay the right account.',
        position: 'left',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-save',
        target: '[data-copilot="invoice-save"]',
        title: 'Save the Invoice',
        description: 'Click **Save** to save immediately. The editor also auto-saves after 2 seconds of inactivity - you\'ll see an _"Unsaved changes"_ indicator if there\'s anything pending. Once saved you\'re ready to send.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-send-from-create',
        target: '[data-copilot="invoice-send"]',
        title: 'Send the Invoice',
        description: 'Click **Send Invoice** to choose how to deliver it:\n\n**Send from QuoteCore+** - email the customer directly with a branded message.\n**Copy URL Link** - copy the link and share via WhatsApp, SMS, or any other channel.\n**Generate Email** - build a ready-to-paste email for your own email client.\n\nOnce sent: _Draft to Sent to Viewed_ (when opened) to _Payment Reported_ (when the customer clicks "Payment Sent") - you confirm - **Paid**.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
    ],
  },

  {
    id: 'invoice-editor',
    name: 'Invoice Editor',
    description: 'Learn every part of the invoice editor - lines, toggles, details, payment info, and saving.',
    steps: [
      {
        id: 'inv-ed-overview',
        target: '[data-copilot="invoice-preview"]',
        title: 'Editor Overview',
        description: 'The invoice editor has two panels. The **left panel** has three tabs: Line Items, Details, and Activity. The **right panel** is a live preview - it updates instantly as you make changes so you always know what the customer will see.',
        position: 'left',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-lines-tab',
        target: '[data-copilot="invoice-lines-tab"]',
        title: 'Line Items Tab',
        description: 'The **Line Items** tab lists everything you are charging for. This is the default view when you open an invoice.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-add-line',
        target: '[data-copilot="invoice-add-line"]',
        title: 'Add a Line Item',
        description: 'Click **Add Line Item** to open the line picker. Choose **Custom** for a free-text line, **Catalog** to search your supplier price list, or **Component** to pull from your library. Add as many lines as needed.',
        position: 'top',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-toggles',
        target: '[data-copilot="invoice-lines-list"]',
        title: 'Show / Hide Toggles',
        description: 'Each line has four checkboxes:\n\n**Show** - include or hide the line on the customer invoice.\n**Price** - show or hide the line price.\n**Qty** - show or hide the quantity.\n**Add $** - include or exclude the amount from the invoice total.\n\nShow and Add $ are independent: you can hide a line visually but still count it in the total.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-edit-line',
        target: '[data-copilot="invoice-lines-list"]',
        title: 'Edit & Reorder',
        description: 'Click the **pencil icon** on a line to edit the title, description, quantity, unit, or price. Use the **up/down arrows** to change the order. Click the **X** to delete a line.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-details-tab',
        target: '[data-copilot="invoice-details-tab"]',
        title: 'Details Tab',
        description: 'Click the **Details** tab to access dates, notes, terms, business info, and payment details.',
        position: 'right',
        page: '/invoices',
        validation: 'click',
        nudgeText: 'Click the Details tab to continue.',
      },
      {
        id: 'inv-ed-dates',
        target: '[data-copilot="invoice-details-tab"]',
        title: 'Invoice Dates',
        description: 'Set the **Invoice Date** and an optional **Due Date**. The due date appears on the customer invoice so they know exactly when payment is expected.',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-notes-terms',
        target: '[data-copilot="invoice-details-tab"]',
        title: 'Notes & Terms',
        description: '**Notes** appear below the line items - use them for job-specific information or a thank-you message. **Terms** are your payment conditions - for example: "Payment due within 14 days of invoice date."',
        position: 'right',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-header',
        target: '[data-copilot="invoice-edit-header"]',
        title: 'Business Details',
        description: 'Click **Edit** to update the company name, address, email, phone, logo, and footer shown on this invoice. To set defaults for future invoices, save an Invoice Template in Resources.',
        position: 'left',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-payment',
        target: '[data-copilot="invoice-payment-details"]',
        title: 'Payment Details',
        description: 'Fill in your bank account details here. They appear in a **Payment Instructions** block on the customer invoice with a one-tap copy button for each field. The customer can copy your account number or sort code directly from the invoice page.',
        position: 'left',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-ed-save',
        target: '[data-copilot="invoice-save"]',
        title: 'Save',
        description: 'Click **Save** to save immediately. The editor auto-saves after 2 seconds of inactivity too - the top bar shows "Unsaved changes" when there is anything pending. Once saved, you can send the invoice.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
    ],
  },

  {
    id: 'send-invoice',
    name: 'Send an Invoice',
    description: 'Send your invoice to the customer by email, link, or copy-ready text, and track payment status.',
    steps: [
      {
        id: 'inv-send-btn',
        target: '[data-copilot="invoice-send"]',
        title: 'Open Send Options',
        description: 'Click **Send Invoice** in the top bar of the editor. This opens a panel with three delivery methods.',
        position: 'bottom',
        page: '/invoices',
        validation: 'click',
        nudgeText: 'Click Send Invoice to continue.',
      },
      {
        id: 'inv-send-direct',
        target: '[data-copilot="invoice-send"]',
        title: 'Option 1 - Send from QuoteCore+',
        description: '**Send from QuoteCore+** emails the customer directly. Enter their email (pre-filled if added on creation), choose an optional message template, and click Send Invoice. The customer receives a branded email with a _View Invoice_ button. When they open the link, the status updates to **Viewed** and you get an in-app alert.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-send-url',
        target: '[data-copilot="invoice-send"]',
        title: 'Option 2 - Copy URL Link',
        description: '**Copy URL Link** copies the public invoice link to your clipboard. Paste it into WhatsApp, SMS, email - wherever you communicate with the customer. The link is permanent.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-send-email',
        target: '[data-copilot="invoice-send"]',
        title: 'Option 3 - Generate Email',
        description: '**Generate Email** builds a ready-to-paste email (subject + body) using your template or a default message. Click _Copy Email_ and paste it straight into Gmail, Outlook, or any other client.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
      {
        id: 'inv-send-track',
        target: '[data-copilot="invoice-send"]',
        title: 'Track Payment Status',
        description: 'After sending, the status updates automatically:\n\n**Draft to Sent** on first send.\n**Sent to Viewed** when the customer opens the link.\n**Viewed to Payment Reported** when they click "Payment Sent" - you get an alert.\n\nOnce the money has arrived, click **Confirm Payment** to close it as **Paid**. Every event is logged in the **Activity** tab.',
        position: 'bottom',
        page: '/invoices',
        validation: 'none',
      },
    ],
  },
  // ────────────────────────────────────────────────────────────────────────
  // Message Center (added 2026-06-08, generic trade set - mirror of base set)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'message-center',
    name: 'Message Center',
    description: 'Manage every alert and message from your quotes, orders and invoices in one inbox.',
    steps: [
      {
        id: 'mc-open',
        target: '[data-copilot="nav-inbox"]',
        title: 'Open your Message Center',
        description: 'Click the **orange envelope** in the top bar to open your Message Center. It collects every alert and message from your quotes, orders and invoices in one place - separate from the bell, which just shows your most recent alerts.',
        position: 'bottom',
        page: '/inbox',
        validation: 'none',
      },
      {
        id: 'mc-folders',
        target: '[data-copilot="inbox-folders"]',
        title: 'Active, To-Do & Archived',
        description: 'Use the folders on the left to organise messages. **Active** is your main list. Push anything to deal with later into **To-Do**. Marking something **Done** moves it to **Archived**, where you can restore it or delete it permanently.',
        position: 'right',
        page: '/inbox',
        validation: 'none',
      },
      {
        id: 'mc-search',
        target: '[data-copilot="inbox-search"]',
        title: 'Search & filter',
        description: 'Search the text of any message, or filter by type - **Quotes, Orders, Invoices, or Messages**. Tick the checkboxes to select several at once, then mark them read, move them to To-Do, or archive them in one go.',
        position: 'bottom',
        page: '/inbox',
        validation: 'none',
      },
    ],
  },
];
