// Shared serialisable calibration domain contracts.
// Source of truth: docs/AI_ASSISTED_CALIBRATION_IMPLEMENTATION_PLAN.md sections 5.3, 6.4, 6.5, 8.1, 9.3.
// Pure data types only - no React, Fabric, Supabase or OpenAI imports; node-safe.

export type Point = Readonly<{ x: number; y: number }>;

// x' = a*x + c*y + e; y' = b*x + d*y + f
export type Affine2D = readonly [number, number, number, number, number, number];

export type DistanceUnit = 'm' | 'cm' | 'mm' | 'ft' | 'in' | 'yd';
export type WorkingUnit = 'meters' | 'feet';

export interface CalibrationImageDescriptor {
  pageId: string;
  /** Authoritative server content-digest revision of the immutable source
   *  image (sha256 hash). Null when the client does not know it yet (the
   *  search response carries it and the controller tracks it separately).
   *  NEVER a client-side fabricated value (P0-6). */
  imageRevision: string | null;
  /** Client render-frame identity (page + canvas raster this scene shows).
   *  Used ONLY for client-side mapping and reducer context guards - never
   *  persisted and never confused with the authoritative source revision. */
  frameKey: string;
  sourceWidth: number;         // after orientation normalisation
  sourceHeight: number;
  sceneWidth: number;
  sceneHeight: number;
  sourceToScene: Affine2D;
  coordinateFrame: 'takeoff-scene-v1';
  geometryVersion: 1;
}

export type AnalysisPurpose = 'overview' | 'reference' | 'endpoint-a' | 'endpoint-b' | 'label';

/** P6: server-generated evidence crop image (data-URI, <=600px longest edge jpeg q80). */
export interface CalibrationEvidenceCrop {
  kind: 'endpoint-a' | 'endpoint-b' | 'label';
  dataUri: string;
}

export interface AnalysisImageDescriptor {
  inputImageId: string;
  imageRevision: string;
  width: number;
  height: number;
  analysisToSource: Affine2D;
  purpose: AnalysisPurpose;
}

export type SourceType =
  | 'dimension_line'
  | 'scale_bar'
  | 'google_earth_measure'
  | 'map_measure'
  | 'other_explicit_distance';

export interface RawLocatedPoint {
  inputImageId: string;
  x: number;
  y: number;
}

export interface RawEvidenceBox {
  inputImageId: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface RawCalibrationHypothesis {
  referenceToken: string;            // an echo token, not a trusted persistent ID
  parentReferenceToken: string | null; // set during refinement
  sourceType: SourceType;
  p1: RawLocatedPoint;
  p2: RawLocatedPoint;
  labelText: string | null;          // exact short visible label, partial if necessary
  distanceValueText: string | null;  // copied text, e.g. "6420" or "10'-6\"""
  unitText: string | null;           // copy visible unit; never infer from country
  unitSource: 'label' | 'drawing_note' | 'unknown';
  unitEvidenceText: string | null;
  labelBox: RawEvidenceBox | null;
  unitEvidenceBox: RawEvidenceBox | null;
  explicitDistanceReference: boolean;
  straightSpan: boolean;
  bothEndpointsVisible: boolean;
  endpointAssociationClear: boolean;
  sameMeasurementView: boolean;
  endpointConfidence: number;        // model self-report, not calibrated probability
  valueConfidence: number | null;
  endpointEvidence: string;          // concise observable description, not reasoning log
}

export interface RawCalibrationDetection {
  suitability: 'suitable' | 'unsuitable' | 'uncertain';
  suitabilityReason: string;
  hypotheses: RawCalibrationHypothesis[];
  notes: string[];
}

export interface CalibrationCandidate {
  id: string;                   // generated by the server
  referenceId: string;          // physical reference identity across rounds
  /** P1-9 (Phase E audit 2026-09-20): server-signed token binding this
   *  candidate's original source geometry to the ledger run, echoed by a
   *  targeted refine request. Present on round-0 results only. */
  refineToken?: string | null;
  revision: number;             // increases for explicit endpoint refinement
  searchRound: 0 | 1;
  imageRevision: string;
  sourceType: SourceType;
  sourceP1: Point;
  sourceP2: Point;
  sceneP1: Point;
  sceneP2: Point;
  scenePixelLength: number;     // computed, never trusted from model
  sourceLabelText: string | null;
  suggestedDistance: number | null;
  suggestedUnit: DistanceUnit | null;
  valueState: 'readable' | 'needs_distance' | 'needs_unit' | 'needs_both';
  endpointConfidence: number;
  valueConfidence: number | null;
  evidence: {
    labelBox: RawEvidenceBox | null;
    unitEvidenceBox: RawEvidenceBox | null;
    endpointDescription: string;
    analysisImageIds: string[];
    /** P6: real crops from the immutable source, generated server-side. */
    crops?: readonly CalibrationEvidenceCrop[];
    /** P1-12 (Phase E audit 2026-09-20): label evidence centre in SOURCE
     *  raster pixels (from the detected labelBox when available). The label
     *  evidence crop is centred here; the span midpoint is only the fallback. */
    sourceLabelCentre?: Point | null;
  };
  warnings: string[];
}

export type CandidateDecision =
  | 'unreviewed'
  | 'accepted'
  | 'skipped'
  | 'needs_reconfirmation'
  | 'superseded';

export interface CandidateReview {
  candidateId: string;
  decision: CandidateDecision;
  enteredDistance: string;        // UI draft; parse strictly before acceptance
  enteredUnit: DistanceUnit | null;
  rejectedReason: 'endpoints' | 'wrong_reference' | 'unsure' | null;
}

export type AcceptedReferenceSource = 'manual' | 'ai_confirmed' | 'ai_adjusted';

export interface AcceptedReferenceDraft {
  id: string;
  source: AcceptedReferenceSource;
  candidateId: string | null;
  referenceId: string | null;
  candidateRevision: number | null;
  sceneP1: Point;
  sceneP2: Point;
  confirmedDistance: number;
  confirmedUnit: DistanceUnit;
  originalLabelText: string | null;
  valueCorrected: boolean;
  /** M4 (spec §7.4 rule 5): true when a human moved at least one endpoint of
   *  an AI-origin reference. Additive/optional so existing persisted rows and
   *  the v1 codec stay compatible. */
  endpointsEdited?: boolean;
}

export interface CalibrationReviewState {
  phase: 'idle' | 'searching' | 'reviewing' | 'manual' |
         'committing' | 'completed' | 'cancelled';
  mode: 'new' | 'replace' | 'edit';
  sessionId: string | null;
  requestId: string | null;
  contextEpoch: number;
  image: CalibrationImageDescriptor;
  baseCalibrationRevision: number;
  searchRoundsCompleted: 0 | 1 | 2;
  candidates: CalibrationCandidate[];
  reviews: Record<string, CandidateReview>;
  accepted: AcceptedReferenceDraft[];
  activeCandidateId: string | null;
  error: { code: string; message: string } | null;
}

export interface EffectiveCalibration {
  scale: number;                 // real working units per scene pixel
  unit: WorkingUnit;
  aggregationPolicy: 'mean-distance-per-scene-pixel-v1';
  contributingCalibrationIds: string[];
  validCalibrationCount: number;
  scaleRangePct: number;         // 100 * (max(S_i)-min(S_i)) / mean(S_i)
  disagreementWarning: string | null;
}
