DO $$ DECLARE x record; target text;
BEGIN
 FOR x IN SELECT * FROM qcp_test.original_functions LOOP
 target:=CASE x.proname WHEN 'get_ai_assist_points_status' THEN 'qcp_p2_legacy_ai_points_status' ELSE 'qcp_p2_legacy_'||x.proname END;
 PERFORM qcp_test.check((SELECT prosrc=x.prosrc FROM pg_proc WHERE proname=target AND pronamespace='public'::regnamespace),'legacy function body unchanged: '||x.proname);
 PERFORM qcp_test.check((SELECT oid=x.oid FROM pg_proc WHERE proname=x.proname AND pronamespace='public'::regnamespace),'public function OID unchanged: '||x.proname);
 END LOOP;
END $$;
DO $$ DECLARE co uuid:=qcp_test.add_company(true,qcp_test.default_limits()); legacy uuid:=qcp_test.add_company(false);
 first_q uuid; before_n bigint; ctx jsonb; s jsonb;
BEGIN
 SELECT public.create_quote_atomic(co,co,'{"customer_name":"Draft 1"}') INTO first_q;
 PERFORM public.create_quote_atomic(co,co,'{"customer_name":"Draft 2"}');
 PERFORM public.create_quote_atomic(co,co,'{"customer_name":"Draft 3"}');
 PERFORM public.create_quote_atomic(co,co,'{"customer_name":"Draft 4"}');
 PERFORM public.create_quote_atomic(co,co,'{"customer_name":"Draft 5"}');
 ctx:=public.qcp_usage_context(co);
 PERFORM qcp_test.check(public.qcp_usage_total(co,ctx,'quote')=5,'five created drafts count');
 PERFORM qcp_test.throws(format('SELECT create_quote_atomic(%L,%L,%L::jsonb)',co,co,'{"customer_name":"Rejected"}'),'P0002','sixth draft refused atomically');
 PERFORM qcp_test.check((SELECT count(*)=5 FROM quotes WHERE company_id=co),'refused quote not inserted');
 UPDATE quotes SET status='sent' WHERE id=first_q;
 PERFORM qcp_test.check(public.qcp_usage_total(co,ctx,'quote')=5,'status update does not debit custom ledger');
 DELETE FROM quotes WHERE id=first_q;
 PERFORM qcp_test.check(public.qcp_usage_total(co,ctx,'quote')=5,'deleting quote does not refund creation');
 PERFORM qcp_test.throws(format('INSERT INTO quotes(id,company_id,customer_name) VALUES(%L,%L,%L)',first_q,co,'Reused'),'QCP03','deleted quote UUID cannot be reused for free');
 PERFORM qcp_test.throws(format('UPDATE quotes SET company_id=%L WHERE company_id=%L',legacy,co),'42501','custom quote cannot move into legacy company');
 PERFORM qcp_test.renew(co);
 PERFORM qcp_test.check(public.qcp_usage_total(co,public.qcp_usage_context(co),'quote')=0,'new paid billing period starts independent quote usage');
 PERFORM create_quote_atomic(co,co,'{"customer_name":"New period"}');
 PERFORM qcp_test.check(public.qcp_usage_total(co,public.qcp_usage_context(co),'quote')=1,'renewed quote consumes new period');
 s:=qcp_usage_snapshot(co,'acct_P2fixture','test');
 PERFORM qcp_test.check((s->>'periodStart')::timestamptz=(SELECT period_start FROM company_custom_billing WHERE company_id=co),'display uses Stripe grant timestamp, not calendar month');
 PERFORM qcp_test.throws(format('SELECT qcp_usage_snapshot(%L,%L,%L)',co,'acct_WRONG','test'),'QCP01','wrong Stripe account denied');
 UPDATE company_custom_billing SET period_end=clock_timestamp()-interval '1 second' WHERE company_id=co;
 PERFORM qcp_test.throws(format('SELECT create_quote_atomic(%L,%L,%L::jsonb)',co,co,'{"customer_name":"Expired"}'),'QCP01','expired grant cannot create quote');
 s:=qcp_usage_snapshot(co,'acct_P2fixture','test');
 PERFORM qcp_test.check((s->>'available')::boolean=false AND (s->>'quotesUsed')::integer=1,'expired read shows usage without granting capacity');
 FOR before_n IN 1..8 LOOP PERFORM create_quote_atomic(legacy,legacy,'{"customer_name":"Legacy draft"}'); END LOOP;
 PERFORM qcp_test.check((SELECT count(*)=8 FROM quotes WHERE company_id=legacy),'legacy quote gateway retains supplied unlimited draft behavior');
 PERFORM qcp_test.check((SELECT count(*)=0 FROM qcp_usage_ledger WHERE company_id=legacy),'legacy activity does not enter custom ledger');
END $$;
DO $$ DECLARE co uuid:=qcp_test.add_company(true,qcp_test.default_limits()); s jsonb; x jsonb; y jsonb; z jsonb; ctx jsonb; n bigint;
BEGIN
 x:=qcp_begin_scan(co,'acct_P2fixture','test','outline-high',repeat('a',64),'{"stage":"scan1","quality":"high"}');
 PERFORM qcp_test.check((x->>'cost')::integer=12,'High outline reserves 12 Scan Tokens');
 y:=qcp_begin_scan(co,'acct_P2fixture','test','outline-high',repeat('a',64),'{"stage":"scan1","quality":"high"}');
 PERFORM qcp_test.check(y->>'decision'='replay' AND y->>'id'=x->>'id','same scan request replays reservation');
 PERFORM qcp_test.throws(format('SELECT qcp_begin_scan(%L,%L,%L,%L,%L,%L::jsonb)',co,'acct_P2fixture','test','outline-high',repeat('b',64),'{"stage":"scan1","quality":"high"}'),'QCP03','same scan request different payload refused');
 PERFORM qcp_finish_scan(co,(x->>'id')::uuid,true,'{"httpStatus":200,"body":{"success":true}}');
 y:=qcp_begin_scan(co,'acct_P2fixture','test','components-high',repeat('b',64),'{"stage":"scan2","quality":"high"}');
 PERFORM qcp_finish_scan(co,(y->>'id')::uuid,true,'{"httpStatus":200,"body":{"success":true}}',NULL,repeat('c',64));
 ctx:=qcp_usage_context(co);
 PERFORM qcp_test.check(qcp_usage_total(co,ctx,'scan')=24,'full High outline plus components uses 24 tokens');
 z:=qcp_begin_scan(co,'acct_P2fixture','test','component-tail',repeat('d',64),jsonb_build_object('stage','scan3','quality','high','tailHash',repeat('c',64)),(y->>'id')::uuid);
 PERFORM qcp_test.check((z->>'cost')::integer=0 AND qcp_usage_total(co,ctx,'scan')=24,'bound classification tail adds no second component debit');
 s:=qcp_begin_scan(co,'acct_P2fixture','test','another-tail-key',repeat('d',64),jsonb_build_object('stage','scan3','quality','high','tailHash',repeat('c',64)),(y->>'id')::uuid);
 PERFORM qcp_test.check(s->>'decision'='replay' AND s->>'id'=z->>'id','new key cannot run paid component tail twice');
 PERFORM qcp_test.throws(format('SELECT qcp_begin_scan(%L,%L,%L,%L,%L,%L::jsonb,%L)',co,'acct_P2fixture','test','changed-tail',repeat('d',64),jsonb_build_object('stage','scan3','quality','high','tailHash',repeat('e',64)),y->>'id'),'QCP03','changed tail proof refused');
 PERFORM qcp_test.renew(co);
 PERFORM qcp_finish_scan(co,(z->>'id')::uuid,false,'{"httpStatus":502,"body":{"success":false}}','scan_failed');
 PERFORM qcp_test.check((SELECT state='refunded' FROM qcp_usage_ledger WHERE id=(y->>'id')::uuid),'failed tail refunds original component debit');
 PERFORM qcp_test.check(qcp_usage_total(co,qcp_usage_context(co),'scan')=0,'late refund does not credit new billing period');
 PERFORM qcp_finish_scan(co,(z->>'id')::uuid,false,'{}','scan_failed');
 PERFORM qcp_test.check(qcp_usage_total(co,ctx,'scan')=12,'duplicate failed completion does not refund twice');
 x:=qcp_begin_scan(co,'acct_P2fixture','test','new-low-scan',repeat('e',64),'{"stage":"scan1","quality":"low"}');
 y:=qcp_begin_scan(co,'acct_P2fixture','test','new-medium-scan',repeat('f',64),'{"stage":"scan1","quality":"medium"}');
 PERFORM qcp_test.check((x->>'cost')::integer=2 AND (y->>'cost')::integer=6,'Low and Medium use existing 2 and 6 costs');
 PERFORM qcp_test.throws(format('UPDATE companies SET ai_assist_points_used=1 WHERE id=%L',co),'QCP04','old counter path cannot charge custom account');
 PERFORM qcp_test.throws(format('INSERT INTO ai_scan_jobs(company_id) VALUES(%L)',co),'QCP04','direct queue insertion cannot bypass custom scan protocol');
 PERFORM qcp_test.throws(format('INSERT INTO calibration_runs(company_id) VALUES(%L)',co),'QCP04','unadapted calibration cannot bypass custom scan protocol');
END $$;
DO $$ DECLARE co uuid:=qcp_test.add_company(true,qcp_test.default_limits()); cv uuid:=qcp_test.new_conversation(co);
 cv2 uuid; a record; b record; r jsonb; call_id uuid;
BEGIN
 PERFORM set_config('test.uid',co::text,true);
 PERFORM qcp_test.throws(format('SELECT * FROM sa_admit_run(%L,%L,%L)',cv,'First task','request-0001'),'QCP08','unwired provider adapter blocks task without charging');
 PERFORM qcp_test.check((SELECT count(*)=0 FROM assistant_turn_reservations WHERE company_id=co),'blocked task has no durable reservation');
 PERFORM qcp_test.check((SELECT count(*)=0 FROM smart_assistant_runs WHERE company_id=co),'failed admission rolls back run insert');
 PERFORM qcp_test.enable_policy();
 SELECT * INTO a FROM sa_admit_run(cv,'First task','request-0001');
 PERFORM qcp_test.check(a.ok AND a.status='accepted','accepted request debits one task');
 SELECT * INTO b FROM sa_admit_run(cv,'First task','request-0001');
 PERFORM qcp_test.check(b.status='duplicate' AND b.run_id=a.run_id,'duplicate request returns original run');
 PERFORM qcp_test.check(qcp_usage_total(co,qcp_usage_context(co),'assistant')=1,'duplicate does not debit second Assistant Task');
 r:=qcp_begin_assistant_call(co,a.run_id,'acct_P2fixture','test','call-1',repeat('a',64),150,50);call_id:=(r->>'id')::uuid;
 PERFORM qcp_test.check((SELECT charged_tokens=150 FROM qcp_assistant_provider_calls WHERE id=call_id),'provider reserves full internal token bound');
 PERFORM qcp_test.throws(format('SELECT qcp_begin_assistant_call(%L,%L,%L,%L,%L,%L,150,50)',co,a.run_id,'acct_P2fixture','test','call-1',repeat('a',64)),'QCP03','duplicate provider call cannot execute again');
 PERFORM qcp_finish_assistant_call(co,call_id,NULL);
 PERFORM qcp_test.check((SELECT charged_tokens=150 AND state='uncertain' FROM qcp_assistant_provider_calls WHERE id=call_id),'unknown provider usage retains ceiling');
 PERFORM qcp_finish_assistant_call(co,call_id,75);
 PERFORM qcp_test.check((SELECT charged_tokens=75 AND state='settled' FROM qcp_assistant_provider_calls WHERE id=call_id),'measured provider usage releases only unused reservation');
 PERFORM qcp_test.check(qcp_usage_total(co,qcp_usage_context(co),'assistant')=1,'internal provider calls do not become customer tasks');
 cv2:=qcp_test.new_conversation(co);SELECT * INTO b FROM sa_admit_run(cv2,'Second task','request-0002');
 SELECT * INTO b FROM sa_admit_run(qcp_test.new_conversation(co),'Third task','request-0003');
 PERFORM qcp_test.check(NOT b.ok AND b.error_code='quota_exceeded','task cap refuses third accepted request');
 SELECT * INTO b FROM sa_admit_run(cv,'First task','request-0001');
 PERFORM qcp_test.check(b.status='duplicate','duplicate still resolves after allowance exhausted');
 DELETE FROM smart_assistant_runs WHERE id=a.run_id;
 PERFORM qcp_test.check(qcp_usage_total(co,qcp_usage_context(co),'assistant')=2,'deleting transcript/run does not replenish tasks');
END $$;
DO $$ DECLARE co uuid:=qcp_test.add_company(true,qcp_test.default_limits()); p text:=co::text||'/plan.pdf'; p2 text:=co::text||'/second.pdf'; r jsonb;
BEGIN
 INSERT INTO storage.objects(bucket_id,name,metadata) VALUES('docs',p,'{"size":60}'),('docs',p2,'{"size":60}');
 r:=qcp_reserve_storage(co,'acct_P2fixture','test','docs',p,60);
 PERFORM qcp_test.check((r->>'reservedBytes')::integer=60 AND qcp_storage_pending_bytes(co)=60,'actual uploaded bytes held until metadata commit');
 PERFORM qcp_test.throws(format('SELECT qcp_reserve_storage(%L,%L,%L,%L,%L,1)',co,'acct_P2fixture','test','docs',p),'QCP03','browser cannot understate actual Storage size');
 PERFORM qcp_test.throws(format('SELECT qcp_reserve_storage(%L,%L,%L,%L,%L,60)',co,'acct_P2fixture','test','docs',p2),'QCP06','second pending upload cannot oversubscribe storage');
 INSERT INTO quote_files(company_id,storage_path,file_size) VALUES(co,p,60);
 PERFORM qcp_test.check((SELECT storage_used_bytes=60 FROM companies WHERE id=co) AND qcp_storage_pending_bytes(co)=0,'metadata commit moves held bytes into existing counter');
 PERFORM qcp_reserve_storage(co,'acct_P2fixture','test','docs',p,60);
 INSERT INTO quote_files(company_id,storage_path,file_size) VALUES(co,p,60) ON CONFLICT(storage_path) DO UPDATE SET file_size=EXCLUDED.file_size;
 PERFORM qcp_test.check((SELECT storage_used_bytes=60 FROM companies WHERE id=co) AND qcp_storage_pending_bytes(co)=0,'metadata retry does not double-charge bytes');
 PERFORM qcp_test.check(NOT qcp_claim_storage_cleanup(co,'docs',p),'cleanup cannot delete a registered file');
 DELETE FROM quote_files WHERE company_id=co AND storage_path=p;
 PERFORM qcp_test.check((SELECT storage_used_bytes=0 FROM companies WHERE id=co) AND qcp_storage_pending_bytes(co)=60,'metadata deletion retains bytes until Storage removal confirmed');
 PERFORM qcp_test.check(NOT qcp_ack_storage_removed(co,'docs',p),'live Storage object prevents premature release');
 PERFORM qcp_test.throws(format('INSERT INTO quote_files(company_id,storage_path,file_size) VALUES(%L,%L,60)',co,p),'QCP07','cleanup tombstone prevents racing re-registration');
 -- SIMULATED Storage API success, allowed only in this disposable fixture.
 DELETE FROM storage.objects WHERE bucket_id='docs' AND name=p;
 PERFORM qcp_test.check(qcp_ack_storage_removed(co,'docs',p) AND qcp_storage_pending_bytes(co)=0,'confirmed object absence releases held bytes');
 PERFORM qcp_test.throws(format('INSERT INTO quote_files(company_id,storage_path,file_size) VALUES(%L,%L,60)',co,p2),'QCP07','direct custom metadata insert without server hold denied');
END $$;
DO $$ DECLARE t text; f text; BEGIN
 FOREACH t IN ARRAY ARRAY['qcp_usage_ledger','qcp_storage_holds','qcp_assistant_budget_policies','qcp_assistant_provider_calls'] LOOP
 PERFORM qcp_test.check(NOT has_table_privilege('authenticated','public.'||t,'INSERT'),'authenticated cannot insert '||t);
 PERFORM qcp_test.check(NOT has_table_privilege('anon','public.'||t,'SELECT'),'anonymous cannot read '||t);
 END LOOP;
 PERFORM qcp_test.check(NOT has_function_privilege('authenticated','public.qcp_finish_scan(uuid,uuid,boolean,jsonb,text,text)','EXECUTE'),'client cannot certify scan/refund');
 PERFORM qcp_test.check(NOT has_function_privilege('authenticated','public.qcp_finish_assistant_call(uuid,uuid,bigint)','EXECUTE'),'client cannot certify provider usage');
 PERFORM qcp_test.check(NOT has_function_privilege('authenticated','public.qcp_reserve_storage(uuid,text,text,text,text,bigint,text)','EXECUTE'),'client cannot certify uploaded byte size');
END $$;
SELECT jsonb_build_object('sql_contract_assertions',count(*),'status','passed') FROM qcp_test.results;
