import { tokenFallbacks } from './theme';
/** Scoped optical composition of the supplied QcButton/QcDialog/IF-01 recipes.
 * Kept in Shadow DOM so no takeoff, pricing or document styles are changed. */
export const styles = `
.qc-boundary-row{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:8px 0;font-size:12px;}
.qc-boundary-row button{white-space:nowrap;}
.qc-approval-note{margin:12px 0 8px;}

:host{${tokenFallbacks}display:block;height:100%;box-sizing:border-box;color:var(--of-text-body);background:var(--of-bg-app);font:var(--of-font-size-body)/var(--of-line-body) var(--of-font-sans)}
*{box-sizing:border-box}button,input,select,textarea{font:inherit}button{display:inline-flex;align-items:center;justify-content:center;gap:var(--of-space-2);min-height:var(--of-control-md);padding:8px 12px;border:1px solid var(--of-border-control);border-radius:var(--of-radius-control);background:var(--of-bg-surface);color:var(--of-text-primary);cursor:pointer;font-weight:600;transition:background var(--of-motion-fast),color var(--of-motion-fast),border-color var(--of-motion-fast),box-shadow var(--of-motion-fast)}
button.primary{background:var(--of-gradient-primary);border-color:var(--of-color-orange-ink);color:var(--of-action-primary-text)}button.secondary{background:var(--of-action-secondary-bg);color:var(--of-action-secondary-text);border-color:var(--of-action-secondary-bg)}button.quiet-danger{color:var(--of-color-danger);border-color:var(--of-color-danger);background:var(--of-bg-surface)}button.active,button[aria-pressed=true]{background:var(--of-selected-bg);color:var(--of-selected-text);border-color:var(--of-focus-ring);box-shadow:inset 0 0 0 1px var(--of-focus-ring)}button.qc-icon-button{padding:8px;width:40px;flex-shrink:0}.qc-icon{flex-shrink:0;pointer-events:none}
@media(hover:hover){button:not(:disabled):hover,summary:hover{background:var(--of-color-orange-wash);border-color:var(--of-color-orange-ink)}button.primary:not(:disabled):hover{background:var(--of-gradient-primary-hover);box-shadow:var(--of-glow-hover)}button.secondary:not(:disabled):hover{background:var(--of-color-text);border-color:var(--of-color-text)}button.quiet-danger:not(:disabled):hover{background:var(--of-color-danger-bg);border-color:var(--of-color-danger)}button.active:not(:disabled):hover,button[aria-pressed=true]:not(:disabled):hover{background:var(--of-color-orange-tint)}}
button:not(:disabled):active,summary:active{background:var(--of-color-orange-tint);box-shadow:inset 0 2px 3px rgba(25,27,32,.12)}button.primary:not(:disabled):active{background:var(--of-gradient-primary-pressed)}button.secondary:not(:disabled):active{background:var(--of-color-text)}button.quiet-danger:not(:disabled):active{background:var(--of-color-danger-bg)}button:disabled{background:var(--of-color-disabled-bg);color:var(--of-color-disabled-ink);border-color:var(--of-border-divider);box-shadow:none;cursor:not-allowed}
:where(button,input,select,textarea,summary,[tabindex]):focus-visible{outline:2px solid var(--of-focus-ring);outline-offset:3px}input[type=checkbox]{accent-color:var(--of-color-orange-ink);width:16px;height:16px;flex-shrink:0;margin:2px 0 0}
.qc-app{height:100%;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;min-height:0}.qc-header{display:flex;align-items:center;justify-content:space-between;gap:var(--of-space-4);padding:var(--of-space-4) var(--of-space-6);background:var(--of-bg-surface);border-bottom:1px solid var(--of-border-divider)}.qc-brand-mark{width:36px;height:36px;border-radius:var(--of-radius-control);background:var(--of-color-orange-wash);color:var(--of-color-orange-ink);display:grid;place-items:center;border:1px solid var(--of-color-orange-tint)}.qc-title{display:flex;align-items:center;gap:12px}.qc-header h1{font-size:20px;line-height:1.25;letter-spacing:-.35px;margin:0;color:var(--of-text-primary);font-weight:700}.qc-header p{font-size:12px;margin:3px 0 0;color:var(--of-text-secondary)}.qc-badge{font-size:11px;padding:4px 10px;border-radius:var(--of-radius-pill);border:1px solid var(--of-border-divider);color:var(--of-text-secondary);background:var(--of-bg-subtle);white-space:nowrap}.qc-topbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:10px 16px;background:var(--of-bg-surface);border-bottom:1px solid var(--of-border-divider)}.qc-spacer{flex:1}.qc-step{display:flex;align-items:center;gap:7px;font-size:12px;color:var(--of-text-secondary);font-weight:600}.qc-step b{display:grid;place-items:center;width:24px;height:24px;border-radius:var(--of-radius-pill);background:var(--of-bg-subtle);color:var(--of-text-secondary)}.qc-step[aria-current=step]{color:var(--of-selected-text)}.qc-step[aria-current=step] b{background:var(--of-color-orange-tint);color:var(--of-color-orange-ink)}
.qc-main{display:grid;grid-template-columns:minmax(0,1fr) 350px;min-height:0}.qc-viewport{position:relative;min-width:0;min-height:260px;overflow:hidden;padding:16px;background:var(--of-bg-app)}.qc-canvas{height:100%;background:var(--of-bg-surface);border:1px solid var(--of-border-divider);border-radius:var(--of-radius-card);overflow:hidden;touch-action:none}.qc-canvas[data-pan=true],.qc-canvas[data-pan=true] *{cursor:grab!important}.qc-canvas[data-dragging=true],.qc-canvas[data-dragging=true] *{cursor:grabbing!important}.qc-help{position:absolute;bottom:24px;left:24px;max-width:calc(100% - 48px);font-size:11px;color:var(--of-text-secondary);pointer-events:none;background:var(--of-glass-b-bg);border:1px solid var(--of-border-divider);border-radius:var(--of-radius-small);padding:6px 10px}.qc-sidebar{background:var(--of-bg-surface);border-left:1px solid var(--of-border-divider);overflow:auto;padding:20px;scrollbar-gutter:stable}.qc-sidebar h2{color:var(--of-text-primary);font-size:16px;line-height:1.3;margin:0 0 8px}.qc-sidebar h3{font-size:13px;margin:20px 0 10px;color:var(--of-text-primary);font-weight:650}.qc-muted{color:var(--of-text-secondary);font-size:12px;line-height:1.55;overflow-wrap:anywhere}.qc-note{border:1px solid var(--of-color-warning-ink);background:var(--of-color-warning-bg);color:var(--of-color-warning-ink);border-radius:var(--of-radius-small);padding:12px;margin:10px 0;font-size:12px;line-height:1.5;overflow-wrap:anywhere}.qc-error{border-color:var(--of-color-danger);background:var(--of-color-danger-bg);color:var(--of-color-danger)}.qc-success{border-color:var(--of-color-success-ink);background:var(--of-color-success-bg);color:var(--of-color-success-ink)}.qc-notice{background:var(--of-color-orange-wash);border:1px solid var(--of-color-orange-ink);color:var(--of-color-orange-ink);border-radius:var(--of-radius-small);font-size:12px;line-height:1.5;padding:10px 12px;margin:0 0 12px}.qc-note button{margin-top:8px;font-size:12px}.qc-check-row{display:flex;gap:8px;align-items:flex-start}.qc-check-row p{margin:0}.qc-check-title{display:flex;align-items:center;gap:8px;font-weight:650}.qc-diagnostic{border:1px solid var(--of-border-divider);border-radius:var(--of-radius-small);padding:10px;margin:8px 0;font-size:12px}.qc-diagnostic strong{display:block}.qc-diagnostic p{margin:4px 0}.qc-diagnostic button{font-size:12px;min-height:32px;padding:4px 8px}.qc-issue-list{margin:12px 0}.qc-view-issues{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.qc-view-issues button{font-size:12px}
.qc-face-tools{position:relative;top:auto;z-index:var(--of-z-sticky);padding:12px;margin:12px -1px;border:1px solid var(--of-color-orange-ink);border-radius:var(--of-radius-control);background:var(--of-bg-surface);box-shadow:var(--of-shadow-raised)}.qc-face-tools-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.qc-face-tools-head strong{color:var(--of-text-primary);font-size:14px}.qc-face-tools small{display:block;font-size:11px;color:var(--of-text-secondary);margin-top:4px}.qc-quick-actions{display:flex;gap:6px;margin-top:10px}.qc-quick-actions button{font-size:12px;flex:1;min-width:0}.qc-face-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:12px 0}.qc-face-grid .qc-face{display:flex;align-items:center;justify-content:space-between;text-align:left;font-size:12px;padding:8px 10px;gap:5px;min-width:0}.qc-face-label{min-width:0;overflow-wrap:anywhere}.qc-face-meta{display:flex;gap:4px;align-items:center;flex-shrink:0}.qc-face[data-hidden=true]{border-style:dashed;color:var(--of-text-secondary);background:var(--of-bg-subtle)}.qc-small-tag{font-size:10px;border:1px solid var(--of-color-warning-ink);color:var(--of-color-warning-ink);border-radius:var(--of-radius-pill);padding:1px 5px;background:var(--of-color-warning-bg)}.qc-hidden-summary{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:12px;color:var(--of-text-secondary)}.qc-hidden-summary button{font-size:12px}
.qc-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}.qc-fields label,.qc-field{display:flex;flex-direction:column;gap:6px;font-size:12px;color:var(--of-text-secondary)}.qc-fields input,.qc-fields select,.qc-field input,.qc-field select,.qc-field textarea{background:var(--of-bg-surface);color:var(--of-text-primary);border:1px solid var(--of-border-control);border-radius:var(--of-radius-small);min-height:var(--of-control-md);padding:8px;min-width:0;width:100%}.qc-field textarea{min-height:120px;resize:vertical;font:12px/1.5 ui-monospace,monospace}.qc-field{margin:12px 0}.qc-check{display:flex;gap:8px;align-items:flex-start;font-size:12px;line-height:1.5;margin:12px 0;cursor:pointer}.qc-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.qc-actions button{font-size:12px}.qc-wide{width:100%;margin:12px 0}.qc-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 16px;font-size:11px;background:var(--of-bg-surface);color:var(--of-text-secondary);border-top:1px solid var(--of-border-divider)}
.qc-plan-total{margin:8px 0 16px}.qc-plan-total strong{display:block;font-size:24px;line-height:1.3;color:var(--of-text-primary)}.qc-plan-total span{display:block;color:var(--of-text-secondary);font-size:12px;margin-top:4px}.qc-plan-row{display:block;text-align:left;width:100%;border-left:4px solid var(--source-color);margin:8px 0;padding:12px}.qc-plan-row:not(:disabled):hover{border-left-color:var(--source-color)}.qc-plan-row span{display:flex;align-items:center;justify-content:space-between;gap:8px}.qc-plan-row b{font-size:13px}.qc-plan-row strong{font-size:10px;letter-spacing:.15px}.qc-plan-row small{display:block;font-size:12px;color:var(--of-text-secondary);margin-top:4px;line-height:1.45}.qc-plan-row .qc-extra{color:var(--of-color-warning-ink)}.qc-plan-row.selected{background:var(--of-selected-bg);outline:1px solid var(--of-focus-ring)}.qc-selection{padding:12px;border:1px solid var(--of-color-orange-ink);background:var(--of-color-orange-wash);border-radius:var(--of-radius-control);font-size:12px}.qc-selection p{font-size:12px;color:var(--of-text-secondary)}.qc-selection button{font-size:12px;margin:3px}.qc-list{max-height:240px;overflow:auto}.qc-assignment{display:block;text-align:left;width:100%;margin:6px 0;font-size:12px;overflow-wrap:anywhere}.qc-assignment.selected{background:var(--of-selected-bg);border-color:var(--of-focus-ring)}.qc-assignment b{display:block}.qc-stock{width:100%;border-collapse:collapse;font-size:12px}.qc-stock th,.qc-stock td{border-bottom:1px solid var(--of-border-divider);padding:8px 4px;text-align:left}.qc-stock small{display:block;color:var(--of-text-secondary)}.qc-stock th{font-weight:650}.qc-reuse{cursor:grab}.qc-reuse:active{cursor:grabbing}.qc-busy{position:absolute;inset:16px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:16px;background:var(--of-glass-dialog-bg);border-radius:var(--of-radius-card);z-index:var(--of-z-sticky)}.qc-busy strong{color:var(--of-text-primary);font-size:18px}.qc-busy span{color:var(--of-text-secondary)}details{margin:12px 0}summary{color:var(--of-text-body);font-size:12px;cursor:pointer;padding:7px 6px;border-radius:var(--of-radius-small);border:1px solid transparent;font-weight:600;transition:background var(--of-motion-fast),border-color var(--of-motion-fast)}#qc-advanced{border-top:1px solid var(--of-border-divider);padding-top:12px;margin-top:16px}#qc-advanced>summary{font-size:13px}#qc-advanced details{margin:16px 0}.qc-hidden{display:none}.qc-sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media(max-width:1000px){.qc-main{grid-template-columns:minmax(0,1fr) 320px}.qc-sidebar{padding:16px}.qc-face-tools{top:auto}.qc-topbar{gap:6px}.qc-header{padding:12px 16px}}
@media(max-width:700px){.qc-main{display:flex;flex-direction:column;overflow:auto}.qc-viewport{height:48vh;min-height:290px;flex-shrink:0;padding:12px}.qc-sidebar{overflow:visible;border-left:0;border-top:1px solid var(--of-border-divider);padding:16px}.qc-face-tools{position:static}.qc-header{padding:12px}.qc-header h1{font-size:18px}.qc-header p,.qc-badge{display:none}.qc-topbar{padding:8px;gap:6px}.qc-step{font-size:11px}.qc-topbar .qc-spacer{display:none}.qc-step:first-child{margin-right:0}.qc-topbar .qc-nav-divider{flex-basis:100%;height:0}.qc-topbar button{flex-grow:1}.qc-help{bottom:20px;left:20px;max-width:calc(100% - 40px);font-size:10px}.qc-footer{font-size:10px;align-items:flex-start;padding:8px 12px}.qc-footer span:last-child{max-width:100px;text-align:right}.qc-list{max-height:160px}button,.qc-fields input,.qc-fields select,.qc-field input,.qc-field select,.qc-field textarea{min-height:var(--of-touch-min)}button.qc-icon-button{width:var(--of-touch-min)}input,select,textarea{font-size:16px!important}summary{min-height:var(--of-touch-min);padding:11px 6px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{transition:none!important;animation:none!important}}
@media(forced-colors:active){button,.qc-note,.qc-face-tools,.qc-selection,.qc-diagnostic{border:1px solid ButtonText;background:Canvas;color:CanvasText;box-shadow:none}button.primary,button.active,button[aria-pressed=true]{border:2px solid Highlight;background:Canvas;color:CanvasText}button:disabled{color:GrayText;border-color:GrayText}:focus-visible{outline:2px solid Highlight!important}.qc-face[data-hidden=true]{border-style:dashed}.qc-scene{forced-color-adjust:none}}

.qc-canvas-wait{height:100%;display:grid;place-items:center;color:var(--of-text-secondary);font-size:14px}
.qc-layout-picker{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 0 16px}.qc-layout-picker>span{font-size:12px;color:var(--of-text-secondary)}

.qc-material-key{font-size:12px;line-height:1.5}.qc-count-explanation{margin:12px 0;font-size:12px;line-height:1.5}.qc-count-explanation summary{font-weight:600}.qc-count-explanation p{margin:8px 0}

.qc-plan-variants{margin:12px 0 18px}.qc-alternative-options{display:grid;gap:8px;margin:10px 0}.qc-alternative-options button{display:grid;text-align:left;white-space:normal;padding:12px;gap:5px;height:auto}.qc-alternative-options small{font-weight:400;line-height:1.45;color:var(--of-text-secondary)}.qc-plan-comparison{font-size:12px;line-height:1.5;padding:10px;background:var(--of-surface-secondary,#F4F5F7);border-radius:8px}.qc-trace pre{font:11px/1.5 ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere;max-height:340px;overflow:auto;background:#F3F4F6;color:#191B20;padding:10px;border-radius:6px}.qc-trace-events{padding-left:22px;font-size:12px}.qc-trace-events>li{margin:8px 0}.qc-trace-events summary{line-height:1.45;overflow-wrap:anywhere}
/* V2.8: inspect first, numeric detail only on request. */
.qc-direction{scroll-margin-top:12px;margin-top:12px;padding-top:12px;border-top:1px solid var(--of-border-divider)}
.qc-direction-heading{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px;font-size:13px}
.qc-direction-heading small{color:var(--of-text-secondary);font-variant-numeric:tabular-nums}
.qc-direction-buttons{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px}
.qc-direction-buttons button{font-size:23px;padding:4px;min-height:42px}
.qc-direction-custom{margin-top:7px;padding:4px 8px;min-height:32px;font-size:12px;background:transparent}
.qc-direction-required,.qc-flow-missing{font-size:11px;color:var(--of-color-orange-ink);font-weight:600}.qc-flow-missing{white-space:nowrap}
.qc-plan-total .qc-lineal-total{display:block;font-size:26px;color:var(--of-text-primary);font-variant-numeric:tabular-nums;line-height:1.35}
.qc-lineal-total small{font-weight:500;font-size:14px;color:var(--of-text-secondary)}
.qc-quantities{margin:14px 0;font-size:12px;border:1px solid var(--of-border-divider);border-radius:var(--of-radius-control);padding:10px}
.qc-quantity-grid{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px 12px;font-size:12px;align-items:start}
.qc-quantity-grid dt{color:var(--of-text-secondary)}.qc-quantity-grid dd{margin:0;text-align:right;font-weight:600;font-variant-numeric:tabular-nums}
.qc-quantity-proposal{border-top:1px solid var(--of-border-divider);margin-top:12px;padding-top:12px;overflow-wrap:anywhere}
.qc-section-detail{padding:12px;border:1px solid var(--of-border-control);border-radius:var(--of-radius-control);font-size:13px;margin:12px 0;background:var(--of-bg-surface)}
.qc-section-heading{display:flex;justify-content:space-between;align-items:center;gap:8px}.qc-section-heading h3{margin:0;font-size:15px}.qc-section-heading button{padding:4px;min-width:32px;min-height:32px}
.qc-section-detail p{margin:8px 0}.qc-section-detail details{font-size:12px}.qc-section-quantity strong{font-size:20px;display:block;font-variant-numeric:tabular-nums}
.qc-selection-hint{padding:10px 12px;margin:12px 0;background:var(--of-bg-app);border-radius:8px;font-size:12px;color:var(--of-text-secondary);line-height:1.6}
.qc-section-list{display:grid;gap:6px;margin:0 0 12px 12px}.qc-section-list button{display:flex;align-items:flex-start;flex-direction:column;gap:4px;text-align:left;padding:8px 10px;font-size:12px}.qc-section-list small{font-size:11px;color:var(--of-text-secondary);font-weight:400}
.qc-faces-summary{margin:12px 0}.qc-faces-summary>.qc-material-plan{margin-top:12px}
svg [data-section]:focus-visible{outline:none}svg [data-section]:focus-visible>path{stroke:#B63D0A;stroke-width:3}
@media(max-width:700px){.qc-direction-buttons button{min-height:44px}.qc-direction-custom,.qc-section-heading button{min-height:44px}.qc-section-list button{min-height:48px}.qc-quantity-grid{gap:8px}.qc-plan-total .qc-lineal-total{font-size:24px}}
@media(forced-colors:active){.qc-section-detail,.qc-quantities{border-color:CanvasText}svg [data-section]:focus-visible>path{stroke:Highlight}.qc-flow-missing{color:CanvasText}}


.qc-canvas[data-drawing=true]:not([data-pan=true]),.qc-canvas[data-drawing=true]:not([data-pan=true]) *{cursor:crosshair!important}
.qc-simple-section{display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px 14px;font-size:13px;margin:14px 0}.qc-simple-section dt{color:var(--of-text-secondary)}.qc-simple-section dd{margin:0;font-weight:600;text-align:right}.qc-section-heading button{font-size:12px;min-height:32px}
.qc-advisory{border:1px solid var(--of-border-divider);border-radius:var(--of-radius-small);padding:8px 10px;margin:12px 0;font-size:12px}.qc-advisory summary{font-weight:600}.qc-advisory button{min-height:32px;padding:4px 12px}.qc-repair-card{background:var(--of-bg-surface);padding:10px;border-radius:var(--of-radius-small)}#qc-drawing-settings pre{font-size:11px;max-height:200px;overflow:auto} .qc-note small{display:block;margin-top:8px}

.qc-save-status{font-size:11px;color:var(--of-text-secondary);max-width:190px}.qc-resume .qc-actions{display:flex;flex-wrap:wrap;gap:6px}@media(max-width:700px){.qc-save-status{max-width:110px;font-size:10px}}

/* V2.15: comparisons beside the plan selector, not below a scrolling inspector. */
.qc-choice-title{font-size:14px;font-weight:650;margin:10px 0 4px}
.qc-choice-description{margin:4px 0 10px}.qc-plan-variants .qc-field{margin-top:0}
.qc-plan-comparison{padding:12px;border:1px solid var(--of-border-divider);background:var(--of-bg-surface)}
.qc-plan-comparison>small{color:var(--of-text-secondary);display:block}
.qc-plan-comparison .qc-comparison-amount{display:block;font-size:17px;line-height:1.4;color:var(--of-text-primary);margin:4px 0}
.qc-plan-comparison p{margin:5px 0}.qc-plan-comparison .qc-work-changes{margin:6px 0 0}.qc-work-changes summary{padding-left:0}
.qc-alternative-options button>span{display:flex;align-items:center;justify-content:space-between;gap:8px}
.qc-alternative-anchor{font-size:11px;margin:5px 0}.qc-result-dialog{${tokenFallbacks}background:var(--of-bg-surface);color:var(--of-text-body);border:1px solid var(--of-border-divider);border-radius:var(--of-radius-dialog);box-shadow:var(--of-shadow-dialog);padding:24px;width:min(440px,calc(100vw - 32px));max-width:calc(100vw - 32px);max-height:calc(100dvh - 32px);overflow:auto;box-sizing:border-box}
.qc-result-dialog::backdrop{background:rgba(25,27,32,.22)}
.qc-result-dialog h2{margin:0 0 12px;font-size:20px;line-height:1.35;color:var(--of-text-primary)}
.qc-result-dialog p{font-size:14px;line-height:1.55;margin:10px 0}.qc-result-dialog .qc-muted{font-size:12px}
.qc-result-dialog button{width:100%;margin-top:12px}
@media(forced-colors:active){.qc-result-dialog{background:Canvas;color:CanvasText;border-color:CanvasText}.qc-plan-comparison{border-color:CanvasText}}

.qc-salvage-offer,.qc-salvage-summary{border:1px solid #d5dae3;border-radius:12px;padding:14px;margin:14px 0;background:#fff}
.qc-salvage-offer p,.qc-salvage-summary p{font-size:13px;line-height:1.5;margin:8px 0}
.qc-salvage-offer small{display:block;color:#596273;line-height:1.5;margin-top:8px}
.qc-salvage-group{padding:12px 0;border-top:1px solid #e1e4ea;margin-top:12px}
.qc-salvage-sequence{background:#fff5ed;padding:10px;border-radius:8px}
.qc-salvage-table{overflow-x:auto}.qc-salvage-summary .qc-actions{flex-wrap:wrap;gap:8px}
.qc-salvage-summary button[aria-pressed="true"]{border-color:#c2410c;background:#fff5ed}
`;
