/** Shared by visible, server-rendered help and FAQ structured data. */
export const QUOTE_FAQS = [
  {q:'How many quotes can I create for free?',a:'Guests can generate 2 documents and make 1 AI extraction request per day. A free verified account gets 10 documents and 3 AI requests per day. Document allowances are shared across quotes, invoices and purchase orders. Typed and photo-based AI requests share one AI allowance. The server uses 24-hour windows, not necessarily a midnight reset.'},
  {q:'How do I remove QuoteCore+ branding?',a:'Generate your quote, then choose Remove branding — free. Continue with Google or verify your email. Once your account is confirmed, branding is removed automatically, without generating the same quote again. A free tools account does not include the separate paid QuoteCore+ app.'},
  {q:'How do I save my quote as a PDF?',a:'Review your quote and select Generate quote. Then choose Print / Save PDF and select Save as PDF in your browser’s print dialog. Turn off the browser’s headers and footers for a clean document. Nothing is emailed to your customer automatically.'},
  {q:'Can Quote Assist fill in the quote for me?',a:'Yes. Use Quote Assist above the form to describe a job, paste existing details or upload a photo. Review the extracted details before adding them to your quote. Check all quantities, units and prices. An extraction request uses the shared AI allowance even when you do not apply the result. You can always enter details manually.'},
  {q:'Will my work be saved?',a:'Your draft stays in this browser tab when storage is available. It is not automatically saved to your account or the paid app. Export your PDF before closing the tab. When you choose to sign in, a device-local backup allows your quote to return after verification; it expires after one hour and is cleared after successful sign-in. Optional Quote Assist sends your supplied text or photo for processing only when you choose Extract.'},
  {q:'Can I add my logo, tax and terms?',a:'Yes. Add a PNG, JPEG or WebP logo, business and customer details, line items and notes. Tax can be switched off, renamed or adjusted. Check the tax settings for your business before sharing the quote.'},
  {q:'Can I turn the quote into an invoice or order?',a:'After generating, open Use these items in another free tool. You can transfer visible line items into the existing invoice, purchase order or margin tools. Recheck tax, totals and document settings in the destination; hidden items are not transferred.'},
];
