name: Deploy to Testing

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy hook
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_4OuiZTxRmc1W5NDWtDAFbzv4s4An/EC9OsWHTA2"
